/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var v;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);
(function(a){function b(k,n){if("function"===typeof window.CustomEvent)return new CustomEvent(k,n);var p=document.createEvent("CustomEvent");p.initCustomEvent(k,!!n.bubbles,!!n.cancelable,n.detail);return p}function c(k){if(P)return k.ownerDocument!==document?k.ownerDocument:null;var n=k.__importDoc;if(!n&&k.parentNode){n=k.parentNode;if("function"===typeof n.closest)n=n.closest("link[rel=import]");else for(;!h(n)&&(n=n.parentNode););k.__importDoc=n}return n}function d(k){var n=q(document,"link[rel=import]:not([import-dependency])"),
p=n.length;p?t(n,function(r){return g(r,function(){0===--p&&k()})}):k()}function e(k){function n(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",n),k())}document.addEventListener("readystatechange",n);n()}function f(k){e(function(){return d(function(){return k&&k()})})}function g(k,n){if(k.__loaded)n&&n();else if("script"===k.localName&&!k.src||"style"===k.localName&&!k.firstChild||"style"===k.localName&&"http://www.w3.org/2000/svg"===k.namespaceURI)k.__loaded=
!0,n&&n();else{var p=function(r){k.removeEventListener(r.type,p);k.__loaded=!0;n&&n()};k.addEventListener("load",p);"style"===k.localName&&(Wa||sa)||k.addEventListener("error",p)}}function h(k){return k.nodeType===Node.ELEMENT_NODE&&"link"===k.localName&&"import"===k.rel}function m(){var k=this;this.g={};this.h=0;this.i=new MutationObserver(function(n){return k.Qa(n)});this.i.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}function l(k){t(q(k,"template"),function(n){n instanceof
HTMLTemplateElement&&(t(q(n.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]'),function(p){var r=document.createElement("script");t(p.attributes,function(y){return r.setAttribute(y.name,y.value)});r.textContent=p.textContent;p.parentNode.replaceChild(r,p)}),l(n.content))})}function q(k,n){return k.childNodes.length?k.querySelectorAll(n):X}function t(k,n,p){var r=k?k.length:0,y=p?-1:1;for(p=p?r-1:0;p<r&&0<=p;p+=y)n(k[p],p)}var B=
document.createElement("link"),P="import"in B,X=B.querySelectorAll("*"),Xa=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return Xa||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var Kd=/(url\()([^)]*)(\))/g,Ld=/(@import[\s]+(?!url\())([^;]*)(;)/g,Md=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,K={Ca:function(k,n){k.href&&k.setAttribute("href",K.V(k.getAttribute("href"),n));k.src&&k.setAttribute("src",
K.V(k.getAttribute("src"),n));if("style"===k.localName){var p=K.la(k.textContent,n,Kd);k.textContent=K.la(p,n,Ld)}},la:function(k,n,p){return k.replace(p,function(r,y,u,A){r=u.replace(/["']/g,"");n&&(r=K.V(r,n));return y+"'"+r+"'"+A})},V:function(k,n){if(void 0===K.Y){K.Y=!1;try{var p=new URL("b","http://a");p.pathname="c%20d";K.Y="http://a/c%20d"===p.href}catch(r){}}if(K.Y)return(new URL(k,n)).href;p=K.ta;p||(p=document.implementation.createHTMLDocument("temp"),K.ta=p,p.ea=p.createElement("base"),
p.head.appendChild(p.ea),p.da=p.createElement("a"));p.ea.href=n;p.da.href=k;return p.da.href||k}},Sb={async:!0,load:function(k,n,p){if(k)if(k.match(/^data:/)){k=k.split(",");var r=k[1];r=-1<k[0].indexOf(";base64")?atob(r):decodeURIComponent(r);n(r)}else{var y=new XMLHttpRequest;y.open("GET",k,Sb.async);y.onerror=function(){p(null)};y.onload=function(){var u,A=null!=(u=y.responseURL||y.getResponseHeader("Location"))?u:void 0;A&&0===A.indexOf("/")&&(A=(location.origin||location.protocol+"//"+location.host)+
A);u=y.response||y.responseText;304===y.status||0===y.status||200<=y.status&&300>y.status?n(u,A):p(u)};y.send()}else p("error: href must be specified")}},Wa=/Trident/.test(navigator.userAgent),sa=/Edge\/\d./i.test(navigator.userAgent);m.prototype.loadImports=function(k){var n=this;k=q(k,"link[rel=import]");t(k,function(p){return n.F(p)})};m.prototype.F=function(k){var n=this,p=k.href;if(void 0!==this.g[p]){var r=this.g[p];r&&r.__loaded&&(k.__import=r,this.j(k))}else this.h++,this.g[p]="pending",Sb.load(p,
function(y,u){y=n.na(y,u||p);n.g[p]=y;n.h--;n.loadImports(y);n.H()},function(){n.g[p]=null;n.h--;n.H()})};m.prototype.na=function(k,n){var p=this;if(!k)return document.createDocumentFragment();if(Wa||sa)k=k.replace(Md,function(u,A,ta){return-1===u.indexOf("type=")?A+" type=import-disable "+ta:u});var r=document.createElement("template");r.innerHTML=k;if(r.content)k=r.content,l(k);else for(k=document.createDocumentFragment();r.firstChild;)k.appendChild(r.firstChild);if(r=k.querySelector("base"))n=
K.V(r.getAttribute("href"),n),r.removeAttribute("href");r=q(k,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]');var y=0;t(r,function(u){g(u);K.Ca(u,n);if("style"===u.localName&&p.ia(u)){var A=p.Ja(u);g(A);u.parentNode.replaceChild(A,u);u=A}u.setAttribute("import-dependency","");if("script"===u.localName&&!u.src&&u.textContent){if("module"===
u.type)throw Error("Inline module scripts are not supported in HTML Imports.");u.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(u.textContent+("\n//# sourceURL="+n+(y?"-"+y:"")+".js\n")));u.textContent="";y++}});return k};m.prototype.ia=function(k){return sa&&-1<k.textContent.indexOf("@import")};m.prototype.Ja=function(k){var n=k.ownerDocument.createElement("style");n.textContent=k.textContent;t(k.attributes,function(p){return n.setAttribute(p.name,p.value)});return n};
m.prototype.H=function(){var k=this;if(!this.h){this.i.disconnect();this.flatten(document);var n=!1,p=!1,r=function(){p&&n&&(k.loadImports(document),k.h||(k.i.observe(document.head,{childList:!0,subtree:!0}),k.Oa()))};this.pa(function(){p=!0;r()});this.oa(function(){n=!0;r()})}};m.prototype.flatten=function(k){var n=this;k=q(k,"link[rel=import]");t(k,function(p){var r=n.g[p.href];(p.__import=r)&&r.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(n.g[p.href]=p,p.readyState="loading",p.__import=p,n.flatten(r),
p.appendChild(r))})};m.prototype.oa=function(k){function n(y){if(y<r){var u=p[y],A=document.createElement("script");u.removeAttribute("import-dependency");t(u.attributes,function(ta){return A.setAttribute(ta.name,ta.value)});Xa=A;u.parentNode.replaceChild(A,u);g(A,function(){Xa=null;n(y+1)})}else k()}var p=q(document,"script[import-dependency]"),r=p.length;n(0)};m.prototype.pa=function(k){var n=this,p=q(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),r=p.length;if(r){var y=
(Wa||sa)&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");t(p,function(u){y&&n.ia(u)&&u.ownerDocument.defaultView!==window.top&&(u.__loaded=!0);g(u,function(){u.removeAttribute("import-dependency");0===--r&&k()});if(y&&u.parentNode!==document.head){var A=document.createElement(u.localName);A.__appliedElement=u;A.setAttribute("type","import-placeholder");u.parentNode.insertBefore(A,u.nextSibling);for(A=c(u);A&&c(A);)A=c(A);A.parentNode!==document.head&&(A=null);document.head.insertBefore(u,
A);u.removeAttribute("type")}})}else k()};m.prototype.Oa=function(){var k=this,n=q(document,"link[rel=import]");t(n,function(p){return k.j(p)},!0)};m.prototype.j=function(k){k.__loaded||(k.__loaded=!0,k.import&&(k.import.readyState="complete"),k.dispatchEvent(b(k.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};m.prototype.Qa=function(k){var n=this;t(k,function(p){return t(p.addedNodes,function(r){r&&r.nodeType===Node.ELEMENT_NODE&&(h(r)?n.F(r):n.loadImports(r))})})};var Ya=null;
if(P)B=q(document,"link[rel=import]"),t(B,function(k){k.import&&"loading"===k.import.readyState||(k.__loaded=!0)}),B=function(k){k=k.target;h(k)&&(k.__loaded=!0)},document.addEventListener("load",B,!0),document.addEventListener("error",B,!0);else{var ka=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!ka||ka.configurable?Node:Element).prototype,"baseURI",{get:function(){var k=h(this)?this:c(this);return k?k.href:ka&&ka.get?ka.get.call(this):(document.querySelector("base")||
window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});e(function(){Ya=new m})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});a.useNative=P;a.whenReady=f;a.importForElement=c;a.loadImports=function(k){Ya&&Ya.loadImports(k)}})(window.HTMLImports=window.HTMLImports||{});/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function fa(){this.ka=this.root=null;this.T=!1;this.D=this.P=this.$=this.assignedSlot=this.assignedNodes=this.G=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.J=void 0;this.fa=this.ga=!1;this.O={}}fa.prototype.toJSON=function(){return{}};function w(a){a.__shady||(a.__shady=new fa);return a.__shady}function x(a){return a&&a.__shady};var z=window.ShadyDOM||{};z.Ea=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ha=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");z.o=!!(ha&&ha.configurable&&ha.get);z.aa=z.force||!z.Ea;z.I=z.noPatch||!1;z.ja=z.preferPerformance;function C(a){return(a=x(a))&&void 0!==a.firstChild}function D(a){return"ShadyRoot"===a.va}function ia(a){return(a=(a=x(a))&&a.root)&&ja(a)}
var E=Element.prototype,la=E.matches||E.matchesSelector||E.mozMatchesSelector||E.msMatchesSelector||E.oMatchesSelector||E.webkitMatchesSelector,ma=document.createTextNode(""),na=0,oa=[];(new MutationObserver(function(){for(;oa.length;)try{oa.shift()()}catch(a){throw ma.textContent=na++,a;}})).observe(ma,{characterData:!0});function pa(a){oa.push(a);ma.textContent=na++}var qa=!!document.contains;function ra(a,b){for(;b;){if(b==a)return!0;b=b.__shady_parentNode}return!1}
function ua(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(e){return a[e]};a.namedItem=function(e){if("length"!==e&&isNaN(e)&&a[e])return a[e];for(var f=ba(a),g=f.next();!g.done;g=f.next())if(g=g.value,(g.getAttribute("id")||g.getAttribute("name"))==e)return g;return null};return a}
function F(a,b,c,d){c=void 0===c?"":c;for(var e in b){var f=b[e];if(!(d&&0<=d.indexOf(e))){f.configurable=!0;var g=c+e;if(f.value)a[g]=f.value;else try{Object.defineProperty(a,g,f)}catch(h){}}}}function G(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=Object.getOwnPropertyDescriptor(a,c)});return b};var va=[],wa;function xa(a){wa||(wa=!0,pa(ya));va.push(a)}function ya(){wa=!1;for(var a=!!va.length;va.length;)va.shift()();return a}ya.list=va;function za(){this.g=!1;this.addedNodes=[];this.removedNodes=[];this.S=new Set}function Aa(a){a.g||(a.g=!0,pa(function(){a.flush()}))}za.prototype.flush=function(){if(this.g){this.g=!1;var a=this.takeRecords();a.length&&this.S.forEach(function(b){b(a)})}};za.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Ba(a,b){var c=w(a);c.G||(c.G=new za);c.G.S.add(b);var d=c.G;return{ua:b,xa:d,wa:a,takeRecords:function(){return d.takeRecords()}}}function Ca(a){var b=a&&a.xa;b&&(b.S.delete(a.ua),b.S.size||(w(a.wa).G=null))}
function Da(a,b){var c=b.getRootNode();return a.map(function(d){var e=c===d.target.getRootNode();if(e&&d.addedNodes){if(e=Array.from(d.addedNodes).filter(function(f){return c===f.getRootNode()}),e.length)return d=Object.create(d),Object.defineProperty(d,"addedNodes",{value:e,configurable:!0}),d}else if(e)return d}).filter(function(d){return d})};var Ea=/[&\u00A0"]/g,Fa=/[&\u00A0<>]/g;function Ga(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Ha(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Ia=Ha("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Ja=Ha("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function Ka(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g=void 0;e<f&&(g=d[e]);e++){a:{var h=g;var m=a,l=b;switch(h.nodeType){case Node.ELEMENT_NODE:m=h.localName;for(var q="<"+m,t=h.attributes,B=0,P;P=t[B];B++)q+=" "+P.name+'="'+P.value.replace(Ea,Ga)+'"';q+=">";h=Ia[m]?q:q+Ka(h,l)+"</"+m+">";break a;case Node.TEXT_NODE:h=h.data;h=m&&Ja[m.localName]?h:h.replace(Fa,Ga);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var La=z.o,Ma={querySelector:function(a){return this.__shady_native_querySelector(a)},querySelectorAll:function(a){return this.__shady_native_querySelectorAll(a)}},Na={};function Oa(a){Na[a]=function(b){return b["__shady_native_"+a]}}function Pa(a,b){F(a,b,"__shady_native_");for(var c in b)Oa(c)}function H(a,b){b=void 0===b?[]:b;for(var c=0;c<b.length;c++){var d=b[c],e=Object.getOwnPropertyDescriptor(a,d);e&&(Object.defineProperty(a,"__shady_native_"+d,e),e.value?Ma[d]||(Ma[d]=e.value):Oa(d))}}
var I=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),J=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),Qa=document.implementation.createHTMLDocument("inert");function Ra(a){for(var b;b=a.__shady_native_firstChild;)a.__shady_native_removeChild(b)}var Sa=["firstElementChild","lastElementChild","children","childElementCount"],Ta=["querySelector","querySelectorAll"];
function Ua(){var a=["dispatchEvent","addEventListener","removeEventListener"];window.EventTarget?H(window.EventTarget.prototype,a):(H(Node.prototype,a),H(Window.prototype,a));La?H(Node.prototype,"parentNode firstChild lastChild previousSibling nextSibling childNodes parentElement textContent".split(" ")):Pa(Node.prototype,{parentNode:{get:function(){I.currentNode=this;return I.parentNode()}},firstChild:{get:function(){I.currentNode=this;return I.firstChild()}},lastChild:{get:function(){I.currentNode=
this;return I.lastChild()}},previousSibling:{get:function(){I.currentNode=this;return I.previousSibling()}},nextSibling:{get:function(){I.currentNode=this;return I.nextSibling()}},childNodes:{get:function(){var b=[];I.currentNode=this;for(var c=I.firstChild();c;)b.push(c),c=I.nextSibling();return b}},parentElement:{get:function(){J.currentNode=this;return J.parentNode()}},textContent:{get:function(){switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(var b=document.createTreeWalker(this,
NodeFilter.SHOW_TEXT,null,!1),c="",d;d=b.nextNode();)c+=d.nodeValue;return c;default:return this.nodeValue}},set:function(b){if("undefined"===typeof b||null===b)b="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:Ra(this);(0<b.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_native_insertBefore(document.createTextNode(b),void 0);break;default:this.nodeValue=b}}}});H(Node.prototype,"appendChild insertBefore removeChild replaceChild cloneNode contains".split(" "));
a={firstElementChild:{get:function(){J.currentNode=this;return J.firstChild()}},lastElementChild:{get:function(){J.currentNode=this;return J.lastChild()}},children:{get:function(){var b=[];J.currentNode=this;for(var c=J.firstChild();c;)b.push(c),c=J.nextSibling();return ua(b)}},childElementCount:{get:function(){return this.children?this.children.length:0}}};La?(H(Element.prototype,Sa),H(Element.prototype,["previousElementSibling","nextElementSibling","innerHTML"]),Object.getOwnPropertyDescriptor(HTMLElement.prototype,
"children")&&H(HTMLElement.prototype,["children"]),Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&H(HTMLElement.prototype,["innerHTML"])):(Pa(Element.prototype,a),Pa(Element.prototype,{previousElementSibling:{get:function(){J.currentNode=this;return J.previousSibling()}},nextElementSibling:{get:function(){J.currentNode=this;return J.nextSibling()}},innerHTML:{get:function(){return Ka(this,function(b){return b.__shady_native_childNodes})},set:function(b){var c="template"===this.localName?
this.content:this;Ra(c);var d=this.localName||"div";d=this.namespaceURI&&this.namespaceURI!==Qa.namespaceURI?Qa.createElementNS(this.namespaceURI,d):Qa.createElement(d);d.innerHTML=b;for(b="template"===this.localName?d.content:d;d=b.__shady_native_firstChild;)c.__shady_native_insertBefore(d,void 0)}}}));H(Element.prototype,"setAttribute getAttribute hasAttribute removeAttribute focus blur".split(" "));H(Element.prototype,Ta);H(HTMLElement.prototype,["focus","blur","contains"]);La&&H(HTMLElement.prototype,
["parentElement","children","innerHTML"]);window.HTMLTemplateElement&&H(window.HTMLTemplateElement.prototype,["innerHTML"]);La?H(DocumentFragment.prototype,Sa):Pa(DocumentFragment.prototype,a);H(DocumentFragment.prototype,Ta);La?(H(Document.prototype,Sa),H(Document.prototype,["activeElement"])):Pa(Document.prototype,a);H(Document.prototype,["importNode","getElementById"]);H(Document.prototype,Ta)};var Va=G({get childNodes(){return this.__shady_childNodes},get firstChild(){return this.__shady_firstChild},get lastChild(){return this.__shady_lastChild},get textContent(){return this.__shady_textContent},set textContent(a){this.__shady_textContent=a},get childElementCount(){return this.__shady_childElementCount},get children(){return this.__shady_children},get firstElementChild(){return this.__shady_firstElementChild},get lastElementChild(){return this.__shady_lastElementChild},get innerHTML(){return this.__shady_innerHTML},
set innerHTML(a){return this.__shady_innerHTML=a},get shadowRoot(){return this.__shady_shadowRoot}}),Za=G({get parentElement(){return this.__shady_parentElement},get parentNode(){return this.__shady_parentNode},get nextSibling(){return this.__shady_nextSibling},get previousSibling(){return this.__shady_previousSibling},get nextElementSibling(){return this.__shady_nextElementSibling},get previousElementSibling(){return this.__shady_previousElementSibling},get className(){return this.__shady_className},
set className(a){return this.__shady_className=a}}),$a;for($a in Va)Va[$a].enumerable=!1;for(var ab in Za)Za[ab].enumerable=!1;var bb=z.o||z.I,cb=bb?function(){}:function(a){var b=w(a);b.ga||(b.ga=!0,F(a,Za))},db=bb?function(){}:function(a){var b=w(a);b.fa||(b.fa=!0,F(a,Va))};var eb="__eventWrappers"+Date.now(),fb=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),gb={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},hb={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function ib(a){return a instanceof Node?a.__shady_getRootNode():a}function jb(a,b){var c=[],d=a;for(a=ib(a);d;)c.push(d),d=d.__shady_assignedSlot?d.__shady_assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.__shady_parentNode;c[c.length-1]===document&&c.push(window);return c}function kb(a){a.__composedPath||(a.__composedPath=jb(a.target,!0));return a.__composedPath}
function lb(a,b){if(!D)return a;a=jb(a,!0);for(var c=0,d,e=void 0,f,g=void 0;c<b.length;c++)if(d=b[c],f=ib(d),f!==e&&(g=a.indexOf(f),e=f),!D(f)||-1<g)return d}function mb(a){function b(c,d){c=new a(c,d);c.__composed=d&&!!d.composed;return c}b.__proto__=a;b.prototype=a.prototype;return b}var nb={focus:!0,blur:!0};function ob(a){return a.__target!==a.target||a.__relatedTarget!==a.relatedTarget}
function pb(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!ob(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.__immediatePropagationStopped);d++);}
function qb(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];pb(a,d,"capture");if(a.W)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=x(d);f=f&&f.root;if(0===c||f&&f===e)if(pb(a,d,"bubble"),d!==window&&(e=d.__shady_getRootNode()),a.W)break}}
function rb(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],m=h.type,l=h.capture,q=h.once,t=h.passive;if(b===h.node&&c===m&&d===l&&e===q&&f===t)return g}return-1}
function sb(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){if(hb[a])return this.__shady_native_addEventListener(a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.X||this,m=b[eb];if(m){if(-1<rb(m,h,a,e,f,g))return}else b[eb]=[];m=function(l){f&&this.__shady_removeEventListener(a,b,c);l.__target||tb(l);if(h!==this){var q=Object.getOwnPropertyDescriptor(l,"currentTarget");
Object.defineProperty(l,"currentTarget",{get:function(){return h},configurable:!0})}l.__previousCurrentTarget=l.currentTarget;if(!D(h)||-1!=l.composedPath().indexOf(h))if(l.composed||-1<l.composedPath().indexOf(h))if(ob(l)&&l.target===l.relatedTarget)l.eventPhase===Event.BUBBLING_PHASE&&l.stopImmediatePropagation();else if(l.eventPhase===Event.CAPTURING_PHASE||l.bubbles||l.target===h||h instanceof Window){var t="function"===d?b.call(h,l):b.handleEvent&&b.handleEvent(l);h!==this&&(q?(Object.defineProperty(l,
"currentTarget",q),q=null):delete l.currentTarget);return t}};b[eb].push({node:h,type:a,capture:e,once:f,passive:g,Ra:m});nb[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][e?"capture":"bubble"].push(m)):this.__shady_native_addEventListener(a,m,c)}}}
function ub(a,b,c){if(b){if(hb[a])return this.__shady_native_removeEventListener(a,b,c);if(c&&"object"===typeof c){var d=!!c.capture;var e=!!c.once;var f=!!c.passive}else d=!!c,f=e=!1;var g=c&&c.X||this,h=void 0;var m=null;try{m=b[eb]}catch(l){}m&&(e=rb(m,g,a,d,e,f),-1<e&&(h=m.splice(e,1)[0].Ra,m.length||(b[eb]=void 0)));this.__shady_native_removeEventListener(a,h||b,c);h&&nb[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][d?"capture":"bubble"],h=a.indexOf(h),-1<h&&a.splice(h,1))}}
function vb(){for(var a in nb)window.__shady_native_addEventListener(a,function(b){b.__target||(tb(b),qb(b))},!0)}
var wb=G({get composed(){void 0===this.__composed&&(fb?this.__composed="focusin"===this.type||"focusout"===this.type||fb(this):!1!==this.isTrusted&&(this.__composed=gb[this.type]));return this.__composed||!1},composedPath:function(){this.__composedPath||(this.__composedPath=jb(this.__target,this.composed));return this.__composedPath},get target(){return lb(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.__relatedTarget)return null;this.__relatedTargetComposedPath||
(this.__relatedTargetComposedPath=jb(this.__relatedTarget,!0));return lb(this.currentTarget||this.__previousCurrentTarget,this.__relatedTargetComposedPath)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.W=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.W=this.__immediatePropagationStopped=!0}});
function tb(a){a.__target=a.target;a.__relatedTarget=a.relatedTarget;if(z.o){var b=Object.getPrototypeOf(a);if(!Object.hasOwnProperty(b,"__shady_patchedProto")){var c=Object.create(b);c.__shady_sourceProto=b;F(c,wb);b.__shady_patchedProto=c}a.__proto__=b.__shady_patchedProto}else F(a,wb)}var xb=mb(Event),yb=mb(CustomEvent),zb=mb(MouseEvent);
function Ab(){if(!fb&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var b=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.__shady_dispatchEvent(b)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}}var Bb=Object.getOwnPropertyNames(Document.prototype).filter(function(a){return"on"===a.substring(0,2)});function Cb(a,b){return{index:a,K:[],R:b}}
function Db(a,b,c,d){var e=0,f=0,g=0,h=0,m=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<m;g++)if(a[g]!==c[g])break a;g=m}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,q=0;q<m-g&&Eb(a[--h],c[--l]);)q++;h=q}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=Cb(e,0);f<d;)b.K.push(c[f++]);return[b]}if(f==d)return[Cb(e,b-e)];m=e;g=f;d=d-g+1;h=b-m+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(q=1;q<h;q++)if(a[m+q-1]===c[g+l-1])b[l][q]=
b[l-1][q-1];else{var t=b[l-1][q]+1,B=b[l][q-1]+1;b[l][q]=t<B?t:B}m=b.length-1;g=b[0].length-1;d=b[m][g];for(a=[];0<m||0<g;)0==m?(a.push(2),g--):0==g?(a.push(3),m--):(h=b[m-1][g-1],l=b[m-1][g],q=b[m][g-1],t=l<q?l<h?l:h:q<h?q:h,t==h?(h==d?a.push(0):(a.push(1),d=h),m--,g--):t==l?(a.push(3),m--,d=l):(a.push(2),g--,d=q));a.reverse();b=void 0;m=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(m.push(b),b=void 0);e++;f++;break;case 1:b||(b=Cb(e,0));b.R++;e++;b.K.push(c[f]);f++;break;case 2:b||(b=Cb(e,0));
b.R++;e++;break;case 3:b||(b=Cb(e,0)),b.K.push(c[f]),f++}b&&m.push(b);return m}function Eb(a,b){return a===b};function Fb(a,b,c){cb(a);c=c||null;var d=w(a),e=w(b),f=c?w(c):null;d.previousSibling=c?f.previousSibling:b.__shady_lastChild;if(f=x(d.previousSibling))f.nextSibling=a;if(f=x(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function Gb(a,b,c){db(b);var d=w(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){d=a.__shady_childNodes;for(var e=0;e<d.length;e++)Fb(d[e],b,c);a=w(a);b=void 0!==a.firstChild?null:void 0;a.firstChild=a.lastChild=b;a.childNodes=b}else Fb(a,b,c)}
function Hb(a,b){var c=w(a);b=w(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(w(a).nextSibling=d);d&&(w(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function Ib(a){var b=w(a);if(void 0===b.firstChild){b.childNodes=null;var c=b.firstChild=a.__shady_native_firstChild||null;b.lastChild=a.__shady_native_lastChild||null;db(a);b=c;for(c=void 0;b;b=b.__shady_native_nextSibling){var d=w(b);d.parentNode=a;d.nextSibling=b.__shady_native_nextSibling||null;d.previousSibling=c||null;c=b;cb(b)}}};var Jb=null;function L(){Jb||(Jb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return Jb||null}function Kb(a,b){var c=L();c&&c.unscopeNode(a,b)}function Lb(a,b){var c=L();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;a=a.__shady_childNodes;for(var d=0;c&&d<a.length;d++)c=c&&Lb(a[d],b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}function Mb(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=L();return b?b.currentScopeForNode(a):""}
function Nb(a,b){if(a){a.nodeType===Node.ELEMENT_NODE&&b(a);a=a.__shady_childNodes;for(var c=0,d;c<a.length;c++)d=a[c],d.nodeType===Node.ELEMENT_NODE&&Nb(d,b)}};var Ob=window.document,Pb=z.ja,Qb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),Rb=Qb&&Qb.get;function Tb(a){for(var b;b=a.__shady_firstChild;)a.__shady_removeChild(b)}function Ub(a){var b=x(a);if(b&&void 0!==b.J){b=a.__shady_childNodes;for(var c=0,d=b.length,e=void 0;c<d&&(e=b[c]);c++)Ub(e)}if(a=x(a))a.J=void 0}function Vb(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=x(a))&&b.D)&&b.length?b[0]:Vb(a.__shady_nextSibling));return b}
function Wb(a,b,c){if(a=(a=x(a))&&a.G)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Aa(a)}
var Yb=G({get parentNode(){var a=x(this);a=a&&a.parentNode;return void 0!==a?a:this.__shady_native_parentNode},get firstChild(){var a=x(this);a=a&&a.firstChild;return void 0!==a?a:this.__shady_native_firstChild},get lastChild(){var a=x(this);a=a&&a.lastChild;return void 0!==a?a:this.__shady_native_lastChild},get nextSibling(){var a=x(this);a=a&&a.nextSibling;return void 0!==a?a:this.__shady_native_nextSibling},get previousSibling(){var a=x(this);a=a&&a.previousSibling;return void 0!==a?a:this.__shady_native_previousSibling},
get childNodes(){if(C(this)){var a=x(this);if(!a.childNodes){a.childNodes=[];for(var b=this.__shady_firstChild;b;b=b.__shady_nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=this.__shady_native_childNodes;c.item=function(d){return c[d]};return c},get parentElement(){var a=x(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:this.__shady_native_parentElement},get isConnected(){if(Rb&&Rb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;
var a=this.ownerDocument;if(qa){if(a.__shady_native_contains(this))return!0}else if(a.documentElement&&a.documentElement.__shady_native_contains(this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.__shady_parentNode||(D(a)?a.host:void 0);return!!(a&&a instanceof Document)},get textContent(){if(C(this)){for(var a=[],b=0,c=this.__shady_childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&a.push(d.__shady_textContent);return a.join("")}return this.__shady_native_textContent},set textContent(a){if("undefined"===
typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!C(this)&&z.o){var b=this.__shady_firstChild;(b!=this.__shady_lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&Tb(this);this.__shady_native_textContent=a}else Tb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_insertBefore(document.createTextNode(a));break;default:this.nodeValue=a}},insertBefore:function(a,b){if(this.ownerDocument!==Ob&&a.ownerDocument!==Ob)return this.__shady_native_insertBefore(a,
b),a;if(a===this)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(b){var c=x(b);c=c&&c.parentNode;if(void 0!==c&&c!==this||void 0===c&&b.__shady_native_parentNode!==this)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(b===a)return a;var d=[],e=(c=M(this))?c.host.localName:Mb(this),f=a.__shady_parentNode;if(f){var g=Mb(a);f.__shady_removeChild(a,!!c||
!M(a))}f=!0;var h=(!Pb||void 0===a.__noInsertionPoint)&&!Lb(a,e),m=c&&!a.__noInsertionPoint&&(!Pb||a.nodeType===Node.DOCUMENT_FRAGMENT_NODE);if(m||h)h&&(g=g||Mb(a)),Nb(a,function(l){m&&"slot"===l.localName&&d.push(l);if(h){var q=g;L()&&(q&&Kb(l,q),(q=L())&&q.scopeNode(l,e))}});if("slot"===this.localName||d.length)d.length&&(c.i=c.i||[],c.g=c.g||[],c.h=c.h||{},c.i.push.apply(c.i,d instanceof Array?d:ca(ba(d)))),c&&N(c);C(this)&&(Gb(a,this,b),c=x(this),ia(this)?(N(c.root),f=!1):c.root&&(f=!1));f?(c=
D(this)?this.host:this,b?(b=Vb(b),c.__shady_native_insertBefore(a,b)):c.__shady_native_appendChild(a)):a.ownerDocument!==this.ownerDocument&&this.ownerDocument.adoptNode(a);Wb(this,a);return a},appendChild:function(a){return this.__shady_insertBefore(a)},removeChild:function(a,b){b=void 0===b?!1:b;if(this.ownerDocument!==Ob)return this.__shady_native_removeChild(a);if(a.__shady_parentNode!==this)throw Error("The node to be removed is not a child of this node: "+a);var c=M(a),d=c&&Xb(c,a),e=x(this);
if(C(this)&&(Hb(a,this),ia(this))){N(e.root);var f=!0}if(L()&&!b&&c){var g=Mb(a);Nb(a,function(h){Kb(h,g)})}Ub(a);c&&((b=this&&"slot"===this.localName)&&(f=!0),(d||b)&&N(c));f||(f=D(this)?this.host:this,(!e.root&&"slot"!==a.localName||f===a.__shady_native_parentNode)&&f.__shady_native_removeChild(a));Wb(this,null,a);return a},replaceChild:function(a,b){this.__shady_insertBefore(a,b);this.__shady_removeChild(b);return a},cloneNode:function(a){if("template"==this.localName)return this.__shady_native_cloneNode(a);
var b=this.__shady_native_cloneNode(!1);if(a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.__shady_childNodes;for(var c=0,d;c<a.length;c++)d=a[c].__shady_cloneNode(!0),b.__shady_appendChild(d)}return b},getRootNode:function(a){if(this&&this.nodeType){var b=w(this),c=b.J;void 0===c&&(D(this)?(c=this,b.J=c):(c=(c=this.__shady_parentNode)?c.__shady_getRootNode(a):this,document.documentElement.__shady_native_contains(this)&&(b.J=c)));return c}},contains:function(a){return ra(this,a)}});function Zb(a,b,c){var d=[];$b(a.__shady_childNodes,b,c,d);return d}function $b(a,b,c,d){for(var e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var m=b,l=c,q=d,t=m(h);t&&q.push(h);l&&l(t)?h=t:($b(h.__shady_childNodes,m,l,q),h=void 0)}if(h)break}}
var ac=G({get firstElementChild(){var a=x(this);if(a&&void 0!==a.firstChild){for(a=this.__shady_firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_firstElementChild},get lastElementChild(){var a=x(this);if(a&&void 0!==a.lastChild){for(a=this.__shady_lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_lastElementChild},get children(){return C(this)?ua(Array.prototype.filter.call(this.__shady_childNodes,
function(a){return a.nodeType===Node.ELEMENT_NODE})):this.__shady_native_children},get childElementCount(){var a=this.__shady_children;return a?a.length:0}}),bc=G({querySelector:function(a){return Zb(this,function(b){return la.call(b,a)},function(b){return!!b})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(this.__shady_native_querySelectorAll(a));var c=this.__shady_getRootNode();return b.filter(function(d){return d.__shady_getRootNode()==c})}return Zb(this,function(d){return la.call(d,
a)})}}),cc=z.ja?Object.assign({},ac):ac;Object.assign(ac,bc);var dc=G({getElementById:function(a){return""===a?null:Zb(this,function(b){return b.id==a},function(b){return!!b})[0]||null}});var ec=G({get activeElement(){var a=z.o?document.__shady_native_activeElement:document.activeElement;if(!a||!a.nodeType)return null;var b=!!D(this);if(!(this===document||b&&this.host!==a&&this.host.__shady_native_contains(a)))return null;for(b=M(a);b&&b!==this;)a=b.host,b=M(a);return this===document?b?null:a:b===this?a:null}});var fc=document.implementation.createHTMLDocument("inert"),gc=G({get innerHTML(){return C(this)?Ka("template"===this.localName?this.content:this,function(a){return a.__shady_childNodes}):this.__shady_native_innerHTML},set innerHTML(a){if("template"===this.localName)this.__shady_native_innerHTML=a;else{Tb(this);var b=this.localName||"div";b=this.namespaceURI&&this.namespaceURI!==fc.namespaceURI?fc.createElementNS(this.namespaceURI,b):fc.createElement(b);for(z.o?b.__shady_native_innerHTML=a:b.innerHTML=
a;a=b.__shady_firstChild;)this.__shady_insertBefore(a)}}});var hc=G({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.X=this;this.host.__shady_addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.X=this;this.host.__shady_removeEventListener(a,b,c)}});function ic(a,b){F(a,hc,b);F(a,ec,b);F(a,gc,b);F(a,ac,b);z.I&&!b?(F(a,Yb,b),F(a,dc,b)):z.o||(F(a,Za),F(a,Va))};var jc={},O=z.deferConnectionCallbacks&&"loading"===document.readyState,kc;function lc(a){var b=[];do b.unshift(a);while(a=a.__shady_parentNode);return b}
function mc(a,b,c){if(a!==jc)throw new TypeError("Illegal constructor");this.va="ShadyRoot";this.host=b;this.mode=c&&c.mode;Ib(b);a=w(b);a.root=this;a.ka="closed"!==this.mode?this:null;a=w(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;a.childNodes=[];this.Z=this.C=!1;this.i=this.h=this.g=null;if(z.preferPerformance)for(;a=b.__shady_native_firstChild;)b.__shady_native_removeChild(a);else N(this)}function N(a){a.C||(a.C=!0,xa(function(){return nc(a)}))}
function nc(a){var b;if(b=a.C){for(var c;a;)a:{a.C&&(c=a),b=a;a=b.host.__shady_getRootNode();if(D(a)&&(b=x(b.host))&&0<b.N)break a;a=void 0}b=c}(c=b)&&c._renderSelf()}
mc.prototype._renderSelf=function(){var a=O;O=!0;this.C=!1;if(this.g){oc(this);for(var b=0,c;b<this.g.length;b++){c=this.g[b];var d=x(c),e=d.assignedNodes;d.assignedNodes=[];d.D=[];if(d.$=e)for(d=0;d<e.length;d++){var f=x(e[d]);f.P=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(b=this.host.__shady_firstChild;b;b=b.__shady_nextSibling)pc(this,b);for(b=0;b<this.g.length;b++){c=this.g[b];e=x(c);if(!e.assignedNodes.length)for(d=c.__shady_firstChild;d;d=d.__shady_nextSibling)pc(this,d,c);
(d=(d=x(c.__shady_parentNode))&&d.root)&&(ja(d)||d.C)&&d._renderSelf();qc(this,e.D,e.assignedNodes);if(d=e.$){for(f=0;f<d.length;f++)x(d[f]).P=null;e.$=null;d.length>e.assignedNodes.length&&(e.T=!0)}e.T&&(e.T=!1,rc(this,c))}c=this.g;b=[];for(e=0;e<c.length;e++)d=c[e].__shady_parentNode,(f=x(d))&&f.root||!(0>b.indexOf(d))||b.push(d);for(c=0;c<b.length;c++){f=b[c];e=f===this?this.host:f;d=[];f=f.__shady_childNodes;for(var g=0;g<f.length;g++){var h=f[g];if("slot"==h.localName){h=x(h).D;for(var m=0;m<
h.length;m++)d.push(h[m])}else d.push(h)}f=Array.prototype.slice.call(e.__shady_native_childNodes);g=Db(d,d.length,f,f.length);m=h=0;for(var l=void 0;h<g.length&&(l=g[h]);h++){for(var q=0,t=void 0;q<l.K.length&&(t=l.K[q]);q++)t.__shady_native_parentNode===e&&e.__shady_native_removeChild(t),f.splice(l.index+m,1);m-=l.R}m=0;for(l=void 0;m<g.length&&(l=g[m]);m++)for(h=f[l.index],q=l.index;q<l.index+l.R;q++)t=d[q],e.__shady_native_insertBefore(t,h),f.splice(q,0,t)}}if(!z.preferPerformance&&!this.Z)for(b=
this.host.__shady_childNodes,c=0,e=b.length;c<e;c++)d=b[c],f=x(d),d.__shady_native_parentNode!==this.host||"slot"!==d.localName&&f.assignedSlot||this.host.__shady_native_removeChild(d);this.Z=!0;O=a;kc&&kc()};function pc(a,b,c){var d=w(b),e=d.P;d.P=null;c||(c=(a=a.h[b.__shady_slot||"__catchall"])&&a[0]);c?(w(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(w(d.assignedSlot).T=!0)}
function qc(a,b,c){for(var d=0,e=void 0;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=x(e).assignedNodes;f&&f.length&&qc(a,b,f)}else b.push(c[d])}function rc(a,b){b.__shady_native_dispatchEvent(new Event("slotchange"));b=x(b);b.assignedSlot&&rc(a,b.assignedSlot)}
function oc(a){if(a.i&&a.i.length){for(var b=a.i,c,d=0;d<b.length;d++){var e=b[d];Ib(e);var f=e.__shady_parentNode;Ib(f);f=x(f);f.N=(f.N||0)+1;f=sc(e);a.h[f]?(c=c||{},c[f]=!0,a.h[f].push(e)):a.h[f]=[e];a.g.push(e)}if(c)for(var g in c)a.h[g]=tc(a.h[g]);a.i=[]}}function sc(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.sa=b}
function tc(a){return a.sort(function(b,c){b=lc(b);for(var d=lc(c),e=0;e<b.length;e++){c=b[e];var f=d[e];if(c!==f)return b=Array.from(c.__shady_parentNode.__shady_childNodes),b.indexOf(c)-b.indexOf(f)}})}
function Xb(a,b){if(a.g){oc(a);var c=a.h,d;for(d in c)for(var e=c[d],f=0;f<e.length;f++){var g=e[f];if(ra(b,g)){e.splice(f,1);var h=a.g.indexOf(g);0<=h&&(a.g.splice(h,1),(h=x(g.__shady_parentNode))&&h.N&&h.N--);f--;g=x(g);if(h=g.D)for(var m=0;m<h.length;m++){var l=h[m],q=l.__shady_native_parentNode;q&&q.__shady_native_removeChild(l)}g.D=[];g.assignedNodes=[];h=!0}}return h}}function ja(a){oc(a);return!(!a.g||!a.g.length)}
(function(a){a.__proto__=DocumentFragment.prototype;ic(a,"__shady_");ic(a);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})})(mc.prototype);
if(window.customElements&&z.aa&&!z.preferPerformance){var uc=new Map;kc=function(){var a=[];uc.forEach(function(d,e){a.push([e,d])});uc.clear();for(var b=0;b<a.length;b++){var c=a[b][0];a[b][1]?c.qa():c.ra()}};O&&document.addEventListener("readystatechange",function(){O=!1;kc()},{once:!0});var vc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.qa=function(){O?uc.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.ra=
function(){O?this.isConnected||uc.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},wc=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;wc.call(window.customElements,a,vc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})}function M(a){a=a.__shady_getRootNode();if(D(a))return a};function xc(a){this.node=a}v=xc.prototype;v.addEventListener=function(a,b,c){return this.node.__shady_addEventListener(a,b,c)};v.removeEventListener=function(a,b,c){return this.node.__shady_removeEventListener(a,b,c)};v.appendChild=function(a){return this.node.__shady_appendChild(a)};v.insertBefore=function(a,b){return this.node.__shady_insertBefore(a,b)};v.removeChild=function(a){return this.node.__shady_removeChild(a)};v.replaceChild=function(a,b){return this.node.__shady_replaceChild(a,b)};
v.cloneNode=function(a){return this.node.__shady_cloneNode(a)};v.getRootNode=function(a){return this.node.__shady_getRootNode(a)};v.contains=function(a){return this.node.__shady_contains(a)};v.dispatchEvent=function(a){return this.node.__shady_dispatchEvent(a)};v.setAttribute=function(a,b){this.node.__shady_setAttribute(a,b)};v.getAttribute=function(a){return this.node.__shady_native_getAttribute(a)};v.removeAttribute=function(a){this.node.__shady_removeAttribute(a)};v.attachShadow=function(a){return this.node.__shady_attachShadow(a)};
v.focus=function(){this.node.__shady_native_focus()};v.blur=function(){this.node.__shady_blur()};v.importNode=function(a,b){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_importNode(a,b)};v.getElementById=function(a){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_getElementById(a)};v.querySelector=function(a){return this.node.__shady_querySelector(a)};v.querySelectorAll=function(a,b){return this.node.__shady_querySelectorAll(a,b)};
v.assignedNodes=function(a){if("slot"===this.node.localName)return this.node.__shady_assignedNodes(a)};
ea.Object.defineProperties(xc.prototype,{activeElement:{configurable:!0,enumerable:!0,get:function(){if(D(this.node)||this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_activeElement}},_activeElement:{configurable:!0,enumerable:!0,get:function(){return this.activeElement}},host:{configurable:!0,enumerable:!0,get:function(){if(D(this.node))return this.node.host}},parentNode:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_parentNode}},firstChild:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_firstChild}},lastChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastChild}},nextSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextSibling}},previousSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousSibling}},childNodes:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childNodes}},parentElement:{configurable:!0,enumerable:!0,
get:function(){return this.node.__shady_parentElement}},firstElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_firstElementChild}},lastElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastElementChild}},nextElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextElementSibling}},previousElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousElementSibling}},
children:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_children}},childElementCount:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childElementCount}},shadowRoot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_shadowRoot}},assignedSlot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_assignedSlot}},isConnected:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_isConnected}},innerHTML:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_innerHTML},set:function(a){this.node.__shady_innerHTML=a}},textContent:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_textContent},set:function(a){this.node.__shady_textContent=a}},slot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_slot},set:function(a){this.node.__shady_slot=a}}});
Bb.forEach(function(a){Object.defineProperty(xc.prototype,a,{get:function(){return this.node["__shady_"+a]},set:function(b){this.node["__shady_"+a]=b},configurable:!0})});var yc=new WeakMap;function zc(a){if(D(a)||a instanceof xc)return a;var b=yc.get(a);b||(b=new xc(a),yc.set(a,b));return b};var Ac=G({dispatchEvent:function(a){ya();return this.__shady_native_dispatchEvent(a)},addEventListener:sb,removeEventListener:ub});var Bc=G({get assignedSlot(){var a=this.__shady_parentNode;(a=a&&a.__shady_shadowRoot)&&nc(a);return(a=x(this))&&a.assignedSlot||null}});var Cc=window.document;function Dc(a,b){if("slot"===b)a=a.__shady_parentNode,ia(a)&&N(x(a).root);else if("slot"===a.localName&&"name"===b&&(b=M(a))){if(b.g){oc(b);var c=a.sa,d=sc(a);if(d!==c){c=b.h[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.h[d]||(b.h[d]=[]);c.push(a);1<c.length&&(b.h[d]=tc(c))}}N(b)}}
var Ec=G({get previousElementSibling(){var a=x(this);if(a&&void 0!==a.previousSibling){for(a=this.__shady_previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_previousElementSibling},get nextElementSibling(){var a=x(this);if(a&&void 0!==a.nextSibling){for(a=this.__shady_nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_nextElementSibling},get slot(){return this.getAttribute("slot")},
set slot(a){this.__shady_setAttribute("slot",a)},get shadowRoot(){var a=x(this);return a&&a.ka||null},get className(){return this.getAttribute("class")||""},set className(a){this.__shady_setAttribute("class",a)},setAttribute:function(a,b){if(this.ownerDocument!==Cc)this.__shady_native_setAttribute(a,b);else{var c;(c=L())&&"class"===a?(c.setElementClass(this,b),c=!0):c=!1;c||(this.__shady_native_setAttribute(a,b),Dc(this,a))}},removeAttribute:function(a){this.__shady_native_removeAttribute(a);Dc(this,
a)},attachShadow:function(a){if(!this)throw Error("Must provide a host.");if(!a)throw Error("Not enough arguments.");return new mc(jc,this,a)}});var Fc=G({blur:function(){var a=x(this);(a=(a=a&&a.root)&&a.activeElement)?a.__shady_blur():this.__shady_native_blur()}});Bb.forEach(function(a){Fc[a]={set:function(b){var c=w(this),d=a.substring(2);c.O[a]&&this.removeEventListener(d,c.O[a]);this.__shady_addEventListener(d,b);c.O[a]=b},get:function(){var b=x(this);return b&&b.O[a]},configurable:!0}});var Gc=G({assignedNodes:function(a){if("slot"===this.localName){var b=this.__shady_getRootNode();b&&D(b)&&nc(b);return(b=x(this))?(a&&a.flatten?b.D:b.assignedNodes)||[]:[]}}});var Hc=window.document,Ic=G({importNode:function(a,b){if(a.ownerDocument!==Hc||"template"===a.localName)return this.__shady_native_importNode(a,b);var c=this.__shady_native_importNode(a,!1);if(b){a=a.__shady_childNodes;b=0;for(var d;b<a.length;b++)d=this.__shady_importNode(a[b],!0),c.__shady_appendChild(d)}return c}});var Jc=G({addEventListener:sb.bind(window),removeEventListener:ub.bind(window)});var Kc={};Object.getOwnPropertyDescriptor(HTMLElement.prototype,"parentElement")&&(Kc.parentElement=Yb.parentElement);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"contains")&&(Kc.contains=Yb.contains);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"children")&&(Kc.children=ac.children);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&(Kc.innerHTML=gc.innerHTML);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"className")&&(Kc.className=Ec.className);
var Lc={EventTarget:[Ac],Node:[Yb,window.EventTarget?null:Ac],Text:[Bc],Element:[Ec,ac,Bc,!z.o||"innerHTML"in Element.prototype?gc:null,window.HTMLSlotElement?null:Gc],HTMLElement:[Fc,Kc],HTMLSlotElement:[Gc],DocumentFragment:[cc,dc],Document:[Ic,cc,dc,ec],Window:[Jc]},Mc=z.o?null:["innerHTML","textContent"];function Nc(a){var b=a?null:Mc,c={},d;for(d in Lc)c.M=window[d]&&window[d].prototype,Lc[d].forEach(function(e){return function(f){return e.M&&f&&F(e.M,f,a,b)}}(c)),c={M:c.M}};if(z.aa){var ShadyDOM={inUse:z.aa,patch:function(a){db(a);cb(a);return a},isShadyRoot:D,enqueue:xa,flush:ya,flushInitial:function(a){!a.Z&&a.C&&nc(a)},settings:z,filterMutations:Da,observeChildren:Ba,unobserveChildren:Ca,deferConnectionCallbacks:z.deferConnectionCallbacks,preferPerformance:z.preferPerformance,handlesDynamicScoping:!0,wrap:z.I?zc:function(a){return a},Wrapper:xc,composedPath:kb,noPatch:z.I,nativeMethods:Ma,nativeTree:Na};window.ShadyDOM=ShadyDOM;Ua();Nc("__shady_");Object.defineProperty(document,
"_activeElement",ec.activeElement);F(Window.prototype,Jc,"__shady_");z.I||(Nc(),Ab());vb();window.Event=xb;window.CustomEvent=yb;window.MouseEvent=zb;window.ShadowRoot=mc};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Oc(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Pc(a){var b=a=a.replace(Qc,"").replace(Rc,""),c=new Oc;c.start=0;c.end=b.length;for(var d=c,e=0,f=b.length;e<f;e++)if("{"===b[e]){d.rules||(d.rules=[]);var g=d,h=g.rules[g.rules.length-1]||null;d=new Oc;d.start=e+1;d.parent=g;d.previous=h;g.rules.push(d)}else"}"===b[e]&&(d.end=e+1,d=d.parent||c);return Sc(c,a)}
function Sc(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=Tc(c),c=c.replace(Uc," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=Vc:c.match(Wc)&&(a.type=Xc,a.keyframesName=a.selector.split(Uc).pop()):a.type=0===c.indexOf("--")?Yc:Zc);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)Sc(f,
b);return a}function Tc(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(b,c){b=c;for(c=6-b.length;c--;)b="0"+b;return"\\"+b})}
function $c(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h=void 0;f<g&&(h=e[f]);f++)d=$c(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(ad,"").replace(bd,""),b=b.replace(cd,"").replace(dd,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var Zc=1,Xc=7,Vc=4,Yc=1E3,Qc=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,Rc=/@import[^;]*;/gim,ad=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,bd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,cd=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,dd=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Wc=/^@[^\s]*keyframes/,Uc=/\s+/g;var Q=!(window.ShadyDOM&&window.ShadyDOM.inUse),ed;function fd(a){ed=a&&a.shimcssproperties?!1:Q||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var gd;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&(gd=window.ShadyCSS.cssBuild);var hd=!(!window.ShadyCSS||!window.ShadyCSS.disableRuntime);
window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?ed=window.ShadyCSS.nativeCss:window.ShadyCSS?(fd(window.ShadyCSS),window.ShadyCSS=void 0):fd(window.WebComponents&&window.WebComponents.flags);var R=ed;var id=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,jd=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,kd=/(--[\w-]+)\s*([:,;)]|$)/gi,ld=/(animation\s*:)|(animation-name\s*:)/,md=/@media\s(.*)/,nd=/\{[^}]*\}/g;var od=new Set;function pd(a,b){if(!a)return"";"string"===typeof a&&(a=Pc(a));b&&qd(a,b);return $c(a,R)}function rd(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Pc(a.textContent));return a.__cssRules||null}function sd(a){return!!a.parent&&a.parent.type===Xc}function qd(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===Vc){var g=a.selector.match(md);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===Zc?b(a):c&&f===Xc?c(a):f===Yc&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++)qd(g,b,c,d)}}
function td(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;ud(e,c,d);return e}var S=null;function vd(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(S?S.nextSibling:null)||b.firstChild);return S=a}function ud(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);S?a.compareDocumentPosition(S)===Node.DOCUMENT_POSITION_PRECEDING&&(S=a):S=a}
function wd(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function xd(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=wd(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=xd(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function yd(a,b){Q?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
var zd=window.ShadyDOM&&window.ShadyDOM.wrap||function(a){return a};function T(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,L:c}}function Ad(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=wd(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function Bd(a){if(void 0!==gd)return gd;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function Cd(a){a=void 0===a?"":a;return""!==a&&R?Q?"shadow"===a:"shady"===a:!1};function Dd(){}function Ed(a,b){Fd(U,a,function(c){V(c,b||"")})}function Fd(a,b,c){b.nodeType===Node.ELEMENT_NODE&&c(b);if(b="template"===b.localName?(b.content||b._content||b).childNodes:b.children||b.childNodes)for(var d=0;d<b.length;d++)Fd(a,b[d],c)}
function V(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),yd(a,b)):yd(a,(d?d+" ":"")+"style-scope "+b)}}function Gd(a,b,c){Fd(U,a,function(d){V(d,b,!0);V(d,c)})}function Hd(a,b){Fd(U,a,function(c){V(c,b||"",!0)})}
function Id(a,b,c,d,e){var f=U;e=void 0===e?"":e;""===e&&(Q||"shady"===(void 0===d?"":d)?e=pd(b,c):(a=T(a),e=Jd(f,b,a.is,a.L,c)+"\n\n"));return e.trim()}function Jd(a,b,c,d,e){var f=Nd(c,d);c=c?"."+c:"";return pd(b,function(g){g.i||(g.selector=g.m=Od(a,g,a.h,c,f),g.i=!0);e&&e(g,c,f)})}function Nd(a,b){return b?"[is="+a+"]":a}
function Od(a,b,c,d,e){var f=Ad(b.selector);if(!sd(b)){b=0;for(var g=f.length,h=void 0;b<g&&(h=f[b]);b++)f[b]=c.call(a,h,d,e)}return f.filter(function(m){return!!m}).join(",")}function Pd(a){return a.replace(Qd,function(b,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
function Rd(a){for(var b=[],c;c=a.match(Sd);){var d=c.index,e=wd(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{ca:a,matches:b}}function Td(a,b){var c=a.split("\ue000");return b.reduce(function(d,e,f){return d+e+c[f+1]},c[0])}
Dd.prototype.h=function(a,b,c){var d=!1;a=a.trim();var e=Qd.test(a);e&&(a=a.replace(Qd,function(h,m,l){return":"+m+"("+l.replace(/\s/g,"")+")"}),a=Pd(a));var f=Sd.test(a);if(f){var g=Rd(a);a=g.ca;g=g.matches}a=a.replace(Ud,":host $1");a=a.replace(Vd,function(h,m,l){d||(h=Wd(l,m,b,c),d=d||h.stop,m=h.Aa,l=h.value);return m+l});f&&(a=Td(a,g));e&&(a=Pd(a));return a};
function Wd(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=Xd(a,d):0!==e&&(a=c?Yd(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(Zd,function(g,h){return" > "+h}))}a=a.replace($d,function(g,h,m){return'[dir="'+m+'"] '+h+", "+h+'[dir="'+m+'"]'});return{value:a,Aa:b,stop:f}}
function Yd(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")}function Xd(a,b){var c=a.match(ae);return(c=c&&c[2].trim()||"")?c[0].match(be)?a.replace(ae,function(d,e,f){return b+f}):c.split(be)[0]===b?c:"should_not_match":a.replace(":host",b)}function ce(a){":root"===a.selector&&(a.selector="html")}
Dd.prototype.i=function(a){return a.match(":host")?"":a.match("::slotted")?this.h(a,":not(.style-scope)"):Yd(a.trim(),":not(.style-scope)")};ea.Object.defineProperties(Dd.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Qd=/:(nth[-\w]+)\(([^)]+)\)/,Vd=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,be=/[[.:#*]/,Ud=/^(::slotted)/,ae=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Zd=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,$d=/(.*):dir\((?:(ltr|rtl))\)/,Sd=/:(?:matches|any|-(?:webkit|moz)-any)/,U=new Dd;function de(a,b,c,d,e){this.B=a||null;this.h=b||null;this.ba=c||[];this.s=null;this.cssBuild=e||"";this.L=d||"";this.g=this.u=this.A=null}function W(a){return a?a.__styleInfo:null}function ee(a,b){return a.__styleInfo=b}de.prototype.i=function(){return this.B};de.prototype._getStyleRules=de.prototype.i;function fe(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var ge=navigator.userAgent.match("Trident");function he(){}function ie(a){var b={},c=[],d=0;qd(a,function(f){je(f);f.index=d++;f=f.l.cssText;for(var g;g=kd.exec(f);){var h=g[1];":"!==g[2]&&(b[h]=!0)}},function(f){c.push(f)});a.h=c;a=[];for(var e in b)a.push(e);return a}
function je(a){if(!a.l){var b={},c={};ke(a,c)&&(b.v=c,a.rules=null);b.cssText=a.parsedCssText.replace(nd,"").replace(id,"");a.l=b}}function ke(a,b){var c=a.l;if(c){if(c.v)return Object.assign(b,c.v),!0}else{c=a.parsedCssText;for(var d;a=id.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function le(a,b,c){b&&(b=0<=b.indexOf(";")?me(a,b,c):xd(b,function(d,e,f,g){if(!e)return d+g;(e=le(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=le(a,c[f]||f,c)||f;return d+(e||"")+g}));return b&&b.trim()||""}
function me(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){jd.lastIndex=0;if(f=jd.exec(e))e=le(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=le(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function ne(a,b){var c={},d=[];qd(a,function(e){e.l||je(e);var f=e.m||e.parsedSelector;b&&e.l.v&&f&&fe.call(b,f)&&(ke(e,c),e=e.index,f=parseInt(e/32,10),d[f]=(d[f]||0)|1<<e%32)},null,!0);return{v:c,key:d}}
function oe(a,b,c,d){b.l||je(b);if(b.l.v){var e=T(a);a=e.is;e=e.L;e=a?Nd(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));if(g||h)c=e,h&&(b.m||(b.m=Od(U,b,U.h,a?"."+a:"",e)),c=b.m||e),d({ca:c,Ga:h,Sa:g})}}function pe(a,b,c){var d={},e={};qd(b,function(f){oe(a,f,c,function(g){fe.call(a._element||a,g.ca)&&(g.Ga?ke(f,d):ke(f,e))})},null,!0);return{Ia:e,Fa:d}}
function qe(a,b,c,d){var e=T(b),f=Nd(e.is,e.L),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),h=W(b);e=h.B;h=h.cssBuild;var m=re(e,d);return Id(b,e,function(l){var q="";l.l||je(l);l.l.cssText&&(q=me(a,l.l.cssText,c));l.cssText=q;if(!Q&&!sd(l)&&l.cssText){var t=q=l.cssText;null==l.ha&&(l.ha=ld.test(q));if(l.ha)if(null==l.U){l.U=[];for(var B in m)t=m[B],t=t(q),q!==t&&(q=t,l.U.push(B))}else{for(B=0;B<l.U.length;++B)t=m[l.U[B]],q=t(q);t=q}l.cssText=t;l.m=l.m||l.selector;
q="."+d;B=Ad(l.m);t=0;for(var P=B.length,X=void 0;t<P&&(X=B[t]);t++)B[t]=X.match(g)?X.replace(f,q):q+" "+X;l.selector=B.join(",")}},h)}function re(a,b){a=a.h;var c={};if(!Q&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,g=b;f.j=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.g=f.keyframesName+"-"+g;f.m=f.m||f.selector;f.selector=f.m.replace(f.keyframesName,f.g);c[e.keyframesName]=se(e)}return c}function se(a){return function(b){return b.replace(a.j,a.g)}}
function te(a,b){var c=ue,d=rd(a);a.textContent=pd(d,function(e){var f=e.cssText=e.parsedCssText;e.l&&e.l.cssText&&(f=f.replace(ad,"").replace(bd,""),e.cssText=me(c,f,b))})}ea.Object.defineProperties(he.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var ue=new he;var ve={},we=window.customElements;if(we&&!Q&&!hd){var xe=we.define;we.define=function(a,b,c){ve[a]||(ve[a]=vd(a));xe.call(we,a,b,c)}};function ye(){this.cache={}}ye.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({v:b,styleElement:c,u:d});100<e.length&&e.shift();this.cache[a]=e};function ze(){}var Ae=new RegExp(U.g+"\\s*([^\\s]*)");function Be(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(Ae))?a[1]:""}function Ce(a){var b=zd(a).getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?T(a).is:""}
function De(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g=Be(e);if(g&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===Bd(e)))Hd(e,g);else if(f instanceof ShadowRoot)for(f=Ce(e),f!==g&&Gd(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+U.g+")"),g=0;g<e.length;g++){f=e[g];
var h=Ce(f);h&&V(f,h)}}}}}
if(!(Q||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var Ee=new MutationObserver(De),Fe=function(a){Ee.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Fe(document);else{var Ge=function(){Fe(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Ge):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Ge();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else Ge()})}ze=function(){De(Ee.takeRecords())}};var He={};var Ie=Promise.resolve();function Je(a){if(a=He[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Ke(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Le(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,Ie.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var Me={},Ne=new ye;function Y(){this.H={};this.i=document.documentElement;var a=new Oc;a.rules=[];this.j=ee(this.i,new de(a));this.F=!1;this.h=this.g=null}v=Y.prototype;v.flush=function(){ze()};v.Da=function(a){return rd(a)};v.Na=function(a){return pd(a)};v.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
v.prepareTemplateStyles=function(a,b,c){if(!a._prepared&&!hd){Q||ve[b]||(ve[b]=vd(b));a._prepared=!0;a.name=b;a.extends=c;He[b]=a;var d=Bd(a),e=Cd(d);c={is:b,extends:c};for(var f=[],g=a.content.querySelectorAll("style"),h=0;h<g.length;h++){var m=g[h];if(m.hasAttribute("shady-unscoped")){if(!Q){var l=m.textContent;od.has(l)||(od.add(l),l=m.cloneNode(!0),document.head.appendChild(l));m.parentNode.removeChild(m)}}else f.push(m.textContent),m.parentNode.removeChild(m)}f=f.join("").trim()+(Me[b]||"");
Oe(this);if(!e){if(g=!d)g=jd.test(f)||id.test(f),jd.lastIndex=0,id.lastIndex=0;h=Pc(f);g&&R&&this.g&&this.g.transformRules(h,b);a._styleAst=h}g=[];R||(g=ie(a._styleAst));if(!g.length||R)h=Q?a.content:null,b=ve[b]||null,d=Id(c,a._styleAst,null,d,e?f:""),d=d.length?td(d,c.is,h,b):null,a._style=d;a.g=g}};v.Ha=function(a,b){Me[b]=a.join(" ")};v.prepareTemplateDom=function(a,b){if(!hd){var c=Bd(a);Q||"shady"===c||a._domPrepared||(a._domPrepared=!0,Ed(a.content,b))}};
function Pe(a){var b=T(a),c=b.is;b=b.L;var d=ve[c]||null,e=He[c];if(e){c=e._styleAst;var f=e.g;e=Bd(e);b=new de(c,d,f,b,e);ee(a,b);return b}}function Qe(a){!a.h&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.h=window.ShadyCSS.CustomStyleInterface,a.h.transformCallback=function(b){a.ma(b)},a.h.validateCallback=function(){requestAnimationFrame(function(){(a.h.enqueued||a.F)&&a.flushCustomStyles()})})}
function Oe(a){!a.g&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.g=window.ShadyCSS.ApplyShim,a.g.invalidCallback=Je);Qe(a)}
v.flushCustomStyles=function(){if(!hd&&(Oe(this),this.h)){var a=this.h.processStyles();if(this.h.enqueued&&!Cd(this.j.cssBuild)){if(R){if(!this.j.cssBuild)for(var b=0;b<a.length;b++){var c=this.h.getStyleForCustomStyle(a[b]);if(c&&R&&this.g){var d=rd(c);Oe(this);this.g.transformRules(d);c.textContent=pd(d)}}}else{Re(this,this.i,this.j);for(b=0;b<a.length;b++)(c=this.h.getStyleForCustomStyle(a[b]))&&te(c,this.j.A);this.F&&this.styleDocument()}this.h.enqueued=!1}}};
v.styleElement=function(a,b){if(hd){if(b){W(a)||ee(a,new de(null));var c=W(a);c.s=c.s||{};Object.assign(c.s,b);Se(this,a,c)}}else if(c=W(a)||Pe(a))if(a!==this.i&&(this.F=!0),b&&(c.s=c.s||{},Object.assign(c.s,b)),R)Se(this,a,c);else if(this.flush(),Re(this,a,c),c.ba&&c.ba.length){b=T(a).is;var d;a:{if(d=Ne.cache[b])for(var e=d.length-1;0<=e;e--){var f=d[e];b:{var g=c.ba;for(var h=0;h<g.length;h++){var m=g[h];if(f.v[m]!==c.A[m]){g=!1;break b}}g=!0}if(g){d=f;break a}}d=void 0}g=d?d.styleElement:null;
e=c.u;(f=d&&d.u)||(f=this.H[b]=(this.H[b]||0)+1,f=b+"-"+f);c.u=f;f=c.u;h=ue;h=g?g.textContent||"":qe(h,a,c.A,f);m=W(a);var l=m.g;l&&!Q&&l!==g&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));Q?m.g?(m.g.textContent=h,g=m.g):h&&(g=td(h,f,a.shadowRoot,m.h)):g?g.parentNode||(ge&&-1<h.indexOf("@media")&&(g.textContent=h),ud(g,null,m.h)):h&&(g=td(h,f,null,m.h));g&&(g._useCount=g._useCount||0,m.g!=g&&g._useCount++,m.g=g);f=g;Q||(g=c.u,m=h=a.getAttribute("class")||"",e&&(m=h.replace(new RegExp("\\s*x-scope\\s*"+
e+"\\s*","g")," ")),m+=(m?" ":"")+"x-scope "+g,h!==m&&yd(a,m));d||Ne.store(b,c.A,f,c.u)}};
function Se(a,b,c){var d=T(b).is;if(c.s){var e=c.s,f;for(f in e)null===f?b.style.removeProperty(f):b.style.setProperty(f,e[f])}e=He[d];if(!(!e&&b!==a.i||e&&""!==Bd(e))&&e&&e._style&&!Ke(e)){if(Ke(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)Oe(a),a.g&&a.g.transformRules(e._styleAst,d),e._style.textContent=Id(b,c.B),Le(e);Q&&(a=b.shadowRoot)&&(a=a.querySelector("style"))&&(a.textContent=Id(b,c.B));c.B=e._styleAst}}
function Te(a,b){return(b=zd(b).getRootNode().host)?W(b)||Pe(b)?b:Te(a,b):a.i}function Re(a,b,c){var d=Te(a,b),e=W(d),f=e.A;d===a.i||f||(Re(a,d,e),f=e.A);a=Object.create(f||null);d=pe(b,c.B,c.cssBuild);b=ne(e.B,b).v;Object.assign(a,d.Fa,b,d.Ia);b=c.s;for(var g in b)if((e=b[g])||0===e)a[g]=e;g=ue;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=le(g,a[d],a);c.A=a}v.styleDocument=function(a){this.styleSubtree(this.i,a)};
v.styleSubtree=function(a,b){var c=zd(a),d=c.shadowRoot;(d||a===this.i)&&this.styleElement(a,b);if(a=d&&(d.children||d.childNodes))for(c=0;c<a.length;c++)this.styleSubtree(a[c]);else if(c=c.children||c.childNodes)for(a=0;a<c.length;a++)this.styleSubtree(c[a])};
v.ma=function(a){var b=this,c=Bd(a);c!==this.j.cssBuild&&(this.j.cssBuild=c);if(!Cd(c)){var d=rd(a);qd(d,function(e){if(Q)ce(e);else{var f=U;e.selector=e.parsedSelector;ce(e);e.selector=e.m=Od(f,e,f.i,void 0,void 0)}R&&""===c&&(Oe(b),b.g&&b.g.transformRule(e))});R?a.textContent=pd(d):this.j.B.rules.push(d)}};v.getComputedStyleValue=function(a,b){var c;R||(c=(W(a)||W(Te(this,a))).A[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};
v.Ma=function(a,b){var c=zd(a).getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===U.g){c=d[e+1];break}}}c&&b.push(U.g,c);R||(c=W(a))&&c.u&&b.push(ue.g,c.u);yd(a,b.join(" "))};v.ya=function(a){return W(a)};v.La=function(a,b){V(a,b)};v.Pa=function(a,b){V(a,b,!0)};v.Ka=function(a){return Ce(a)};v.Ba=function(a){return Be(a)};Y.prototype.flush=Y.prototype.flush;Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;
Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.Ma;Y.prototype._styleInfoForNode=Y.prototype.ya;Y.prototype.transformCustomStyleForDocument=Y.prototype.ma;Y.prototype.getStyleAst=Y.prototype.Da;Y.prototype.styleAstToString=Y.prototype.Na;Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;
Y.prototype.scopeNode=Y.prototype.La;Y.prototype.unscopeNode=Y.prototype.Pa;Y.prototype.scopeForNode=Y.prototype.Ka;Y.prototype.currentScopeForNode=Y.prototype.Ba;Y.prototype.prepareAdoptedCssText=Y.prototype.Ha;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return Q}},nativeCss:{get:function(){return R}}});var Z=new Y,Ue,Ve;window.ShadyCSS&&(Ue=window.ShadyCSS.ApplyShim,Ve=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:R,nativeShadow:Q,cssBuild:gd,disableRuntime:hd};Ue&&(window.ShadyCSS.ApplyShim=Ue);Ve&&(window.ShadyCSS.CustomStyleInterface=Ve);/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var We=window.customElements,Xe=window.HTMLImports,Ye=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(We&&We.polyfillWrapFlushCallback){var Ze,$e=function(){if(Ze){Ye.za&&Ye.za(window.document);var a=Ze;Ze=null;a();return!0}},af=Xe.whenReady;We.polyfillWrapFlushCallback(function(a){Ze=a;af($e)});Xe.whenReady=function(a){af(function(){$e()?Xe.whenReady(a):a()})}}
Xe.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var bf=document.createElement("style");bf.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var cf=document.querySelector("head");cf.insertBefore(bf,cf.firstChild);/*

Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
}).call(this);

//# sourceMappingURL=webcomponents-hi-sd.js.map
