/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var n;function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ca(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:ba(a)}}function da(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}
function ea(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var fa=ea(this);
function ha(){this.fa=this.root=null;this.R=!1;this.D=this.N=this.W=this.assignedSlot=this.assignedNodes=this.F=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.H=void 0;this.aa=this.ba=!1;this.M={}}ha.prototype.toJSON=function(){return{}};function p(a){a.__shady||(a.__shady=new ha);return a.__shady}function r(a){return a&&a.__shady};var t=window.ShadyDOM||{};t.sa=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ia=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");t.m=!!(ia&&ia.configurable&&ia.get);t.X=t.force||!t.sa;t.G=t.noPatch||!1;t.ea=t.preferPerformance;function u(a){return(a=r(a))&&void 0!==a.firstChild}function v(a){return"ShadyRoot"===a.la}function ja(a){return(a=(a=r(a))&&a.root)&&ka(a)}
var w=Element.prototype,la=w.matches||w.matchesSelector||w.mozMatchesSelector||w.msMatchesSelector||w.oMatchesSelector||w.webkitMatchesSelector,ma=document.createTextNode(""),na=0,oa=[];(new MutationObserver(function(){for(;oa.length;)try{oa.shift()()}catch(a){throw ma.textContent=na++,a;}})).observe(ma,{characterData:!0});function pa(a){oa.push(a);ma.textContent=na++}var qa=!!document.contains;function ra(a,b){for(;b;){if(b==a)return!0;b=b.__shady_parentNode}return!1}
function sa(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(e){return a[e]};a.namedItem=function(e){if("length"!==e&&isNaN(e)&&a[e])return a[e];for(var f=ca(a),g=f.next();!g.done;g=f.next())if(g=g.value,(g.getAttribute("id")||g.getAttribute("name"))==e)return g;return null};return a}
function x(a,b,c,d){c=void 0===c?"":c;for(var e in b){var f=b[e];if(!(d&&0<=d.indexOf(e))){f.configurable=!0;var g=c+e;if(f.value)a[g]=f.value;else try{Object.defineProperty(a,g,f)}catch(h){}}}}function z(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=Object.getOwnPropertyDescriptor(a,c)});return b};var A=[],ta;function ua(a){ta||(ta=!0,pa(va));A.push(a)}function va(){ta=!1;for(var a=!!A.length;A.length;)A.shift()();return a}va.list=A;function wa(){this.g=!1;this.addedNodes=[];this.removedNodes=[];this.P=new Set}function xa(a){a.g||(a.g=!0,pa(function(){a.flush()}))}wa.prototype.flush=function(){if(this.g){this.g=!1;var a=this.takeRecords();a.length&&this.P.forEach(function(b){b(a)})}};wa.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function ya(a,b){var c=p(a);c.F||(c.F=new wa);c.F.P.add(b);var d=c.F;return{ka:b,na:d,ma:a,takeRecords:function(){return d.takeRecords()}}}function za(a){var b=a&&a.na;b&&(b.P.delete(a.ka),b.P.size||(p(a.ma).F=null))}
function Aa(a,b){var c=b.getRootNode();return a.map(function(d){var e=c===d.target.getRootNode();if(e&&d.addedNodes){if(e=Array.from(d.addedNodes).filter(function(f){return c===f.getRootNode()}),e.length)return d=Object.create(d),Object.defineProperty(d,"addedNodes",{value:e,configurable:!0}),d}else if(e)return d}).filter(function(d){return d})};var Ba=/[&\u00A0"]/g,Ca=/[&\u00A0<>]/g;function Da(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Fa(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Ga=Fa("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Ha=Fa("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function Ia(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g=void 0;e<f&&(g=d[e]);e++){a:{var h=g;var l=a,k=b;switch(h.nodeType){case Node.ELEMENT_NODE:l=h.localName;for(var m="<"+l,q=h.attributes,y=0,aa;aa=q[y];y++)m+=" "+aa.name+'="'+aa.value.replace(Ba,Da)+'"';m+=">";h=Ga[l]?m:m+Ia(h,k)+"</"+l+">";break a;case Node.TEXT_NODE:h=h.data;h=l&&Ha[l.localName]?h:h.replace(Ca,Da);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var Ja=t.m,Ka={querySelector:function(a){return this.__shady_native_querySelector(a)},querySelectorAll:function(a){return this.__shady_native_querySelectorAll(a)}},La={};function Ma(a){La[a]=function(b){return b["__shady_native_"+a]}}function Na(a,b){x(a,b,"__shady_native_");for(var c in b)Ma(c)}function B(a,b){b=void 0===b?[]:b;for(var c=0;c<b.length;c++){var d=b[c],e=Object.getOwnPropertyDescriptor(a,d);e&&(Object.defineProperty(a,"__shady_native_"+d,e),e.value?Ka[d]||(Ka[d]=e.value):Ma(d))}}
var C=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),D=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),Oa=document.implementation.createHTMLDocument("inert");function Pa(a){for(var b;b=a.__shady_native_firstChild;)a.__shady_native_removeChild(b)}var Qa=["firstElementChild","lastElementChild","children","childElementCount"],Ra=["querySelector","querySelectorAll"];
function Sa(){var a=["dispatchEvent","addEventListener","removeEventListener"];window.EventTarget?B(window.EventTarget.prototype,a):(B(Node.prototype,a),B(Window.prototype,a));Ja?B(Node.prototype,"parentNode firstChild lastChild previousSibling nextSibling childNodes parentElement textContent".split(" ")):Na(Node.prototype,{parentNode:{get:function(){C.currentNode=this;return C.parentNode()}},firstChild:{get:function(){C.currentNode=this;return C.firstChild()}},lastChild:{get:function(){C.currentNode=
this;return C.lastChild()}},previousSibling:{get:function(){C.currentNode=this;return C.previousSibling()}},nextSibling:{get:function(){C.currentNode=this;return C.nextSibling()}},childNodes:{get:function(){var b=[];C.currentNode=this;for(var c=C.firstChild();c;)b.push(c),c=C.nextSibling();return b}},parentElement:{get:function(){D.currentNode=this;return D.parentNode()}},textContent:{get:function(){switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(var b=document.createTreeWalker(this,
NodeFilter.SHOW_TEXT,null,!1),c="",d;d=b.nextNode();)c+=d.nodeValue;return c;default:return this.nodeValue}},set:function(b){if("undefined"===typeof b||null===b)b="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:Pa(this);(0<b.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_native_insertBefore(document.createTextNode(b),void 0);break;default:this.nodeValue=b}}}});B(Node.prototype,"appendChild insertBefore removeChild replaceChild cloneNode contains".split(" "));
a={firstElementChild:{get:function(){D.currentNode=this;return D.firstChild()}},lastElementChild:{get:function(){D.currentNode=this;return D.lastChild()}},children:{get:function(){var b=[];D.currentNode=this;for(var c=D.firstChild();c;)b.push(c),c=D.nextSibling();return sa(b)}},childElementCount:{get:function(){return this.children?this.children.length:0}}};Ja?(B(Element.prototype,Qa),B(Element.prototype,["previousElementSibling","nextElementSibling","innerHTML"]),Object.getOwnPropertyDescriptor(HTMLElement.prototype,
"children")&&B(HTMLElement.prototype,["children"]),Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&B(HTMLElement.prototype,["innerHTML"])):(Na(Element.prototype,a),Na(Element.prototype,{previousElementSibling:{get:function(){D.currentNode=this;return D.previousSibling()}},nextElementSibling:{get:function(){D.currentNode=this;return D.nextSibling()}},innerHTML:{get:function(){return Ia(this,function(b){return b.__shady_native_childNodes})},set:function(b){var c="template"===this.localName?
this.content:this;Pa(c);var d=this.localName||"div";d=this.namespaceURI&&this.namespaceURI!==Oa.namespaceURI?Oa.createElementNS(this.namespaceURI,d):Oa.createElement(d);d.innerHTML=b;for(b="template"===this.localName?d.content:d;d=b.__shady_native_firstChild;)c.__shady_native_insertBefore(d,void 0)}}}));B(Element.prototype,"setAttribute getAttribute hasAttribute removeAttribute focus blur".split(" "));B(Element.prototype,Ra);B(HTMLElement.prototype,["focus","blur","contains"]);Ja&&B(HTMLElement.prototype,
["parentElement","children","innerHTML"]);window.HTMLTemplateElement&&B(window.HTMLTemplateElement.prototype,["innerHTML"]);Ja?B(DocumentFragment.prototype,Qa):Na(DocumentFragment.prototype,a);B(DocumentFragment.prototype,Ra);Ja?(B(Document.prototype,Qa),B(Document.prototype,["activeElement"])):Na(Document.prototype,a);B(Document.prototype,["importNode","getElementById"]);B(Document.prototype,Ra)};var Ta=z({get childNodes(){return this.__shady_childNodes},get firstChild(){return this.__shady_firstChild},get lastChild(){return this.__shady_lastChild},get textContent(){return this.__shady_textContent},set textContent(a){this.__shady_textContent=a},get childElementCount(){return this.__shady_childElementCount},get children(){return this.__shady_children},get firstElementChild(){return this.__shady_firstElementChild},get lastElementChild(){return this.__shady_lastElementChild},get innerHTML(){return this.__shady_innerHTML},
set innerHTML(a){return this.__shady_innerHTML=a},get shadowRoot(){return this.__shady_shadowRoot}}),Ua=z({get parentElement(){return this.__shady_parentElement},get parentNode(){return this.__shady_parentNode},get nextSibling(){return this.__shady_nextSibling},get previousSibling(){return this.__shady_previousSibling},get nextElementSibling(){return this.__shady_nextElementSibling},get previousElementSibling(){return this.__shady_previousElementSibling},get className(){return this.__shady_className},
set className(a){return this.__shady_className=a}}),Va;for(Va in Ta)Ta[Va].enumerable=!1;for(var Wa in Ua)Ua[Wa].enumerable=!1;var Xa=t.m||t.G,Ya=Xa?function(){}:function(a){var b=p(a);b.ba||(b.ba=!0,x(a,Ua))},Za=Xa?function(){}:function(a){var b=p(a);b.aa||(b.aa=!0,x(a,Ta))};var $a="__eventWrappers"+Date.now(),ab=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),bb={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},cb={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function db(a){return a instanceof Node?a.__shady_getRootNode():a}function eb(a,b){var c=[],d=a;for(a=db(a);d;)c.push(d),d=d.__shady_assignedSlot?d.__shady_assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.__shady_parentNode;c[c.length-1]===document&&c.push(window);return c}function fb(a){a.__composedPath||(a.__composedPath=eb(a.target,!0));return a.__composedPath}
function gb(a,b){if(!v)return a;a=eb(a,!0);for(var c=0,d,e=void 0,f,g=void 0;c<b.length;c++)if(d=b[c],f=db(d),f!==e&&(g=a.indexOf(f),e=f),!v(f)||-1<g)return d}function hb(a){function b(c,d){c=new a(c,d);c.__composed=d&&!!d.composed;return c}b.__proto__=a;b.prototype=a.prototype;return b}var ib={focus:!0,blur:!0};function jb(a){return a.__target!==a.target||a.__relatedTarget!==a.relatedTarget}
function kb(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!jb(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.__immediatePropagationStopped);d++);}
function lb(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];kb(a,d,"capture");if(a.T)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=r(d);f=f&&f.root;if(0===c||f&&f===e)if(kb(a,d,"bubble"),d!==window&&(e=d.__shady_getRootNode()),a.T)break}}
function mb(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],l=h.type,k=h.capture,m=h.once,q=h.passive;if(b===h.node&&c===l&&d===k&&e===m&&f===q)return g}return-1}
function nb(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){if(cb[a])return this.__shady_native_addEventListener(a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.U||this,l=b[$a];if(l){if(-1<mb(l,h,a,e,f,g))return}else b[$a]=[];l=function(k){f&&this.__shady_removeEventListener(a,b,c);k.__target||ob(k);if(h!==this){var m=Object.getOwnPropertyDescriptor(k,"currentTarget");
Object.defineProperty(k,"currentTarget",{get:function(){return h},configurable:!0})}k.__previousCurrentTarget=k.currentTarget;if(!v(h)||-1!=k.composedPath().indexOf(h))if(k.composed||-1<k.composedPath().indexOf(h))if(jb(k)&&k.target===k.relatedTarget)k.eventPhase===Event.BUBBLING_PHASE&&k.stopImmediatePropagation();else if(k.eventPhase===Event.CAPTURING_PHASE||k.bubbles||k.target===h||h instanceof Window){var q="function"===d?b.call(h,k):b.handleEvent&&b.handleEvent(k);h!==this&&(m?(Object.defineProperty(k,
"currentTarget",m),m=null):delete k.currentTarget);return q}};b[$a].push({node:h,type:a,capture:e,once:f,passive:g,Ca:l});ib[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][e?"capture":"bubble"].push(l)):this.__shady_native_addEventListener(a,l,c)}}}
function pb(a,b,c){if(b){if(cb[a])return this.__shady_native_removeEventListener(a,b,c);if(c&&"object"===typeof c){var d=!!c.capture;var e=!!c.once;var f=!!c.passive}else d=!!c,f=e=!1;var g=c&&c.U||this,h=void 0;var l=null;try{l=b[$a]}catch(k){}l&&(e=mb(l,g,a,d,e,f),-1<e&&(h=l.splice(e,1)[0].Ca,l.length||(b[$a]=void 0)));this.__shady_native_removeEventListener(a,h||b,c);h&&ib[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][d?"capture":"bubble"],h=a.indexOf(h),-1<h&&a.splice(h,1))}}
function qb(){for(var a in ib)window.__shady_native_addEventListener(a,function(b){b.__target||(ob(b),lb(b))},!0)}
var rb=z({get composed(){void 0===this.__composed&&(ab?this.__composed="focusin"===this.type||"focusout"===this.type||ab(this):!1!==this.isTrusted&&(this.__composed=bb[this.type]));return this.__composed||!1},composedPath:function(){this.__composedPath||(this.__composedPath=eb(this.__target,this.composed));return this.__composedPath},get target(){return gb(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.__relatedTarget)return null;this.__relatedTargetComposedPath||
(this.__relatedTargetComposedPath=eb(this.__relatedTarget,!0));return gb(this.currentTarget||this.__previousCurrentTarget,this.__relatedTargetComposedPath)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.T=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.T=this.__immediatePropagationStopped=!0}});
function ob(a){a.__target=a.target;a.__relatedTarget=a.relatedTarget;if(t.m){var b=Object.getPrototypeOf(a);if(!Object.hasOwnProperty(b,"__shady_patchedProto")){var c=Object.create(b);c.__shady_sourceProto=b;x(c,rb);b.__shady_patchedProto=c}a.__proto__=b.__shady_patchedProto}else x(a,rb)}var sb=hb(Event),tb=hb(CustomEvent),ub=hb(MouseEvent);
function vb(){if(!ab&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var b=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.__shady_dispatchEvent(b)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}}var wb=Object.getOwnPropertyNames(Document.prototype).filter(function(a){return"on"===a.substring(0,2)});function xb(a,b){return{index:a,I:[],O:b}}
function yb(a,b,c,d){var e=0,f=0,g=0,h=0,l=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<l;g++)if(a[g]!==c[g])break a;g=l}if(b==a.length&&d==c.length){h=a.length;for(var k=c.length,m=0;m<l-g&&zb(a[--h],c[--k]);)m++;h=m}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=xb(e,0);f<d;)b.I.push(c[f++]);return[b]}if(f==d)return[xb(e,b-e)];l=e;g=f;d=d-g+1;h=b-l+1;b=Array(d);for(k=0;k<d;k++)b[k]=Array(h),b[k][0]=k;for(k=0;k<h;k++)b[0][k]=k;for(k=1;k<d;k++)for(m=1;m<h;m++)if(a[l+m-1]===c[g+k-1])b[k][m]=
b[k-1][m-1];else{var q=b[k-1][m]+1,y=b[k][m-1]+1;b[k][m]=q<y?q:y}l=b.length-1;g=b[0].length-1;d=b[l][g];for(a=[];0<l||0<g;)0==l?(a.push(2),g--):0==g?(a.push(3),l--):(h=b[l-1][g-1],k=b[l-1][g],m=b[l][g-1],q=k<m?k<h?k:h:m<h?m:h,q==h?(h==d?a.push(0):(a.push(1),d=h),l--,g--):q==k?(a.push(3),l--,d=k):(a.push(2),g--,d=m));a.reverse();b=void 0;l=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(l.push(b),b=void 0);e++;f++;break;case 1:b||(b=xb(e,0));b.O++;e++;b.I.push(c[f]);f++;break;case 2:b||(b=xb(e,0));
b.O++;e++;break;case 3:b||(b=xb(e,0)),b.I.push(c[f]),f++}b&&l.push(b);return l}function zb(a,b){return a===b};function Ab(a,b,c){Ya(a);c=c||null;var d=p(a),e=p(b),f=c?p(c):null;d.previousSibling=c?f.previousSibling:b.__shady_lastChild;if(f=r(d.previousSibling))f.nextSibling=a;if(f=r(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function Bb(a,b,c){Za(b);var d=p(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){d=a.__shady_childNodes;for(var e=0;e<d.length;e++)Ab(d[e],b,c);a=p(a);b=void 0!==a.firstChild?null:void 0;a.firstChild=a.lastChild=b;a.childNodes=b}else Ab(a,b,c)}
function Cb(a,b){var c=p(a);b=p(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(p(a).nextSibling=d);d&&(p(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function Db(a){var b=p(a);if(void 0===b.firstChild){b.childNodes=null;var c=b.firstChild=a.__shady_native_firstChild||null;b.lastChild=a.__shady_native_lastChild||null;Za(a);b=c;for(c=void 0;b;b=b.__shady_native_nextSibling){var d=p(b);d.parentNode=a;d.nextSibling=b.__shady_native_nextSibling||null;d.previousSibling=c||null;c=b;Ya(b)}}};var Eb=null;function E(){Eb||(Eb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return Eb||null}function Fb(a,b){var c=E();c&&c.unscopeNode(a,b)}function Gb(a,b){var c=E();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;a=a.__shady_childNodes;for(var d=0;c&&d<a.length;d++)c=c&&Gb(a[d],b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}function Hb(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=E();return b?b.currentScopeForNode(a):""}
function Ib(a,b){if(a){a.nodeType===Node.ELEMENT_NODE&&b(a);a=a.__shady_childNodes;for(var c=0,d;c<a.length;c++)d=a[c],d.nodeType===Node.ELEMENT_NODE&&Ib(d,b)}};var Jb=window.document,Kb=t.ea,Lb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),Mb=Lb&&Lb.get;function Nb(a){for(var b;b=a.__shady_firstChild;)a.__shady_removeChild(b)}function Ob(a){var b=r(a);if(b&&void 0!==b.H){b=a.__shady_childNodes;for(var c=0,d=b.length,e=void 0;c<d&&(e=b[c]);c++)Ob(e)}if(a=r(a))a.H=void 0}function Pb(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=r(a))&&b.D)&&b.length?b[0]:Pb(a.__shady_nextSibling));return b}
function Qb(a,b,c){if(a=(a=r(a))&&a.F)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),xa(a)}
var Sb=z({get parentNode(){var a=r(this);a=a&&a.parentNode;return void 0!==a?a:this.__shady_native_parentNode},get firstChild(){var a=r(this);a=a&&a.firstChild;return void 0!==a?a:this.__shady_native_firstChild},get lastChild(){var a=r(this);a=a&&a.lastChild;return void 0!==a?a:this.__shady_native_lastChild},get nextSibling(){var a=r(this);a=a&&a.nextSibling;return void 0!==a?a:this.__shady_native_nextSibling},get previousSibling(){var a=r(this);a=a&&a.previousSibling;return void 0!==a?a:this.__shady_native_previousSibling},
get childNodes(){if(u(this)){var a=r(this);if(!a.childNodes){a.childNodes=[];for(var b=this.__shady_firstChild;b;b=b.__shady_nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=this.__shady_native_childNodes;c.item=function(d){return c[d]};return c},get parentElement(){var a=r(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:this.__shady_native_parentElement},get isConnected(){if(Mb&&Mb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;
var a=this.ownerDocument;if(qa){if(a.__shady_native_contains(this))return!0}else if(a.documentElement&&a.documentElement.__shady_native_contains(this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.__shady_parentNode||(v(a)?a.host:void 0);return!!(a&&a instanceof Document)},get textContent(){if(u(this)){for(var a=[],b=0,c=this.__shady_childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&a.push(d.__shady_textContent);return a.join("")}return this.__shady_native_textContent},set textContent(a){if("undefined"===
typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!u(this)&&t.m){var b=this.__shady_firstChild;(b!=this.__shady_lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&Nb(this);this.__shady_native_textContent=a}else Nb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_insertBefore(document.createTextNode(a));break;default:this.nodeValue=a}},insertBefore:function(a,b){if(this.ownerDocument!==Jb&&a.ownerDocument!==Jb)return this.__shady_native_insertBefore(a,
b),a;if(a===this)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(b){var c=r(b);c=c&&c.parentNode;if(void 0!==c&&c!==this||void 0===c&&b.__shady_native_parentNode!==this)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(b===a)return a;var d=[],e=(c=F(this))?c.host.localName:Hb(this),f=a.__shady_parentNode;if(f){var g=Hb(a);f.__shady_removeChild(a,!!c||
!F(a))}f=!0;var h=(!Kb||void 0===a.__noInsertionPoint)&&!Gb(a,e),l=c&&!a.__noInsertionPoint&&(!Kb||a.nodeType===Node.DOCUMENT_FRAGMENT_NODE);if(l||h)h&&(g=g||Hb(a)),Ib(a,function(k){l&&"slot"===k.localName&&d.push(k);if(h){var m=g;E()&&(m&&Fb(k,m),(m=E())&&m.scopeNode(k,e))}});if("slot"===this.localName||d.length)d.length&&(c.i=c.i||[],c.g=c.g||[],c.h=c.h||{},c.i.push.apply(c.i,d instanceof Array?d:da(ca(d)))),c&&G(c);u(this)&&(Bb(a,this,b),c=r(this),ja(this)?(G(c.root),f=!1):c.root&&(f=!1));f?(c=
v(this)?this.host:this,b?(b=Pb(b),c.__shady_native_insertBefore(a,b)):c.__shady_native_appendChild(a)):a.ownerDocument!==this.ownerDocument&&this.ownerDocument.adoptNode(a);Qb(this,a);return a},appendChild:function(a){return this.__shady_insertBefore(a)},removeChild:function(a,b){b=void 0===b?!1:b;if(this.ownerDocument!==Jb)return this.__shady_native_removeChild(a);if(a.__shady_parentNode!==this)throw Error("The node to be removed is not a child of this node: "+a);var c=F(a),d=c&&Rb(c,a),e=r(this);
if(u(this)&&(Cb(a,this),ja(this))){G(e.root);var f=!0}if(E()&&!b&&c){var g=Hb(a);Ib(a,function(h){Fb(h,g)})}Ob(a);c&&((b=this&&"slot"===this.localName)&&(f=!0),(d||b)&&G(c));f||(f=v(this)?this.host:this,(!e.root&&"slot"!==a.localName||f===a.__shady_native_parentNode)&&f.__shady_native_removeChild(a));Qb(this,null,a);return a},replaceChild:function(a,b){this.__shady_insertBefore(a,b);this.__shady_removeChild(b);return a},cloneNode:function(a){if("template"==this.localName)return this.__shady_native_cloneNode(a);
var b=this.__shady_native_cloneNode(!1);if(a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.__shady_childNodes;for(var c=0,d;c<a.length;c++)d=a[c].__shady_cloneNode(!0),b.__shady_appendChild(d)}return b},getRootNode:function(a){if(this&&this.nodeType){var b=p(this),c=b.H;void 0===c&&(v(this)?(c=this,b.H=c):(c=(c=this.__shady_parentNode)?c.__shady_getRootNode(a):this,document.documentElement.__shady_native_contains(this)&&(b.H=c)));return c}},contains:function(a){return ra(this,a)}});function Tb(a,b,c){var d=[];Ub(a.__shady_childNodes,b,c,d);return d}function Ub(a,b,c,d){for(var e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var l=b,k=c,m=d,q=l(h);q&&m.push(h);k&&k(q)?h=q:(Ub(h.__shady_childNodes,l,k,m),h=void 0)}if(h)break}}
var H=z({get firstElementChild(){var a=r(this);if(a&&void 0!==a.firstChild){for(a=this.__shady_firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_firstElementChild},get lastElementChild(){var a=r(this);if(a&&void 0!==a.lastChild){for(a=this.__shady_lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_lastElementChild},get children(){return u(this)?sa(Array.prototype.filter.call(this.__shady_childNodes,
function(a){return a.nodeType===Node.ELEMENT_NODE})):this.__shady_native_children},get childElementCount(){var a=this.__shady_children;return a?a.length:0}}),Vb=z({querySelector:function(a){return Tb(this,function(b){return la.call(b,a)},function(b){return!!b})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(this.__shady_native_querySelectorAll(a));var c=this.__shady_getRootNode();return b.filter(function(d){return d.__shady_getRootNode()==c})}return Tb(this,function(d){return la.call(d,
a)})}}),Wb=t.ea?Object.assign({},H):H;Object.assign(H,Vb);var Xb=z({getElementById:function(a){return""===a?null:Tb(this,function(b){return b.id==a},function(b){return!!b})[0]||null}});var Yb=z({get activeElement(){var a=t.m?document.__shady_native_activeElement:document.activeElement;if(!a||!a.nodeType)return null;var b=!!v(this);if(!(this===document||b&&this.host!==a&&this.host.__shady_native_contains(a)))return null;for(b=F(a);b&&b!==this;)a=b.host,b=F(a);return this===document?b?null:a:b===this?a:null}});var Zb=document.implementation.createHTMLDocument("inert"),$b=z({get innerHTML(){return u(this)?Ia("template"===this.localName?this.content:this,function(a){return a.__shady_childNodes}):this.__shady_native_innerHTML},set innerHTML(a){if("template"===this.localName)this.__shady_native_innerHTML=a;else{Nb(this);var b=this.localName||"div";b=this.namespaceURI&&this.namespaceURI!==Zb.namespaceURI?Zb.createElementNS(this.namespaceURI,b):Zb.createElement(b);for(t.m?b.__shady_native_innerHTML=a:b.innerHTML=
a;a=b.__shady_firstChild;)this.__shady_insertBefore(a)}}});var ac=z({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.U=this;this.host.__shady_addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.U=this;this.host.__shady_removeEventListener(a,b,c)}});function bc(a,b){x(a,ac,b);x(a,Yb,b);x(a,$b,b);x(a,H,b);t.G&&!b?(x(a,Sb,b),x(a,Xb,b)):t.m||(x(a,Ua),x(a,Ta))};var cc={},I=t.deferConnectionCallbacks&&"loading"===document.readyState,dc;function ec(a){var b=[];do b.unshift(a);while(a=a.__shady_parentNode);return b}
function fc(a,b,c){if(a!==cc)throw new TypeError("Illegal constructor");this.la="ShadyRoot";this.host=b;this.mode=c&&c.mode;Db(b);a=p(b);a.root=this;a.fa="closed"!==this.mode?this:null;a=p(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;a.childNodes=[];this.V=this.C=!1;this.i=this.h=this.g=null;if(t.preferPerformance)for(;a=b.__shady_native_firstChild;)b.__shady_native_removeChild(a);else G(this)}function G(a){a.C||(a.C=!0,ua(function(){return gc(a)}))}
function gc(a){var b;if(b=a.C){for(var c;a;)a:{a.C&&(c=a),b=a;a=b.host.__shady_getRootNode();if(v(a)&&(b=r(b.host))&&0<b.L)break a;a=void 0}b=c}(c=b)&&c._renderSelf()}
fc.prototype._renderSelf=function(){var a=I;I=!0;this.C=!1;if(this.g){hc(this);for(var b=0,c;b<this.g.length;b++){c=this.g[b];var d=r(c),e=d.assignedNodes;d.assignedNodes=[];d.D=[];if(d.W=e)for(d=0;d<e.length;d++){var f=r(e[d]);f.N=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(b=this.host.__shady_firstChild;b;b=b.__shady_nextSibling)ic(this,b);for(b=0;b<this.g.length;b++){c=this.g[b];e=r(c);if(!e.assignedNodes.length)for(d=c.__shady_firstChild;d;d=d.__shady_nextSibling)ic(this,d,c);
(d=(d=r(c.__shady_parentNode))&&d.root)&&(ka(d)||d.C)&&d._renderSelf();jc(this,e.D,e.assignedNodes);if(d=e.W){for(f=0;f<d.length;f++)r(d[f]).N=null;e.W=null;d.length>e.assignedNodes.length&&(e.R=!0)}e.R&&(e.R=!1,kc(this,c))}c=this.g;b=[];for(e=0;e<c.length;e++)d=c[e].__shady_parentNode,(f=r(d))&&f.root||!(0>b.indexOf(d))||b.push(d);for(c=0;c<b.length;c++){f=b[c];e=f===this?this.host:f;d=[];f=f.__shady_childNodes;for(var g=0;g<f.length;g++){var h=f[g];if("slot"==h.localName){h=r(h).D;for(var l=0;l<
h.length;l++)d.push(h[l])}else d.push(h)}f=Array.prototype.slice.call(e.__shady_native_childNodes);g=yb(d,d.length,f,f.length);l=h=0;for(var k=void 0;h<g.length&&(k=g[h]);h++){for(var m=0,q=void 0;m<k.I.length&&(q=k.I[m]);m++)q.__shady_native_parentNode===e&&e.__shady_native_removeChild(q),f.splice(k.index+l,1);l-=k.O}l=0;for(k=void 0;l<g.length&&(k=g[l]);l++)for(h=f[k.index],m=k.index;m<k.index+k.O;m++)q=d[m],e.__shady_native_insertBefore(q,h),f.splice(m,0,q)}}if(!t.preferPerformance&&!this.V)for(b=
this.host.__shady_childNodes,c=0,e=b.length;c<e;c++)d=b[c],f=r(d),d.__shady_native_parentNode!==this.host||"slot"!==d.localName&&f.assignedSlot||this.host.__shady_native_removeChild(d);this.V=!0;I=a;dc&&dc()};function ic(a,b,c){var d=p(b),e=d.N;d.N=null;c||(c=(a=a.h[b.__shady_slot||"__catchall"])&&a[0]);c?(p(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(p(d.assignedSlot).R=!0)}
function jc(a,b,c){for(var d=0,e=void 0;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=r(e).assignedNodes;f&&f.length&&jc(a,b,f)}else b.push(c[d])}function kc(a,b){b.__shady_native_dispatchEvent(new Event("slotchange"));b=r(b);b.assignedSlot&&kc(a,b.assignedSlot)}
function hc(a){if(a.i&&a.i.length){for(var b=a.i,c,d=0;d<b.length;d++){var e=b[d];Db(e);var f=e.__shady_parentNode;Db(f);f=r(f);f.L=(f.L||0)+1;f=lc(e);a.h[f]?(c=c||{},c[f]=!0,a.h[f].push(e)):a.h[f]=[e];a.g.push(e)}if(c)for(var g in c)a.h[g]=mc(a.h[g]);a.i=[]}}function lc(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.ja=b}
function mc(a){return a.sort(function(b,c){b=ec(b);for(var d=ec(c),e=0;e<b.length;e++){c=b[e];var f=d[e];if(c!==f)return b=Array.from(c.__shady_parentNode.__shady_childNodes),b.indexOf(c)-b.indexOf(f)}})}
function Rb(a,b){if(a.g){hc(a);var c=a.h,d;for(d in c)for(var e=c[d],f=0;f<e.length;f++){var g=e[f];if(ra(b,g)){e.splice(f,1);var h=a.g.indexOf(g);0<=h&&(a.g.splice(h,1),(h=r(g.__shady_parentNode))&&h.L&&h.L--);f--;g=r(g);if(h=g.D)for(var l=0;l<h.length;l++){var k=h[l],m=k.__shady_native_parentNode;m&&m.__shady_native_removeChild(k)}g.D=[];g.assignedNodes=[];h=!0}}return h}}function ka(a){hc(a);return!(!a.g||!a.g.length)}
(function(a){a.__proto__=DocumentFragment.prototype;bc(a,"__shady_");bc(a);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})})(fc.prototype);
if(window.customElements&&t.X&&!t.preferPerformance){var nc=new Map;dc=function(){var a=[];nc.forEach(function(d,e){a.push([e,d])});nc.clear();for(var b=0;b<a.length;b++){var c=a[b][0];a[b][1]?c.ha():c.ia()}};I&&document.addEventListener("readystatechange",function(){I=!1;dc()},{once:!0});var oc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.ha=function(){I?nc.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.ia=
function(){I?this.isConnected||nc.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},pc=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;pc.call(window.customElements,a,oc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})}function F(a){a=a.__shady_getRootNode();if(v(a))return a};function J(a){this.node=a}n=J.prototype;n.addEventListener=function(a,b,c){return this.node.__shady_addEventListener(a,b,c)};n.removeEventListener=function(a,b,c){return this.node.__shady_removeEventListener(a,b,c)};n.appendChild=function(a){return this.node.__shady_appendChild(a)};n.insertBefore=function(a,b){return this.node.__shady_insertBefore(a,b)};n.removeChild=function(a){return this.node.__shady_removeChild(a)};n.replaceChild=function(a,b){return this.node.__shady_replaceChild(a,b)};
n.cloneNode=function(a){return this.node.__shady_cloneNode(a)};n.getRootNode=function(a){return this.node.__shady_getRootNode(a)};n.contains=function(a){return this.node.__shady_contains(a)};n.dispatchEvent=function(a){return this.node.__shady_dispatchEvent(a)};n.setAttribute=function(a,b){this.node.__shady_setAttribute(a,b)};n.getAttribute=function(a){return this.node.__shady_native_getAttribute(a)};n.removeAttribute=function(a){this.node.__shady_removeAttribute(a)};n.attachShadow=function(a){return this.node.__shady_attachShadow(a)};
n.focus=function(){this.node.__shady_native_focus()};n.blur=function(){this.node.__shady_blur()};n.importNode=function(a,b){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_importNode(a,b)};n.getElementById=function(a){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_getElementById(a)};n.querySelector=function(a){return this.node.__shady_querySelector(a)};n.querySelectorAll=function(a,b){return this.node.__shady_querySelectorAll(a,b)};
n.assignedNodes=function(a){if("slot"===this.node.localName)return this.node.__shady_assignedNodes(a)};
fa.Object.defineProperties(J.prototype,{activeElement:{configurable:!0,enumerable:!0,get:function(){if(v(this.node)||this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_activeElement}},_activeElement:{configurable:!0,enumerable:!0,get:function(){return this.activeElement}},host:{configurable:!0,enumerable:!0,get:function(){if(v(this.node))return this.node.host}},parentNode:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_parentNode}},firstChild:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_firstChild}},lastChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastChild}},nextSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextSibling}},previousSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousSibling}},childNodes:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childNodes}},parentElement:{configurable:!0,enumerable:!0,
get:function(){return this.node.__shady_parentElement}},firstElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_firstElementChild}},lastElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastElementChild}},nextElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextElementSibling}},previousElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousElementSibling}},
children:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_children}},childElementCount:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childElementCount}},shadowRoot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_shadowRoot}},assignedSlot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_assignedSlot}},isConnected:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_isConnected}},innerHTML:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_innerHTML},set:function(a){this.node.__shady_innerHTML=a}},textContent:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_textContent},set:function(a){this.node.__shady_textContent=a}},slot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_slot},set:function(a){this.node.__shady_slot=a}}});
wb.forEach(function(a){Object.defineProperty(J.prototype,a,{get:function(){return this.node["__shady_"+a]},set:function(b){this.node["__shady_"+a]=b},configurable:!0})});var qc=new WeakMap;function rc(a){if(v(a)||a instanceof J)return a;var b=qc.get(a);b||(b=new J(a),qc.set(a,b));return b};var sc=z({dispatchEvent:function(a){va();return this.__shady_native_dispatchEvent(a)},addEventListener:nb,removeEventListener:pb});var tc=z({get assignedSlot(){var a=this.__shady_parentNode;(a=a&&a.__shady_shadowRoot)&&gc(a);return(a=r(this))&&a.assignedSlot||null}});var uc=window.document;function vc(a,b){if("slot"===b)a=a.__shady_parentNode,ja(a)&&G(r(a).root);else if("slot"===a.localName&&"name"===b&&(b=F(a))){if(b.g){hc(b);var c=a.ja,d=lc(a);if(d!==c){c=b.h[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.h[d]||(b.h[d]=[]);c.push(a);1<c.length&&(b.h[d]=mc(c))}}G(b)}}
var wc=z({get previousElementSibling(){var a=r(this);if(a&&void 0!==a.previousSibling){for(a=this.__shady_previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_previousElementSibling},get nextElementSibling(){var a=r(this);if(a&&void 0!==a.nextSibling){for(a=this.__shady_nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_nextElementSibling},get slot(){return this.getAttribute("slot")},
set slot(a){this.__shady_setAttribute("slot",a)},get shadowRoot(){var a=r(this);return a&&a.fa||null},get className(){return this.getAttribute("class")||""},set className(a){this.__shady_setAttribute("class",a)},setAttribute:function(a,b){if(this.ownerDocument!==uc)this.__shady_native_setAttribute(a,b);else{var c;(c=E())&&"class"===a?(c.setElementClass(this,b),c=!0):c=!1;c||(this.__shady_native_setAttribute(a,b),vc(this,a))}},removeAttribute:function(a){this.__shady_native_removeAttribute(a);vc(this,
a)},attachShadow:function(a){if(!this)throw Error("Must provide a host.");if(!a)throw Error("Not enough arguments.");return new fc(cc,this,a)}});var xc=z({blur:function(){var a=r(this);(a=(a=a&&a.root)&&a.activeElement)?a.__shady_blur():this.__shady_native_blur()}});wb.forEach(function(a){xc[a]={set:function(b){var c=p(this),d=a.substring(2);c.M[a]&&this.removeEventListener(d,c.M[a]);this.__shady_addEventListener(d,b);c.M[a]=b},get:function(){var b=r(this);return b&&b.M[a]},configurable:!0}});var yc=z({assignedNodes:function(a){if("slot"===this.localName){var b=this.__shady_getRootNode();b&&v(b)&&gc(b);return(b=r(this))?(a&&a.flatten?b.D:b.assignedNodes)||[]:[]}}});var zc=window.document,Ac=z({importNode:function(a,b){if(a.ownerDocument!==zc||"template"===a.localName)return this.__shady_native_importNode(a,b);var c=this.__shady_native_importNode(a,!1);if(b){a=a.__shady_childNodes;b=0;for(var d;b<a.length;b++)d=this.__shady_importNode(a[b],!0),c.__shady_appendChild(d)}return c}});var Bc=z({addEventListener:nb.bind(window),removeEventListener:pb.bind(window)});var K={};Object.getOwnPropertyDescriptor(HTMLElement.prototype,"parentElement")&&(K.parentElement=Sb.parentElement);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"contains")&&(K.contains=Sb.contains);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"children")&&(K.children=H.children);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&(K.innerHTML=$b.innerHTML);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"className")&&(K.className=wc.className);
var Cc={EventTarget:[sc],Node:[Sb,window.EventTarget?null:sc],Text:[tc],Element:[wc,H,tc,!t.m||"innerHTML"in Element.prototype?$b:null,window.HTMLSlotElement?null:yc],HTMLElement:[xc,K],HTMLSlotElement:[yc],DocumentFragment:[Wb,Xb],Document:[Ac,Wb,Xb,Yb],Window:[Bc]},Dc=t.m?null:["innerHTML","textContent"];function Ec(a){var b=a?null:Dc,c={},d;for(d in Cc)c.K=window[d]&&window[d].prototype,Cc[d].forEach(function(e){return function(f){return e.K&&f&&x(e.K,f,a,b)}}(c)),c={K:c.K}};if(t.X){var ShadyDOM={inUse:t.X,patch:function(a){Za(a);Ya(a);return a},isShadyRoot:v,enqueue:ua,flush:va,flushInitial:function(a){!a.V&&a.C&&gc(a)},settings:t,filterMutations:Aa,observeChildren:ya,unobserveChildren:za,deferConnectionCallbacks:t.deferConnectionCallbacks,preferPerformance:t.preferPerformance,handlesDynamicScoping:!0,wrap:t.G?rc:function(a){return a},Wrapper:J,composedPath:fb,noPatch:t.G,nativeMethods:Ka,nativeTree:La};window.ShadyDOM=ShadyDOM;Sa();Ec("__shady_");Object.defineProperty(document,
"_activeElement",Yb.activeElement);x(Window.prototype,Bc,"__shady_");t.G||(Ec(),vb());qb();window.Event=sb;window.CustomEvent=tb;window.MouseEvent=ub;window.ShadowRoot=fc};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Fc(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Gc(a){var b=a=a.replace(Hc,"").replace(Ic,""),c=new Fc;c.start=0;c.end=b.length;for(var d=c,e=0,f=b.length;e<f;e++)if("{"===b[e]){d.rules||(d.rules=[]);var g=d,h=g.rules[g.rules.length-1]||null;d=new Fc;d.start=e+1;d.parent=g;d.previous=h;g.rules.push(d)}else"}"===b[e]&&(d.end=e+1,d=d.parent||c);return Jc(c,a)}
function Jc(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=Kc(c),c=c.replace(Lc," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=Mc:c.match(Nc)&&(a.type=Oc,a.keyframesName=a.selector.split(Lc).pop()):a.type=0===c.indexOf("--")?Pc:Qc);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)Jc(f,
b);return a}function Kc(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(b,c){b=c;for(c=6-b.length;c--;)b="0"+b;return"\\"+b})}
function Rc(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h=void 0;f<g&&(h=e[f]);f++)d=Rc(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(Sc,"").replace(Tc,""),b=b.replace(Uc,"").replace(Vc,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var Qc=1,Oc=7,Mc=4,Pc=1E3,Hc=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,Ic=/@import[^;]*;/gim,Sc=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Tc=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Uc=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Vc=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Nc=/^@[^\s]*keyframes/,Lc=/\s+/g;var L=!(window.ShadyDOM&&window.ShadyDOM.inUse),Wc;function Xc(a){Wc=a&&a.shimcssproperties?!1:L||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var Yc;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&(Yc=window.ShadyCSS.cssBuild);var M=!(!window.ShadyCSS||!window.ShadyCSS.disableRuntime);
window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?Wc=window.ShadyCSS.nativeCss:window.ShadyCSS?(Xc(window.ShadyCSS),window.ShadyCSS=void 0):Xc(window.WebComponents&&window.WebComponents.flags);var N=Wc;var Zc=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,$c=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,ad=/(--[\w-]+)\s*([:,;)]|$)/gi,bd=/(animation\s*:)|(animation-name\s*:)/,cd=/@media\s(.*)/,dd=/\{[^}]*\}/g;var ed=new Set;function O(a,b){if(!a)return"";"string"===typeof a&&(a=Gc(a));b&&P(a,b);return Rc(a,N)}function fd(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Gc(a.textContent));return a.__cssRules||null}function gd(a){return!!a.parent&&a.parent.type===Oc}function P(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===Mc){var g=a.selector.match(cd);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===Qc?b(a):c&&f===Oc?c(a):f===Pc&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++)P(g,b,c,d)}}
function hd(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;id(e,c,d);return e}var Q=null;function jd(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(Q?Q.nextSibling:null)||b.firstChild);return Q=a}function id(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);Q?a.compareDocumentPosition(Q)===Node.DOCUMENT_POSITION_PRECEDING&&(Q=a):Q=a}
function kd(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function ld(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=kd(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=ld(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function md(a,b){L?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
var nd=window.ShadyDOM&&window.ShadyDOM.wrap||function(a){return a};function R(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,J:c}}function od(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=kd(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function S(a){if(void 0!==Yc)return Yc;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function pd(a){a=void 0===a?"":a;return""!==a&&N?L?"shadow"===a:"shady"===a:!1};function qd(){}function rd(a,b){sd(T,a,function(c){U(c,b||"")})}function sd(a,b,c){b.nodeType===Node.ELEMENT_NODE&&c(b);if(b="template"===b.localName?(b.content||b._content||b).childNodes:b.children||b.childNodes)for(var d=0;d<b.length;d++)sd(a,b[d],c)}
function U(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),md(a,b)):md(a,(d?d+" ":"")+"style-scope "+b)}}function td(a,b,c){sd(T,a,function(d){U(d,b,!0);U(d,c)})}function ud(a,b){sd(T,a,function(c){U(c,b||"",!0)})}
function vd(a,b,c,d,e){var f=T;e=void 0===e?"":e;""===e&&(L||"shady"===(void 0===d?"":d)?e=O(b,c):(a=R(a),e=wd(f,b,a.is,a.J,c)+"\n\n"));return e.trim()}function wd(a,b,c,d,e){var f=xd(c,d);c=c?"."+c:"";return O(b,function(g){g.i||(g.selector=g.l=yd(a,g,a.h,c,f),g.i=!0);e&&e(g,c,f)})}function xd(a,b){return b?"[is="+a+"]":a}
function yd(a,b,c,d,e){var f=od(b.selector);if(!gd(b)){b=0;for(var g=f.length,h=void 0;b<g&&(h=f[b]);b++)f[b]=c.call(a,h,d,e)}return f.filter(function(l){return!!l}).join(",")}function zd(a){return a.replace(Ad,function(b,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
function Bd(a){for(var b=[],c;c=a.match(Cd);){var d=c.index,e=kd(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{$:a,matches:b}}function Dd(a,b){var c=a.split("\ue000");return b.reduce(function(d,e,f){return d+e+c[f+1]},c[0])}
qd.prototype.h=function(a,b,c){var d=!1;a=a.trim();var e=Ad.test(a);e&&(a=a.replace(Ad,function(h,l,k){return":"+l+"("+k.replace(/\s/g,"")+")"}),a=zd(a));var f=Cd.test(a);if(f){var g=Bd(a);a=g.$;g=g.matches}a=a.replace(Ed,":host $1");a=a.replace(Fd,function(h,l,k){d||(h=Gd(k,l,b,c),d=d||h.stop,l=h.pa,k=h.value);return l+k});f&&(a=Dd(a,g));e&&(a=zd(a));return a};
function Gd(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=Hd(a,d):0!==e&&(a=c?Id(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(Jd,function(g,h){return" > "+h}))}a=a.replace(Kd,function(g,h,l){return'[dir="'+l+'"] '+h+", "+h+'[dir="'+l+'"]'});return{value:a,pa:b,stop:f}}
function Id(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")}function Hd(a,b){var c=a.match(Ld);return(c=c&&c[2].trim()||"")?c[0].match(Md)?a.replace(Ld,function(d,e,f){return b+f}):c.split(Md)[0]===b?c:"should_not_match":a.replace(":host",b)}function Nd(a){":root"===a.selector&&(a.selector="html")}
qd.prototype.i=function(a){return a.match(":host")?"":a.match("::slotted")?this.h(a,":not(.style-scope)"):Id(a.trim(),":not(.style-scope)")};fa.Object.defineProperties(qd.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Ad=/:(nth[-\w]+)\(([^)]+)\)/,Fd=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,Md=/[[.:#*]/,Ed=/^(::slotted)/,Ld=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Jd=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Kd=/(.*):dir\((?:(ltr|rtl))\)/,Cd=/:(?:matches|any|-(?:webkit|moz)-any)/,T=new qd;function V(a,b,c,d,e){this.B=a||null;this.h=b||null;this.Z=c||[];this.s=null;this.cssBuild=e||"";this.J=d||"";this.g=this.u=this.A=null}function W(a){return a?a.__styleInfo:null}function Od(a,b){return a.__styleInfo=b}V.prototype.i=function(){return this.B};V.prototype._getStyleRules=V.prototype.i;function Pd(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var Qd=navigator.userAgent.match("Trident");function Rd(){}function Sd(a){var b={},c=[],d=0;P(a,function(f){Td(f);f.index=d++;f=f.j.cssText;for(var g;g=ad.exec(f);){var h=g[1];":"!==g[2]&&(b[h]=!0)}},function(f){c.push(f)});a.h=c;a=[];for(var e in b)a.push(e);return a}
function Td(a){if(!a.j){var b={},c={};Ud(a,c)&&(b.v=c,a.rules=null);b.cssText=a.parsedCssText.replace(dd,"").replace(Zc,"");a.j=b}}function Ud(a,b){var c=a.j;if(c){if(c.v)return Object.assign(b,c.v),!0}else{c=a.parsedCssText;for(var d;a=Zc.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function Vd(a,b,c){b&&(b=0<=b.indexOf(";")?Wd(a,b,c):ld(b,function(d,e,f,g){if(!e)return d+g;(e=Vd(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=Vd(a,c[f]||f,c)||f;return d+(e||"")+g}));return b&&b.trim()||""}
function Wd(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){$c.lastIndex=0;if(f=$c.exec(e))e=Vd(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=Vd(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function Xd(a,b){var c={},d=[];P(a,function(e){e.j||Td(e);var f=e.l||e.parsedSelector;b&&e.j.v&&f&&Pd.call(b,f)&&(Ud(e,c),e=e.index,f=parseInt(e/32,10),d[f]=(d[f]||0)|1<<e%32)},null,!0);return{v:c,key:d}}
function Yd(a,b,c,d){b.j||Td(b);if(b.j.v){var e=R(a);a=e.is;e=e.J;e=a?xd(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));if(g||h)c=e,h&&(b.l||(b.l=yd(T,b,T.h,a?"."+a:"",e)),c=b.l||e),d({$:c,ua:h,Da:g})}}function Zd(a,b,c){var d={},e={};P(b,function(f){Yd(a,f,c,function(g){Pd.call(a._element||a,g.$)&&(g.ua?Ud(f,d):Ud(f,e))})},null,!0);return{wa:e,ta:d}}
function $d(a,b,c,d){var e=R(b),f=xd(e.is,e.J),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),h=W(b);e=h.B;h=h.cssBuild;var l=ae(e,d);return vd(b,e,function(k){var m="";k.j||Td(k);k.j.cssText&&(m=Wd(a,k.j.cssText,c));k.cssText=m;if(!L&&!gd(k)&&k.cssText){var q=m=k.cssText;null==k.ca&&(k.ca=bd.test(m));if(k.ca)if(null==k.S){k.S=[];for(var y in l)q=l[y],q=q(m),m!==q&&(m=q,k.S.push(y))}else{for(y=0;y<k.S.length;++y)q=l[k.S[y]],m=q(m);q=m}k.cssText=q;k.l=k.l||k.selector;
m="."+d;y=od(k.l);q=0;for(var aa=y.length,Ea=void 0;q<aa&&(Ea=y[q]);q++)y[q]=Ea.match(g)?Ea.replace(f,m):m+" "+Ea;k.selector=y.join(",")}},h)}function ae(a,b){a=a.h;var c={};if(!L&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,g=b;f.o=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.g=f.keyframesName+"-"+g;f.l=f.l||f.selector;f.selector=f.l.replace(f.keyframesName,f.g);c[e.keyframesName]=be(e)}return c}function be(a){return function(b){return b.replace(a.o,a.g)}}
function ce(a,b){var c=de,d=fd(a);a.textContent=O(d,function(e){var f=e.cssText=e.parsedCssText;e.j&&e.j.cssText&&(f=f.replace(Sc,"").replace(Tc,""),e.cssText=Wd(c,f,b))})}fa.Object.defineProperties(Rd.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var de=new Rd;var X={},ee=window.customElements;if(ee&&!L&&!M){var fe=ee.define;ee.define=function(a,b,c){X[a]||(X[a]=jd(a));fe.call(ee,a,b,c)}};function ge(){this.cache={}}ge.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({v:b,styleElement:c,u:d});100<e.length&&e.shift();this.cache[a]=e};function he(){}var ie=new RegExp(T.g+"\\s*([^\\s]*)");function je(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(ie))?a[1]:""}function ke(a){var b=nd(a).getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?R(a).is:""}
function le(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g=je(e);if(g&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===S(e)))ud(e,g);else if(f instanceof ShadowRoot)for(f=ke(e),f!==g&&td(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+T.g+")"),g=0;g<e.length;g++){f=e[g];
var h=ke(f);h&&U(f,h)}}}}}
if(!(L||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var me=new MutationObserver(le),ne=function(a){me.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)ne(document);else{var oe=function(){ne(document.body)};window.HTMLImports?window.HTMLImports.whenReady(oe):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){oe();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else oe()})}he=function(){le(me.takeRecords())}};var pe={};var qe=Promise.resolve();function re(a){if(a=pe[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function se(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function te(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,qe.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var ue={},ve=new ge;function Y(){this.da={};this.i=document.documentElement;var a=new Fc;a.rules=[];this.o=Od(this.i,new V(a));this.Y=!1;this.h=this.g=null}n=Y.prototype;n.flush=function(){he()};n.ra=function(a){return fd(a)};n.Aa=function(a){return O(a)};n.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
n.prepareTemplateStyles=function(a,b,c){if(!a._prepared&&!M){L||X[b]||(X[b]=jd(b));a._prepared=!0;a.name=b;a.extends=c;pe[b]=a;var d=S(a),e=pd(d);c={is:b,extends:c};for(var f=[],g=a.content.querySelectorAll("style"),h=0;h<g.length;h++){var l=g[h];if(l.hasAttribute("shady-unscoped")){if(!L){var k=l.textContent;ed.has(k)||(ed.add(k),k=l.cloneNode(!0),document.head.appendChild(k));l.parentNode.removeChild(l)}}else f.push(l.textContent),l.parentNode.removeChild(l)}f=f.join("").trim()+(ue[b]||"");we(this);
if(!e){if(g=!d)g=$c.test(f)||Zc.test(f),$c.lastIndex=0,Zc.lastIndex=0;h=Gc(f);g&&N&&this.g&&this.g.transformRules(h,b);a._styleAst=h}g=[];N||(g=Sd(a._styleAst));if(!g.length||N)h=L?a.content:null,b=X[b]||null,d=vd(c,a._styleAst,null,d,e?f:""),d=d.length?hd(d,c.is,h,b):null,a._style=d;a.g=g}};n.va=function(a,b){ue[b]=a.join(" ")};n.prepareTemplateDom=function(a,b){if(!M){var c=S(a);L||"shady"===c||a._domPrepared||(a._domPrepared=!0,rd(a.content,b))}};
function xe(a){var b=R(a),c=b.is;b=b.J;var d=X[c]||null,e=pe[c];if(e){c=e._styleAst;var f=e.g;e=S(e);b=new V(c,d,f,b,e);Od(a,b);return b}}function ye(a){!a.h&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.h=window.ShadyCSS.CustomStyleInterface,a.h.transformCallback=function(b){a.ga(b)},a.h.validateCallback=function(){requestAnimationFrame(function(){(a.h.enqueued||a.Y)&&a.flushCustomStyles()})})}
function we(a){!a.g&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.g=window.ShadyCSS.ApplyShim,a.g.invalidCallback=re);ye(a)}
n.flushCustomStyles=function(){if(!M&&(we(this),this.h)){var a=this.h.processStyles();if(this.h.enqueued&&!pd(this.o.cssBuild)){if(N){if(!this.o.cssBuild)for(var b=0;b<a.length;b++){var c=this.h.getStyleForCustomStyle(a[b]);if(c&&N&&this.g){var d=fd(c);we(this);this.g.transformRules(d);c.textContent=O(d)}}}else{ze(this,this.i,this.o);for(b=0;b<a.length;b++)(c=this.h.getStyleForCustomStyle(a[b]))&&ce(c,this.o.A);this.Y&&this.styleDocument()}this.h.enqueued=!1}}};
n.styleElement=function(a,b){if(M){if(b){W(a)||Od(a,new V(null));var c=W(a);c.s=c.s||{};Object.assign(c.s,b);Ae(this,a,c)}}else if(c=W(a)||xe(a))if(a!==this.i&&(this.Y=!0),b&&(c.s=c.s||{},Object.assign(c.s,b)),N)Ae(this,a,c);else if(this.flush(),ze(this,a,c),c.Z&&c.Z.length){b=R(a).is;var d;a:{if(d=ve.cache[b])for(var e=d.length-1;0<=e;e--){var f=d[e];b:{var g=c.Z;for(var h=0;h<g.length;h++){var l=g[h];if(f.v[l]!==c.A[l]){g=!1;break b}}g=!0}if(g){d=f;break a}}d=void 0}g=d?d.styleElement:null;e=c.u;
(f=d&&d.u)||(f=this.da[b]=(this.da[b]||0)+1,f=b+"-"+f);c.u=f;f=c.u;h=de;h=g?g.textContent||"":$d(h,a,c.A,f);l=W(a);var k=l.g;k&&!L&&k!==g&&(k._useCount--,0>=k._useCount&&k.parentNode&&k.parentNode.removeChild(k));L?l.g?(l.g.textContent=h,g=l.g):h&&(g=hd(h,f,a.shadowRoot,l.h)):g?g.parentNode||(Qd&&-1<h.indexOf("@media")&&(g.textContent=h),id(g,null,l.h)):h&&(g=hd(h,f,null,l.h));g&&(g._useCount=g._useCount||0,l.g!=g&&g._useCount++,l.g=g);f=g;L||(g=c.u,l=h=a.getAttribute("class")||"",e&&(l=h.replace(new RegExp("\\s*x-scope\\s*"+
e+"\\s*","g")," ")),l+=(l?" ":"")+"x-scope "+g,h!==l&&md(a,l));d||ve.store(b,c.A,f,c.u)}};
function Ae(a,b,c){var d=R(b).is;if(c.s){var e=c.s,f;for(f in e)null===f?b.style.removeProperty(f):b.style.setProperty(f,e[f])}e=pe[d];if(!(!e&&b!==a.i||e&&""!==S(e))&&e&&e._style&&!se(e)){if(se(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)we(a),a.g&&a.g.transformRules(e._styleAst,d),e._style.textContent=vd(b,c.B),te(e);L&&(a=b.shadowRoot)&&(a=a.querySelector("style"))&&(a.textContent=vd(b,c.B));c.B=e._styleAst}}
function Be(a,b){return(b=nd(b).getRootNode().host)?W(b)||xe(b)?b:Be(a,b):a.i}function ze(a,b,c){var d=Be(a,b),e=W(d),f=e.A;d===a.i||f||(ze(a,d,e),f=e.A);a=Object.create(f||null);d=Zd(b,c.B,c.cssBuild);b=Xd(e.B,b).v;Object.assign(a,d.ta,b,d.wa);b=c.s;for(var g in b)if((e=b[g])||0===e)a[g]=e;g=de;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=Vd(g,a[d],a);c.A=a}n.styleDocument=function(a){this.styleSubtree(this.i,a)};
n.styleSubtree=function(a,b){var c=nd(a),d=c.shadowRoot;(d||a===this.i)&&this.styleElement(a,b);if(a=d&&(d.children||d.childNodes))for(c=0;c<a.length;c++)this.styleSubtree(a[c]);else if(c=c.children||c.childNodes)for(a=0;a<c.length;a++)this.styleSubtree(c[a])};
n.ga=function(a){var b=this,c=S(a);c!==this.o.cssBuild&&(this.o.cssBuild=c);if(!pd(c)){var d=fd(a);P(d,function(e){if(L)Nd(e);else{var f=T;e.selector=e.parsedSelector;Nd(e);e.selector=e.l=yd(f,e,f.i,void 0,void 0)}N&&""===c&&(we(b),b.g&&b.g.transformRule(e))});N?a.textContent=O(d):this.o.B.rules.push(d)}};n.getComputedStyleValue=function(a,b){var c;N||(c=(W(a)||W(Be(this,a))).A[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};
n.za=function(a,b){var c=nd(a).getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===T.g){c=d[e+1];break}}}c&&b.push(T.g,c);N||(c=W(a))&&c.u&&b.push(de.g,c.u);md(a,b.join(" "))};n.oa=function(a){return W(a)};n.ya=function(a,b){U(a,b)};n.Ba=function(a,b){U(a,b,!0)};n.xa=function(a){return ke(a)};n.qa=function(a){return je(a)};Y.prototype.flush=Y.prototype.flush;Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;
Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.za;Y.prototype._styleInfoForNode=Y.prototype.oa;Y.prototype.transformCustomStyleForDocument=Y.prototype.ga;Y.prototype.getStyleAst=Y.prototype.ra;Y.prototype.styleAstToString=Y.prototype.Aa;Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;
Y.prototype.scopeNode=Y.prototype.ya;Y.prototype.unscopeNode=Y.prototype.Ba;Y.prototype.scopeForNode=Y.prototype.xa;Y.prototype.currentScopeForNode=Y.prototype.qa;Y.prototype.prepareAdoptedCssText=Y.prototype.va;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return L}},nativeCss:{get:function(){return N}}});var Z=new Y,Ce,De;window.ShadyCSS&&(Ce=window.ShadyCSS.ApplyShim,De=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:N,nativeShadow:L,cssBuild:Yc,disableRuntime:M};Ce&&(window.ShadyCSS.ApplyShim=Ce);De&&(window.ShadyCSS.CustomStyleInterface=De);var Ee=window.document;window.WebComponents=window.WebComponents||{};function Fe(){window.WebComponents.ready=!0;window.document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))}function Ge(){Fe();Ee.removeEventListener("readystatechange",Ge)}"loading"!==Ee.readyState?Fe():Ee.addEventListener("readystatechange",Ge);}).call(this);

//# sourceMappingURL=webcomponents-sd.js.map
