/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';(function(b){function a(d,h){if("function"===typeof window.CustomEvent)return new CustomEvent(d,h);var k=document.createEvent("CustomEvent");k.initCustomEvent(d,!!h.bubbles,!!h.cancelable,h.detail);return k}function c(d){if(S)return d.ownerDocument!==document?d.ownerDocument:null;var h=d.__importDoc;if(!h&&d.parentNode){h=d.parentNode;if("function"===typeof h.closest)h=h.closest("link[rel=import]");else for(;!m(h)&&(h=h.parentNode););d.__importDoc=h}return h}function f(d){var h=v(document,
"link[rel=import]:not([import-dependency])"),k=h.length;k?x(h,function(p){return l(p,function(){0===--k&&d()})}):d()}function e(d){function h(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",h),d())}document.addEventListener("readystatechange",h);h()}function g(d){e(function(){return f(function(){return d&&d()})})}function l(d,h){if(d.__loaded)h&&h();else if("script"===d.localName&&!d.src||"style"===d.localName&&!d.firstChild||"style"===d.localName&&
"http://www.w3.org/2000/svg"===d.namespaceURI)d.__loaded=!0,h&&h();else{var k=function(p){d.removeEventListener(p.type,k);d.__loaded=!0;h&&h()};d.addEventListener("load",k);"style"===d.localName&&(T||J)||d.addEventListener("error",k)}}function m(d){return d.nodeType===Node.ELEMENT_NODE&&"link"===d.localName&&"import"===d.rel}function n(){var d=this;this.g={};this.h=0;this.i=new MutationObserver(function(h){return d.B(h)});this.i.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}
function r(d){x(v(d,"template"),function(h){h instanceof HTMLTemplateElement&&(x(v(h.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]'),function(k){var p=document.createElement("script");x(k.attributes,function(t){return p.setAttribute(t.name,t.value)});p.textContent=k.textContent;k.parentNode.replaceChild(p,k)}),r(h.content))})}function v(d,h){return d.childNodes.length?d.querySelectorAll(h):Ja}function x(d,h,k){var p=d?d.length:
0,t=k?-1:1;for(k=k?p-1:0;k<p&&0<=k;k+=t)h(d[k],k)}var E=document.createElement("link"),S="import"in E,Ja=E.querySelectorAll("*"),U=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return U||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var Ka=/(url\()([^)]*)(\))/g,La=/(@import[\s]+(?!url\())([^;]*)(;)/g,Ma=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,A={L:function(d,h){d.href&&d.setAttribute("href",
A.s(d.getAttribute("href"),h));d.src&&d.setAttribute("src",A.s(d.getAttribute("src"),h));if("style"===d.localName){var k=A.F(d.textContent,h,Ka);d.textContent=A.F(k,h,La)}},F:function(d,h,k){return d.replace(k,function(p,t,q,u){p=q.replace(/["']/g,"");h&&(p=A.s(p,h));return t+"'"+p+"'"+u})},s:function(d,h){if(void 0===A.u){A.u=!1;try{var k=new URL("b","http://a");k.pathname="c%20d";A.u="http://a/c%20d"===k.href}catch(p){}}if(A.u)return(new URL(d,h)).href;k=A.J;k||(k=document.implementation.createHTMLDocument("temp"),
A.J=k,k.D=k.createElement("base"),k.head.appendChild(k.D),k.C=k.createElement("a"));k.D.href=h;k.C.href=d;return k.C.href||d}},ha={async:!0,load:function(d,h,k){if(d)if(d.match(/^data:/)){d=d.split(",");var p=d[1];p=-1<d[0].indexOf(";base64")?atob(p):decodeURIComponent(p);h(p)}else{var t=new XMLHttpRequest;t.open("GET",d,ha.async);t.onerror=function(){k(null)};t.onload=function(){var q,u=null!=(q=t.responseURL||t.getResponseHeader("Location"))?q:void 0;u&&0===u.indexOf("/")&&(u=(location.origin||
location.protocol+"//"+location.host)+u);q=t.response||t.responseText;304===t.status||0===t.status||200<=t.status&&300>t.status?h(q,u):k(q)};t.send()}else k("error: href must be specified")}},T=/Trident/.test(navigator.userAgent),J=/Edge\/\d./i.test(navigator.userAgent);n.prototype.loadImports=function(d){var h=this;d=v(d,"link[rel=import]");x(d,function(k){return h.l(k)})};n.prototype.l=function(d){var h=this,k=d.href;if(void 0!==this.g[k]){var p=this.g[k];p&&p.__loaded&&(d.__import=p,this.j(d))}else this.h++,
this.g[k]="pending",ha.load(k,function(t,q){t=h.G(t,q||k);h.g[k]=t;h.h--;h.loadImports(t);h.m()},function(){h.g[k]=null;h.h--;h.m()})};n.prototype.G=function(d,h){var k=this;if(!d)return document.createDocumentFragment();if(T||J)d=d.replace(Ma,function(q,u,K){return-1===q.indexOf("type=")?u+" type=import-disable "+K:q});var p=document.createElement("template");p.innerHTML=d;if(p.content)d=p.content,r(d);else for(d=document.createDocumentFragment();p.firstChild;)d.appendChild(p.firstChild);if(p=d.querySelector("base"))h=
A.s(p.getAttribute("href"),h),p.removeAttribute("href");p=v(d,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]');var t=0;x(p,function(q){l(q);A.L(q,h);if("style"===q.localName&&k.o(q)){var u=k.v(q);l(u);q.parentNode.replaceChild(u,q);q=u}q.setAttribute("import-dependency","");if("script"===q.localName&&!q.src&&q.textContent){if("module"===
q.type)throw Error("Inline module scripts are not supported in HTML Imports.");q.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(q.textContent+("\n//# sourceURL="+h+(t?"-"+t:"")+".js\n")));q.textContent="";t++}});return d};n.prototype.o=function(d){return J&&-1<d.textContent.indexOf("@import")};n.prototype.v=function(d){var h=d.ownerDocument.createElement("style");h.textContent=d.textContent;x(d.attributes,function(k){return h.setAttribute(k.name,k.value)});return h};n.prototype.m=
function(){var d=this;if(!this.h){this.i.disconnect();this.flatten(document);var h=!1,k=!1,p=function(){k&&h&&(d.loadImports(document),d.h||(d.i.observe(document.head,{childList:!0,subtree:!0}),d.A()))};this.I(function(){k=!0;p()});this.H(function(){h=!0;p()})}};n.prototype.flatten=function(d){var h=this;d=v(d,"link[rel=import]");x(d,function(k){var p=h.g[k.href];(k.__import=p)&&p.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(h.g[k.href]=k,k.readyState="loading",k.__import=k,h.flatten(p),k.appendChild(p))})};
n.prototype.H=function(d){function h(t){if(t<p){var q=k[t],u=document.createElement("script");q.removeAttribute("import-dependency");x(q.attributes,function(K){return u.setAttribute(K.name,K.value)});U=u;q.parentNode.replaceChild(u,q);l(u,function(){U=null;h(t+1)})}else d()}var k=v(document,"script[import-dependency]"),p=k.length;h(0)};n.prototype.I=function(d){var h=this,k=v(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),p=k.length;if(p){var t=(T||J)&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");
x(k,function(q){t&&h.o(q)&&q.ownerDocument.defaultView!==window.top&&(q.__loaded=!0);l(q,function(){q.removeAttribute("import-dependency");0===--p&&d()});if(t&&q.parentNode!==document.head){var u=document.createElement(q.localName);u.__appliedElement=q;u.setAttribute("type","import-placeholder");q.parentNode.insertBefore(u,q.nextSibling);for(u=c(q);u&&c(u);)u=c(u);u.parentNode!==document.head&&(u=null);document.head.insertBefore(q,u);q.removeAttribute("type")}})}else d()};n.prototype.A=function(){var d=
this,h=v(document,"link[rel=import]");x(h,function(k){return d.j(k)},!0)};n.prototype.j=function(d){d.__loaded||(d.__loaded=!0,d.import&&(d.import.readyState="complete"),d.dispatchEvent(a(d.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};n.prototype.B=function(d){var h=this;x(d,function(k){return x(k.addedNodes,function(p){p&&p.nodeType===Node.ELEMENT_NODE&&(m(p)?h.l(p):h.loadImports(p))})})};var V=null;if(S)E=v(document,"link[rel=import]"),x(E,function(d){d.import&&"loading"===
d.import.readyState||(d.__loaded=!0)}),E=function(d){d=d.target;m(d)&&(d.__loaded=!0)},document.addEventListener("load",E,!0),document.addEventListener("error",E,!0);else{var I=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!I||I.configurable?Node:Element).prototype,"baseURI",{get:function(){var d=m(this)?this:c(this);return d?d.href:I&&I.get?I.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,
"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});e(function(){V=new n})}g(function(){return document.dispatchEvent(a("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});b.useNative=S;b.whenReady=g;b.importForElement=c;b.loadImports=function(d){V&&V.loadImports(d)}})(window.HTMLImports=window.HTMLImports||{});var aa=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function ba(b){var a=aa.has(b);b=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(b);return!a&&b}function w(b){var a=b.isConnected;if(void 0!==a)return a;for(;b&&!(b.__CE_isImportDocument||b instanceof Document);)b=b.parentNode||(window.ShadowRoot&&b instanceof ShadowRoot?b.host:void 0);return!(!b||!(b.__CE_isImportDocument||b instanceof Document))}
function y(b,a){for(;a&&a!==b&&!a.nextSibling;)a=a.parentNode;return a&&a!==b?a.nextSibling:null}
function z(b,a,c){c=void 0===c?new Set:c;for(var f=b;f;){if(f.nodeType===Node.ELEMENT_NODE){var e=f;a(e);var g=e.localName;if("link"===g&&"import"===e.getAttribute("rel")){f=e.import;if(f instanceof Node&&!c.has(f))for(c.add(f),f=f.firstChild;f;f=f.nextSibling)z(f,a,c);f=y(b,e);continue}else if("template"===g){f=y(b,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)z(e,a,c)}f=f.firstChild?f.firstChild:y(b,f)}}function B(b,a,c){b[a]=c};function C(){this.g=new Map;this.j=new Map;this.i=[];this.h=!1}function ca(b,a,c){b.g.set(a,c);b.j.set(c.constructorFunction,c)}function da(b,a){b.h=!0;b.i.push(a)}function D(b,a){b.h&&z(a,function(c){return F(b,c)})}function F(b,a){if(b.h&&!a.__CE_patched){a.__CE_patched=!0;for(var c=0;c<b.i.length;c++)b.i[c](a)}}function G(b,a){var c=[];z(a,function(e){return c.push(e)});for(a=0;a<c.length;a++){var f=c[a];1===f.__CE_state?b.connectedCallback(f):H(b,f)}}
function L(b,a){var c=[];z(a,function(e){return c.push(e)});for(a=0;a<c.length;a++){var f=c[a];1===f.__CE_state&&b.disconnectedCallback(f)}}
function M(b,a,c){c=void 0===c?{}:c;var f=c.M||new Set,e=c.upgrade||function(l){return H(b,l)},g=[];z(a,function(l){if("link"===l.localName&&"import"===l.getAttribute("rel")){var m=l.import;m instanceof Node&&(m.__CE_isImportDocument=!0,m.__CE_hasRegistry=!0);m&&"complete"===m.readyState?m.__CE_documentLoadHandled=!0:l.addEventListener("load",function(){var n=l.import;if(!n.__CE_documentLoadHandled){n.__CE_documentLoadHandled=!0;var r=new Set(f);r.delete(n);M(b,n,{M:r,upgrade:e})}})}else g.push(l)},
f);if(b.h)for(a=0;a<g.length;a++)F(b,g[a]);for(a=0;a<g.length;a++)e(g[a])}
function H(b,a){if(void 0===a.__CE_state){var c=a.ownerDocument;if(c.defaultView||c.__CE_isImportDocument&&c.__CE_hasRegistry)if(c=b.g.get(a.localName)){c.constructionStack.push(a);var f=c.constructorFunction;try{try{if(new f!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(l){throw a.__CE_state=2,l;}a.__CE_state=1;a.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,f=0;f<c.length;f++){var e=
c[f],g=a.getAttribute(e);null!==g&&b.attributeChangedCallback(a,e,null,g,null)}w(a)&&b.connectedCallback(a)}}}C.prototype.connectedCallback=function(b){var a=b.__CE_definition;a.connectedCallback&&a.connectedCallback.call(b)};C.prototype.disconnectedCallback=function(b){var a=b.__CE_definition;a.disconnectedCallback&&a.disconnectedCallback.call(b)};
C.prototype.attributeChangedCallback=function(b,a,c,f,e){var g=b.__CE_definition;g.attributeChangedCallback&&-1<g.observedAttributes.indexOf(a)&&g.attributeChangedCallback.call(b,a,c,f,e)};function ea(b){var a=document;this.i=b;this.g=a;this.h=void 0;M(this.i,this.g);"loading"===this.g.readyState&&(this.h=new MutationObserver(this.j.bind(this)),this.h.observe(this.g,{childList:!0,subtree:!0}))}function fa(b){b.h&&b.h.disconnect()}ea.prototype.j=function(b){var a=this.g.readyState;"interactive"!==a&&"complete"!==a||fa(this);for(a=0;a<b.length;a++)for(var c=b[a].addedNodes,f=0;f<c.length;f++)M(this.i,c[f])};function ia(){var b=this;this.h=this.g=void 0;this.i=new Promise(function(a){b.h=a;b.g&&a(b.g)})}function ja(b){if(b.g)throw Error("Already resolved.");b.g=void 0;b.h&&b.h(void 0)};function N(b){this.i=!1;this.g=b;this.m=new Map;this.j=function(a){return a()};this.h=!1;this.l=[];this.A=new ea(b)}
N.prototype.o=function(b,a){var c=this;if(!(a instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!ba(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(this.g.g.get(b))throw Error("A custom element with name '"+b+"' has already been defined.");if(this.i)throw Error("A custom element is already being defined.");this.i=!0;try{var f=function(v){var x=e[v];if(void 0!==x&&!(x instanceof Function))throw Error("The '"+v+"' callback must be a function.");
return x},e=a.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var g=f("connectedCallback");var l=f("disconnectedCallback");var m=f("adoptedCallback");var n=f("attributeChangedCallback");var r=a.observedAttributes||[]}catch(v){return}finally{this.i=!1}a={localName:b,constructorFunction:a,connectedCallback:g,disconnectedCallback:l,adoptedCallback:m,attributeChangedCallback:n,observedAttributes:r,constructionStack:[]};ca(this.g,
b,a);this.l.push(a);this.h||(this.h=!0,this.j(function(){return ka(c)}))};N.prototype.upgrade=function(b){M(this.g,b)};
function ka(b){if(!1!==b.h){b.h=!1;for(var a=b.l,c=[],f=new Map,e=0;e<a.length;e++)f.set(a[e].localName,[]);M(b.g,document,{upgrade:function(m){if(void 0===m.__CE_state){var n=m.localName,r=f.get(n);r?r.push(m):b.g.g.get(n)&&c.push(m)}}});for(e=0;e<c.length;e++)H(b.g,c[e]);for(;0<a.length;){var g=a.shift();e=g.localName;g=f.get(g.localName);for(var l=0;l<g.length;l++)H(b.g,g[l]);(e=b.m.get(e))&&ja(e)}}}N.prototype.get=function(b){if(b=this.g.g.get(b))return b.constructorFunction};
N.prototype.v=function(b){if(!ba(b))return Promise.reject(new SyntaxError("'"+b+"' is not a valid custom element name."));var a=this.m.get(b);if(a)return a.i;a=new ia;this.m.set(b,a);this.g.g.get(b)&&!this.l.some(function(c){return c.localName===b})&&ja(a);return a.i};N.prototype.B=function(b){fa(this.A);var a=this.j;this.j=function(c){return b(function(){return a(c)})}};window.CustomElementRegistry=N;N.prototype.define=N.prototype.o;N.prototype.upgrade=N.prototype.upgrade;N.prototype.get=N.prototype.get;
N.prototype.whenDefined=N.prototype.v;N.prototype.polyfillWrapFlushCallback=N.prototype.B;var la=window.Document.prototype.createElement,ma=window.Document.prototype.createElementNS,na=window.Document.prototype.importNode,oa=window.Document.prototype.prepend,pa=window.Document.prototype.append,qa=window.DocumentFragment.prototype.prepend,ra=window.DocumentFragment.prototype.append,sa=window.Node.prototype.cloneNode,O=window.Node.prototype.appendChild,ta=window.Node.prototype.insertBefore,P=window.Node.prototype.removeChild,ua=window.Node.prototype.replaceChild,Q=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),va=window.Element.prototype.attachShadow,wa=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),xa=window.Element.prototype.getAttribute,ya=window.Element.prototype.setAttribute,za=window.Element.prototype.removeAttribute,R=window.Element.prototype.getAttributeNS,Aa=window.Element.prototype.setAttributeNS,Ba=window.Element.prototype.removeAttributeNS,Ca=window.Element.prototype.insertAdjacentElement,Da=window.Element.prototype.insertAdjacentHTML,Ea=window.Element.prototype.prepend,
Fa=window.Element.prototype.append,Ga=window.Element.prototype.before,Ha=window.Element.prototype.after,Ia=window.Element.prototype.replaceWith,Na=window.Element.prototype.remove,Oa=window.HTMLElement,Pa=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),Qa=window.HTMLElement.prototype.insertAdjacentElement,Ra=window.HTMLElement.prototype.insertAdjacentHTML;var Sa=new function(){};function Ta(){var b=W;window.HTMLElement=function(){function a(){var c=this.constructor,f=b.j.get(c);if(!f)throw Error("The custom element being constructed was not registered with `customElements`.");var e=f.constructionStack;if(0===e.length)return e=la.call(document,f.localName),Object.setPrototypeOf(e,c.prototype),e.__CE_state=1,e.__CE_definition=f,F(b,e),e;f=e.length-1;var g=e[f];if(g===Sa)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
e[f]=Sa;Object.setPrototypeOf(g,c.prototype);F(b,g);return g}a.prototype=Oa.prototype;Object.defineProperty(a.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:a});return a}()};function Ua(b,a,c){function f(e){return function(g){for(var l=[],m=0;m<arguments.length;++m)l[m]=arguments[m];m=[];for(var n=[],r=0;r<l.length;r++){var v=l[r];v instanceof Element&&w(v)&&n.push(v);if(v instanceof DocumentFragment)for(v=v.firstChild;v;v=v.nextSibling)m.push(v);else m.push(v)}e.apply(this,l);for(l=0;l<n.length;l++)L(b,n[l]);if(w(this))for(l=0;l<m.length;l++)n=m[l],n instanceof Element&&G(b,n)}}void 0!==c.prepend&&B(a,"prepend",f(c.prepend));void 0!==c.append&&B(a,"append",f(c.append))}
;function Va(){var b=W;B(Document.prototype,"createElement",function(a){if(this.__CE_hasRegistry){var c=b.g.get(a);if(c)return new c.constructorFunction}a=la.call(this,a);F(b,a);return a});B(Document.prototype,"importNode",function(a,c){a=na.call(this,a,!!c);this.__CE_hasRegistry?M(b,a):D(b,a);return a});B(Document.prototype,"createElementNS",function(a,c){if(this.__CE_hasRegistry&&(null===a||"http://www.w3.org/1999/xhtml"===a)){var f=b.g.get(c);if(f)return new f.constructorFunction}a=ma.call(this,
a,c);F(b,a);return a});Ua(b,Document.prototype,{prepend:oa,append:pa})};function Wa(){function b(c,f){Object.defineProperty(c,"textContent",{enumerable:f.enumerable,configurable:!0,get:f.get,set:function(e){if(this.nodeType===Node.TEXT_NODE)f.set.call(this,e);else{var g=void 0;if(this.firstChild){var l=this.childNodes,m=l.length;if(0<m&&w(this)){g=Array(m);for(var n=0;n<m;n++)g[n]=l[n]}}f.set.call(this,e);if(g)for(e=0;e<g.length;e++)L(a,g[e])}}})}var a=W;B(Node.prototype,"insertBefore",function(c,f){if(c instanceof DocumentFragment){var e=Array.prototype.slice.apply(c.childNodes);
c=ta.call(this,c,f);if(w(this))for(f=0;f<e.length;f++)G(a,e[f]);return c}e=w(c);f=ta.call(this,c,f);e&&L(a,c);w(this)&&G(a,c);return f});B(Node.prototype,"appendChild",function(c){if(c instanceof DocumentFragment){var f=Array.prototype.slice.apply(c.childNodes);c=O.call(this,c);if(w(this))for(var e=0;e<f.length;e++)G(a,f[e]);return c}f=w(c);e=O.call(this,c);f&&L(a,c);w(this)&&G(a,c);return e});B(Node.prototype,"cloneNode",function(c){c=sa.call(this,!!c);this.ownerDocument.__CE_hasRegistry?M(a,c):
D(a,c);return c});B(Node.prototype,"removeChild",function(c){var f=w(c),e=P.call(this,c);f&&L(a,c);return e});B(Node.prototype,"replaceChild",function(c,f){if(c instanceof DocumentFragment){var e=Array.prototype.slice.apply(c.childNodes);c=ua.call(this,c,f);if(w(this))for(L(a,f),f=0;f<e.length;f++)G(a,e[f]);return c}e=w(c);var g=ua.call(this,c,f),l=w(this);l&&L(a,f);e&&L(a,c);l&&G(a,c);return g});Q&&Q.get?b(Node.prototype,Q):da(a,function(c){b(c,{enumerable:!0,configurable:!0,get:function(){for(var f=
[],e=0;e<this.childNodes.length;e++)f.push(this.childNodes[e].textContent);return f.join("")},set:function(f){for(;this.firstChild;)P.call(this,this.firstChild);O.call(this,document.createTextNode(f))}})})};function Xa(b){function a(f){return function(e){for(var g=[],l=0;l<arguments.length;++l)g[l]=arguments[l];l=[];for(var m=[],n=0;n<g.length;n++){var r=g[n];r instanceof Element&&w(r)&&m.push(r);if(r instanceof DocumentFragment)for(r=r.firstChild;r;r=r.nextSibling)l.push(r);else l.push(r)}f.apply(this,g);for(g=0;g<m.length;g++)L(b,m[g]);if(w(this))for(g=0;g<l.length;g++)m=l[g],m instanceof Element&&G(b,m)}}var c=Element.prototype;void 0!==Ga&&B(c,"before",a(Ga));void 0!==Ga&&B(c,"after",a(Ha));void 0!==
Ia&&B(c,"replaceWith",function(f){for(var e=[],g=0;g<arguments.length;++g)e[g]=arguments[g];g=[];for(var l=[],m=0;m<e.length;m++){var n=e[m];n instanceof Element&&w(n)&&l.push(n);if(n instanceof DocumentFragment)for(n=n.firstChild;n;n=n.nextSibling)g.push(n);else g.push(n)}m=w(this);Ia.apply(this,e);for(e=0;e<l.length;e++)L(b,l[e]);if(m)for(L(b,this),e=0;e<g.length;e++)l=g[e],l instanceof Element&&G(b,l)});void 0!==Na&&B(c,"remove",function(){var f=w(this);Na.call(this);f&&L(b,this)})};function Ya(){function b(e,g){Object.defineProperty(e,"innerHTML",{enumerable:g.enumerable,configurable:!0,get:g.get,set:function(l){var m=this,n=void 0;w(this)&&(n=[],z(this,function(x){x!==m&&n.push(x)}));g.set.call(this,l);if(n)for(var r=0;r<n.length;r++){var v=n[r];1===v.__CE_state&&f.disconnectedCallback(v)}this.ownerDocument.__CE_hasRegistry?M(f,this):D(f,this);return l}})}function a(e,g){B(e,"insertAdjacentElement",function(l,m){var n=w(m);l=g.call(this,l,m);n&&L(f,m);w(l)&&G(f,m);return l})}
function c(e,g){function l(m,n){for(var r=[];m!==n;m=m.nextSibling)r.push(m);for(n=0;n<r.length;n++)M(f,r[n])}B(e,"insertAdjacentHTML",function(m,n){m=m.toLowerCase();if("beforebegin"===m){var r=this.previousSibling;g.call(this,m,n);l(r||this.parentNode.firstChild,this)}else if("afterbegin"===m)r=this.firstChild,g.call(this,m,n),l(this.firstChild,r);else if("beforeend"===m)r=this.lastChild,g.call(this,m,n),l(r||this.firstChild,null);else if("afterend"===m)r=this.nextSibling,g.call(this,m,n),l(this.nextSibling,
r);else throw new SyntaxError("The value provided ("+String(m)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");})}var f=W;va&&B(Element.prototype,"attachShadow",function(e){return this.__CE_shadowRoot=e=va.call(this,e)});wa&&wa.get?b(Element.prototype,wa):Pa&&Pa.get?b(HTMLElement.prototype,Pa):da(f,function(e){b(e,{enumerable:!0,configurable:!0,get:function(){return sa.call(this,!0).innerHTML},set:function(g){var l="template"===this.localName,m=l?this.content:this,n=ma.call(document,
this.namespaceURI,this.localName);for(n.innerHTML=g;0<m.childNodes.length;)P.call(m,m.childNodes[0]);for(g=l?n.content:n;0<g.childNodes.length;)O.call(m,g.childNodes[0])}})});B(Element.prototype,"setAttribute",function(e,g){if(1!==this.__CE_state)return ya.call(this,e,g);var l=xa.call(this,e);ya.call(this,e,g);g=xa.call(this,e);f.attributeChangedCallback(this,e,l,g,null)});B(Element.prototype,"setAttributeNS",function(e,g,l){if(1!==this.__CE_state)return Aa.call(this,e,g,l);var m=R.call(this,e,g);
Aa.call(this,e,g,l);l=R.call(this,e,g);f.attributeChangedCallback(this,g,m,l,e)});B(Element.prototype,"removeAttribute",function(e){if(1!==this.__CE_state)return za.call(this,e);var g=xa.call(this,e);za.call(this,e);null!==g&&f.attributeChangedCallback(this,e,g,null,null)});B(Element.prototype,"removeAttributeNS",function(e,g){if(1!==this.__CE_state)return Ba.call(this,e,g);var l=R.call(this,e,g);Ba.call(this,e,g);var m=R.call(this,e,g);l!==m&&f.attributeChangedCallback(this,g,l,m,e)});Qa?a(HTMLElement.prototype,
Qa):Ca?a(Element.prototype,Ca):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");Ra?c(HTMLElement.prototype,Ra):Da?c(Element.prototype,Da):console.warn("Custom Elements: `Element#insertAdjacentHTML` was not patched.");Ua(f,Element.prototype,{prepend:Ea,append:Fa});Xa(f)};var X=window.customElements;if(!X||X.forcePolyfill||"function"!=typeof X.define||"function"!=typeof X.get){var W=new C;Ta();Va();Ua(W,DocumentFragment.prototype,{prepend:qa,append:ra});Wa();Ya();document.__CE_hasRegistry=!0;var customElements=new N(W);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var Za=window.customElements,Y=window.HTMLImports,$a=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(Za&&Za.polyfillWrapFlushCallback){var Z,ab=function(){if(Z){$a.K&&$a.K(window.document);var b=Z;Z=null;b();return!0}},bb=Y.whenReady;Za.polyfillWrapFlushCallback(function(b){Z=b;bb(ab)});Y.whenReady=function(b){bb(function(){ab()?Y.whenReady(b):b()})}}
Y.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var cb=document.createElement("style");cb.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var db=document.querySelector("head");db.insertBefore(cb,db.firstChild);/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
}).call(this);

//# sourceMappingURL=webcomponents-hi-ce.js.map
