/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';(function(m){function H(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function v(a){if(C)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!y(b)&&(b=b.parentNode););a.__importDoc=b}return b}function Q(a){var b=p(document,
"link[rel=import]:not([import-dependency])"),c=b.length;c?h(b,function(d){return w(d,function(){0===--c&&a()})}):a()}function I(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function J(a){I(function(){return Q(function(){return a&&a()})})}function w(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild||"style"===a.localName&&
"http://www.w3.org/2000/svg"===a.namespaceURI)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);"style"===a.localName&&(D||z)||a.addEventListener("error",c)}}function y(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function k(){var a=this;this.g={};this.h=0;this.l=new MutationObserver(function(b){return a.M(b)});this.l.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}
function K(a){h(p(a,"template"),function(b){b instanceof HTMLTemplateElement&&(h(p(b.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]'),function(c){var d=document.createElement("script");h(c.attributes,function(f){return d.setAttribute(f.name,f.value)});d.textContent=c.textContent;c.parentNode.replaceChild(d,c)}),K(b.content))})}function p(a,b){return a.childNodes.length?a.querySelectorAll(b):R}function h(a,b,c){var d=a?a.length:
0,f=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=f)b(a[c],c)}var r=document.createElement("link"),C="import"in r,R=r.querySelectorAll("*"),E=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return E||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var S=/(url\()([^)]*)(\))/g,T=/(@import[\s]+(?!url\())([^;]*)(;)/g,U=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,l={I:function(a,b){a.href&&a.setAttribute("href",
l.i(a.getAttribute("href"),b));a.src&&a.setAttribute("src",l.i(a.getAttribute("src"),b));if("style"===a.localName){var c=l.B(a.textContent,b,S);a.textContent=l.B(c,b,T)}},B:function(a,b,c){return a.replace(c,function(d,f,e,g){d=e.replace(/["']/g,"");b&&(d=l.i(d,b));return f+"'"+d+"'"+g})},i:function(a,b){if(void 0===l.j){l.j=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";l.j="http://a/c%20d"===c.href}catch(d){}}if(l.j)return(new URL(a,b)).href;c=l.G;c||(c=document.implementation.createHTMLDocument("temp"),
l.G=c,c.o=c.createElement("base"),c.head.appendChild(c.o),c.m=c.createElement("a"));c.o.href=b;c.m.href=a;return c.m.href||a}},V={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){var d=a.split(","),f=d[1];f=-1<d[0].indexOf(";base64")?atob(f):decodeURIComponent(f);b(f)}else{var e=function(n){n=void 0===n?0:n;return t(0===n).then(function(q){b(q.J,q.O)},function(q){console.error(q);if(2<=n)c();else return g(100*Math.random()*Math.pow(2,n)).then(function(){return e(n+1)})})},g=function(n){return new Promise(function(q){return setTimeout(q,
n)})},t=function(n){var q=null;return fetch(a,{cache:n?"default":"reload"}).then(function(u){if(!u.ok)throw Error("HTTP "+u.status);q=u.url;return u.text()}).then(function(u){return{J:u,N:q}})};e()}else c()}},D=/Trident/.test(navigator.userAgent),z=/Edge\/\d./i.test(navigator.userAgent);k.prototype.loadImports=function(a){var b=this;a=p(a,"link[rel=import]");h(a,function(c){return b.u(c)})};k.prototype.u=function(a){var b=this,c=a.href;if(void 0!==this.g[c]){var d=this.g[c];d&&d.__loaded&&(a.__import=
d,this.s(a))}else this.h++,this.g[c]="pending",V.load(c,function(f,e){f=b.C(f,e||c);b.g[c]=f;b.h--;b.loadImports(f);b.v()},function(){b.g[c]=null;b.h--;b.v()})};k.prototype.C=function(a,b){var c=this;if(!a)return document.createDocumentFragment();if(D||z)a=a.replace(U,function(e,g,t){return-1===e.indexOf("type=")?g+" type=import-disable "+t:e});var d=document.createElement("template");d.innerHTML=a;if(d.content)a=d.content,K(a);else for(a=document.createDocumentFragment();d.firstChild;)a.appendChild(d.firstChild);
if(d=a.querySelector("base"))b=l.i(d.getAttribute("href"),b),d.removeAttribute("href");d=p(a,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]');var f=0;h(d,function(e){w(e);l.I(e,b);if("style"===e.localName&&c.A(e)){var g=c.K(e);w(g);e.parentNode.replaceChild(g,e);e=g}e.setAttribute("import-dependency","");if("script"===
e.localName&&!e.src&&e.textContent){if("module"===e.type)throw Error("Inline module scripts are not supported in HTML Imports.");e.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(e.textContent+("\n//# sourceURL="+b+(f?"-"+f:"")+".js\n")));e.textContent="";f++}});return a};k.prototype.A=function(a){return z&&-1<a.textContent.indexOf("@import")};k.prototype.K=function(a){var b=a.ownerDocument.createElement("style");b.textContent=a.textContent;h(a.attributes,function(c){return b.setAttribute(c.name,
c.value)});return b};k.prototype.v=function(){var a=this;if(!this.h){this.l.disconnect();this.flatten(document);var b=!1,c=!1,d=function(){c&&b&&(a.loadImports(document),a.h||(a.l.observe(document.head,{childList:!0,subtree:!0}),a.L()))};this.F(function(){c=!0;d()});this.D(function(){b=!0;d()})}};k.prototype.flatten=function(a){var b=this;a=p(a,"link[rel=import]");h(a,function(c){var d=b.g[c.href];(c.__import=d)&&d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.g[c.href]=c,c.readyState="loading",c.__import=
c,b.flatten(d),c.appendChild(d))})};k.prototype.D=function(a){function b(f){if(f<d){var e=c[f],g=document.createElement("script");e.removeAttribute("import-dependency");h(e.attributes,function(t){return g.setAttribute(t.name,t.value)});E=g;e.parentNode.replaceChild(g,e);w(g,function(){E=null;b(f+1)})}else a()}var c=p(document,"script[import-dependency]"),d=c.length;b(0)};k.prototype.F=function(a){var b=this,c=p(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),d=c.length;
if(d){var f=(D||z)&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");h(c,function(e){f&&b.A(e)&&e.ownerDocument.defaultView!==window.top&&(e.__loaded=!0);w(e,function(){e.removeAttribute("import-dependency");0===--d&&a()});if(f&&e.parentNode!==document.head){var g=document.createElement(e.localName);g.__appliedElement=e;g.setAttribute("type","import-placeholder");e.parentNode.insertBefore(g,e.nextSibling);for(g=v(e);g&&v(g);)g=v(g);g.parentNode!==document.head&&(g=null);
document.head.insertBefore(e,g);e.removeAttribute("type")}})}else a()};k.prototype.L=function(){var a=this,b=p(document,"link[rel=import]");h(b,function(c){return a.s(c)},!0)};k.prototype.s=function(a){a.__loaded||(a.__loaded=!0,a.import&&(a.import.readyState="complete"),a.dispatchEvent(H(a.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};k.prototype.M=function(a){var b=this;h(a,function(c){return h(c.addedNodes,function(d){d&&d.nodeType===Node.ELEMENT_NODE&&(y(d)?b.u(d):b.loadImports(d))})})};
var F=null;if(C)r=p(document,"link[rel=import]"),h(r,function(a){a.import&&"loading"===a.import.readyState||(a.__loaded=!0)}),r=function(a){a=a.target;y(a)&&(a.__loaded=!0)},document.addEventListener("load",r,!0),document.addEventListener("error",r,!0);else{var x=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!x||x.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=y(this)?this:v(this);return a?a.href:x&&x.get?x.get.call(this):(document.querySelector("base")||
window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});I(function(){F=new k})}J(function(){return document.dispatchEvent(H("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});m.useNative=C;m.whenReady=J;m.importForElement=v;m.loadImports=function(a){F&&F.loadImports(a)}})(window.HTMLImports=window.HTMLImports||{});/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var A=window.customElements,B=window.HTMLImports,G=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(A&&A.polyfillWrapFlushCallback){var L,M=function(){if(L){G.H&&G.H(window.document);var m=L;L=null;m();return!0}},N=B.whenReady;A.polyfillWrapFlushCallback(function(m){L=m;N(M)});B.whenReady=function(m){N(function(){M()?B.whenReady(m):m()})}}
B.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var O=document.createElement("style");O.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var P=document.querySelector("head");P.insertBefore(O,P.firstChild);/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
}).call(this);

//# sourceMappingURL=webcomponents-hi.js.map
