/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);
function fa(){this.ga=this.root=null;this.U=!1;this.D=this.R=this.Z=this.assignedSlot=this.assignedNodes=this.I=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.K=void 0;this.ca=this.da=!1;this.P={}}fa.prototype.toJSON=function(){return{}};function q(a){a.__shady||(a.__shady=new fa);return a.__shady}function r(a){return a&&a.__shady};var t=window.ShadyDOM||{};t.ua=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ha=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");t.o=!!(ha&&ha.configurable&&ha.get);t.$=t.force||!t.ua;t.J=t.noPatch||!1;t.fa=t.preferPerformance;function u(a){return(a=r(a))&&void 0!==a.firstChild}function v(a){return"ShadyRoot"===a.oa}function ia(a){return(a=(a=r(a))&&a.root)&&ja(a)}
var w=Element.prototype,la=w.matches||w.matchesSelector||w.mozMatchesSelector||w.msMatchesSelector||w.oMatchesSelector||w.webkitMatchesSelector,ma=document.createTextNode(""),na=0,oa=[];(new MutationObserver(function(){for(;oa.length;)try{oa.shift()()}catch(a){throw ma.textContent=na++,a;}})).observe(ma,{characterData:!0});function pa(a){oa.push(a);ma.textContent=na++}var qa=!!document.contains;function ra(a,b){for(;b;){if(b==a)return!0;b=b.__shady_parentNode}return!1}
function sa(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(e){return a[e]};a.namedItem=function(e){if("length"!==e&&isNaN(e)&&a[e])return a[e];for(var f=ba(a),g=f.next();!g.done;g=f.next())if(g=g.value,(g.getAttribute("id")||g.getAttribute("name"))==e)return g;return null};return a}
function x(a,b,c,d){c=void 0===c?"":c;for(var e in b){var f=b[e];if(!(d&&0<=d.indexOf(e))){f.configurable=!0;var g=c+e;if(f.value)a[g]=f.value;else try{Object.defineProperty(a,g,f)}catch(h){}}}}function y(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=Object.getOwnPropertyDescriptor(a,c)});return b};var ta=[],ua;function va(a){ua||(ua=!0,pa(wa));ta.push(a)}function wa(){ua=!1;for(var a=!!ta.length;ta.length;)ta.shift()();return a}wa.list=ta;function xa(){this.g=!1;this.addedNodes=[];this.removedNodes=[];this.T=new Set}function ya(a){a.g||(a.g=!0,pa(function(){a.flush()}))}xa.prototype.flush=function(){if(this.g){this.g=!1;var a=this.takeRecords();a.length&&this.T.forEach(function(b){b(a)})}};xa.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function za(a,b){var c=q(a);c.I||(c.I=new xa);c.I.T.add(b);var d=c.I;return{na:b,G:d,pa:a,takeRecords:function(){return d.takeRecords()}}}function Aa(a){var b=a&&a.G;b&&(b.T.delete(a.na),b.T.size||(q(a.pa).I=null))}
function Ba(a,b){var c=b.getRootNode();return a.map(function(d){var e=c===d.target.getRootNode();if(e&&d.addedNodes){if(e=Array.from(d.addedNodes).filter(function(f){return c===f.getRootNode()}),e.length)return d=Object.create(d),Object.defineProperty(d,"addedNodes",{value:e,configurable:!0}),d}else if(e)return d}).filter(function(d){return d})};var Ca=/[&\u00A0"]/g,Da=/[&\u00A0<>]/g;function Ea(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Fa(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Ga=Fa("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Ha=Fa("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function Ia(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g=void 0;e<f&&(g=d[e]);e++){a:{var h=g;var k=a,l=b;switch(h.nodeType){case Node.ELEMENT_NODE:k=h.localName;for(var m="<"+k,p=h.attributes,A=0,ka;ka=p[A];A++)m+=" "+ka.name+'="'+ka.value.replace(Ca,Ea)+'"';m+=">";h=Ga[k]?m:m+Ia(h,l)+"</"+k+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&Ha[k.localName]?h:h.replace(Da,Ea);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var Ja=t.o,Ka={querySelector:function(a){return this.__shady_native_querySelector(a)},querySelectorAll:function(a){return this.__shady_native_querySelectorAll(a)}},La={};function Ma(a){La[a]=function(b){return b["__shady_native_"+a]}}function Na(a,b){x(a,b,"__shady_native_");for(var c in b)Ma(c)}function z(a,b){b=void 0===b?[]:b;for(var c=0;c<b.length;c++){var d=b[c],e=Object.getOwnPropertyDescriptor(a,d);e&&(Object.defineProperty(a,"__shady_native_"+d,e),e.value?Ka[d]||(Ka[d]=e.value):Ma(d))}}
var B=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),C=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),Oa=document.implementation.createHTMLDocument("inert");function Pa(a){for(var b;b=a.__shady_native_firstChild;)a.__shady_native_removeChild(b)}var Qa=["firstElementChild","lastElementChild","children","childElementCount"],Ra=["querySelector","querySelectorAll"];
function Ta(){var a=["dispatchEvent","addEventListener","removeEventListener"];window.EventTarget?z(window.EventTarget.prototype,a):(z(Node.prototype,a),z(Window.prototype,a));Ja?z(Node.prototype,"parentNode firstChild lastChild previousSibling nextSibling childNodes parentElement textContent".split(" ")):Na(Node.prototype,{parentNode:{get:function(){B.currentNode=this;return B.parentNode()}},firstChild:{get:function(){B.currentNode=this;return B.firstChild()}},lastChild:{get:function(){B.currentNode=
this;return B.lastChild()}},previousSibling:{get:function(){B.currentNode=this;return B.previousSibling()}},nextSibling:{get:function(){B.currentNode=this;return B.nextSibling()}},childNodes:{get:function(){var b=[];B.currentNode=this;for(var c=B.firstChild();c;)b.push(c),c=B.nextSibling();return b}},parentElement:{get:function(){C.currentNode=this;return C.parentNode()}},textContent:{get:function(){switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(var b=document.createTreeWalker(this,
NodeFilter.SHOW_TEXT,null,!1),c="",d;d=b.nextNode();)c+=d.nodeValue;return c;default:return this.nodeValue}},set:function(b){if("undefined"===typeof b||null===b)b="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:Pa(this);(0<b.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_native_insertBefore(document.createTextNode(b),void 0);break;default:this.nodeValue=b}}}});z(Node.prototype,"appendChild insertBefore removeChild replaceChild cloneNode contains".split(" "));
a={firstElementChild:{get:function(){C.currentNode=this;return C.firstChild()}},lastElementChild:{get:function(){C.currentNode=this;return C.lastChild()}},children:{get:function(){var b=[];C.currentNode=this;for(var c=C.firstChild();c;)b.push(c),c=C.nextSibling();return sa(b)}},childElementCount:{get:function(){return this.children?this.children.length:0}}};Ja?(z(Element.prototype,Qa),z(Element.prototype,["previousElementSibling","nextElementSibling","innerHTML"]),Object.getOwnPropertyDescriptor(HTMLElement.prototype,
"children")&&z(HTMLElement.prototype,["children"]),Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&z(HTMLElement.prototype,["innerHTML"])):(Na(Element.prototype,a),Na(Element.prototype,{previousElementSibling:{get:function(){C.currentNode=this;return C.previousSibling()}},nextElementSibling:{get:function(){C.currentNode=this;return C.nextSibling()}},innerHTML:{get:function(){return Ia(this,function(b){return b.__shady_native_childNodes})},set:function(b){var c="template"===this.localName?
this.content:this;Pa(c);var d=this.localName||"div";d=this.namespaceURI&&this.namespaceURI!==Oa.namespaceURI?Oa.createElementNS(this.namespaceURI,d):Oa.createElement(d);d.innerHTML=b;for(b="template"===this.localName?d.content:d;d=b.__shady_native_firstChild;)c.__shady_native_insertBefore(d,void 0)}}}));z(Element.prototype,"setAttribute getAttribute hasAttribute removeAttribute focus blur".split(" "));z(Element.prototype,Ra);z(HTMLElement.prototype,["focus","blur","contains"]);Ja&&z(HTMLElement.prototype,
["parentElement","children","innerHTML"]);window.HTMLTemplateElement&&z(window.HTMLTemplateElement.prototype,["innerHTML"]);Ja?z(DocumentFragment.prototype,Qa):Na(DocumentFragment.prototype,a);z(DocumentFragment.prototype,Ra);Ja?(z(Document.prototype,Qa),z(Document.prototype,["activeElement"])):Na(Document.prototype,a);z(Document.prototype,["importNode","getElementById"]);z(Document.prototype,Ra)};var Ua=y({get childNodes(){return this.__shady_childNodes},get firstChild(){return this.__shady_firstChild},get lastChild(){return this.__shady_lastChild},get textContent(){return this.__shady_textContent},set textContent(a){this.__shady_textContent=a},get childElementCount(){return this.__shady_childElementCount},get children(){return this.__shady_children},get firstElementChild(){return this.__shady_firstElementChild},get lastElementChild(){return this.__shady_lastElementChild},get innerHTML(){return this.__shady_innerHTML},
set innerHTML(a){return this.__shady_innerHTML=a},get shadowRoot(){return this.__shady_shadowRoot}}),Va=y({get parentElement(){return this.__shady_parentElement},get parentNode(){return this.__shady_parentNode},get nextSibling(){return this.__shady_nextSibling},get previousSibling(){return this.__shady_previousSibling},get nextElementSibling(){return this.__shady_nextElementSibling},get previousElementSibling(){return this.__shady_previousElementSibling},get className(){return this.__shady_className},
set className(a){return this.__shady_className=a}}),Wa;for(Wa in Ua)Ua[Wa].enumerable=!1;for(var Xa in Va)Va[Xa].enumerable=!1;var Ya=t.o||t.J,Za=Ya?function(){}:function(a){var b=q(a);b.da||(b.da=!0,x(a,Va))},$a=Ya?function(){}:function(a){var b=q(a);b.ca||(b.ca=!0,x(a,Ua))};var ab="__eventWrappers"+Date.now(),bb=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),cb={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},db={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function eb(a){return a instanceof Node?a.__shady_getRootNode():a}function fb(a,b){var c=[],d=a;for(a=eb(a);d;)c.push(d),d=d.__shady_assignedSlot?d.__shady_assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.__shady_parentNode;c[c.length-1]===document&&c.push(window);return c}function gb(a){a.__composedPath||(a.__composedPath=fb(a.target,!0));return a.__composedPath}
function hb(a,b){if(!v)return a;a=fb(a,!0);for(var c=0,d,e=void 0,f,g=void 0;c<b.length;c++)if(d=b[c],f=eb(d),f!==e&&(g=a.indexOf(f),e=f),!v(f)||-1<g)return d}function ib(a){function b(c,d){c=new a(c,d);c.__composed=d&&!!d.composed;return c}b.__proto__=a;b.prototype=a.prototype;return b}var jb={focus:!0,blur:!0};function kb(a){return a.__target!==a.target||a.__relatedTarget!==a.relatedTarget}
function lb(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!kb(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.__immediatePropagationStopped);d++);}
function mb(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];lb(a,d,"capture");if(a.W)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=r(d);f=f&&f.root;if(0===c||f&&f===e)if(lb(a,d,"bubble"),d!==window&&(e=d.__shady_getRootNode()),a.W)break}}
function nb(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],k=h.type,l=h.capture,m=h.once,p=h.passive;if(b===h.node&&c===k&&d===l&&e===m&&f===p)return g}return-1}
function ob(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){if(db[a])return this.__shady_native_addEventListener(a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.X||this,k=b[ab];if(k){if(-1<nb(k,h,a,e,f,g))return}else b[ab]=[];k=function(l){f&&this.__shady_removeEventListener(a,b,c);l.__target||pb(l);if(h!==this){var m=Object.getOwnPropertyDescriptor(l,"currentTarget");
Object.defineProperty(l,"currentTarget",{get:function(){return h},configurable:!0})}l.__previousCurrentTarget=l.currentTarget;if(!v(h)||-1!=l.composedPath().indexOf(h))if(l.composed||-1<l.composedPath().indexOf(h))if(kb(l)&&l.target===l.relatedTarget)l.eventPhase===Event.BUBBLING_PHASE&&l.stopImmediatePropagation();else if(l.eventPhase===Event.CAPTURING_PHASE||l.bubbles||l.target===h||h instanceof Window){var p="function"===d?b.call(h,l):b.handleEvent&&b.handleEvent(l);h!==this&&(m?(Object.defineProperty(l,
"currentTarget",m),m=null):delete l.currentTarget);return p}};b[ab].push({node:h,type:a,capture:e,once:f,passive:g,Ha:k});jb[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][e?"capture":"bubble"].push(k)):this.__shady_native_addEventListener(a,k,c)}}}
function qb(a,b,c){if(b){if(db[a])return this.__shady_native_removeEventListener(a,b,c);if(c&&"object"===typeof c){var d=!!c.capture;var e=!!c.once;var f=!!c.passive}else d=!!c,f=e=!1;var g=c&&c.X||this,h=void 0;var k=null;try{k=b[ab]}catch(l){}k&&(e=nb(k,g,a,d,e,f),-1<e&&(h=k.splice(e,1)[0].Ha,k.length||(b[ab]=void 0)));this.__shady_native_removeEventListener(a,h||b,c);h&&jb[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][d?"capture":"bubble"],h=a.indexOf(h),-1<h&&a.splice(h,1))}}
function rb(){for(var a in jb)window.__shady_native_addEventListener(a,function(b){b.__target||(pb(b),mb(b))},!0)}
var sb=y({get composed(){void 0===this.__composed&&(bb?this.__composed="focusin"===this.type||"focusout"===this.type||bb(this):!1!==this.isTrusted&&(this.__composed=cb[this.type]));return this.__composed||!1},composedPath:function(){this.__composedPath||(this.__composedPath=fb(this.__target,this.composed));return this.__composedPath},get target(){return hb(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.__relatedTarget)return null;this.__relatedTargetComposedPath||
(this.__relatedTargetComposedPath=fb(this.__relatedTarget,!0));return hb(this.currentTarget||this.__previousCurrentTarget,this.__relatedTargetComposedPath)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.W=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.W=this.__immediatePropagationStopped=!0}});
function pb(a){a.__target=a.target;a.__relatedTarget=a.relatedTarget;if(t.o){var b=Object.getPrototypeOf(a);if(!Object.hasOwnProperty(b,"__shady_patchedProto")){var c=Object.create(b);c.__shady_sourceProto=b;x(c,sb);b.__shady_patchedProto=c}a.__proto__=b.__shady_patchedProto}else x(a,sb)}var tb=ib(Event),ub=ib(CustomEvent),vb=ib(MouseEvent);
function wb(){if(!bb&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var b=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.__shady_dispatchEvent(b)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}}var xb=Object.getOwnPropertyNames(Document.prototype).filter(function(a){return"on"===a.substring(0,2)});function yb(a,b){return{index:a,L:[],S:b}}
function zb(a,b,c,d){var e=0,f=0,g=0,h=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,m=0;m<k-g&&Ab(a[--h],c[--l]);)m++;h=m}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=yb(e,0);f<d;)b.L.push(c[f++]);return[b]}if(f==d)return[yb(e,b-e)];k=e;g=f;d=d-g+1;h=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(m=1;m<h;m++)if(a[k+m-1]===c[g+l-1])b[l][m]=
b[l-1][m-1];else{var p=b[l-1][m]+1,A=b[l][m-1]+1;b[l][m]=p<A?p:A}k=b.length-1;g=b[0].length-1;d=b[k][g];for(a=[];0<k||0<g;)0==k?(a.push(2),g--):0==g?(a.push(3),k--):(h=b[k-1][g-1],l=b[k-1][g],m=b[k][g-1],p=l<m?l<h?l:h:m<h?m:h,p==h?(h==d?a.push(0):(a.push(1),d=h),k--,g--):p==l?(a.push(3),k--,d=l):(a.push(2),g--,d=m));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=yb(e,0));b.S++;e++;b.L.push(c[f]);f++;break;case 2:b||(b=yb(e,0));
b.S++;e++;break;case 3:b||(b=yb(e,0)),b.L.push(c[f]),f++}b&&k.push(b);return k}function Ab(a,b){return a===b};function Bb(a,b,c){Za(a);c=c||null;var d=q(a),e=q(b),f=c?q(c):null;d.previousSibling=c?f.previousSibling:b.__shady_lastChild;if(f=r(d.previousSibling))f.nextSibling=a;if(f=r(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function Cb(a,b,c){$a(b);var d=q(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){d=a.__shady_childNodes;for(var e=0;e<d.length;e++)Bb(d[e],b,c);a=q(a);b=void 0!==a.firstChild?null:void 0;a.firstChild=a.lastChild=b;a.childNodes=b}else Bb(a,b,c)}
function Db(a,b){var c=q(a);b=q(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(q(a).nextSibling=d);d&&(q(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function Eb(a){var b=q(a);if(void 0===b.firstChild){b.childNodes=null;var c=b.firstChild=a.__shady_native_firstChild||null;b.lastChild=a.__shady_native_lastChild||null;$a(a);b=c;for(c=void 0;b;b=b.__shady_native_nextSibling){var d=q(b);d.parentNode=a;d.nextSibling=b.__shady_native_nextSibling||null;d.previousSibling=c||null;c=b;Za(b)}}};var Fb=null;function D(){Fb||(Fb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return Fb||null}function Gb(a,b){var c=D();c&&c.unscopeNode(a,b)}function Hb(a,b){var c=D();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;a=a.__shady_childNodes;for(var d=0;c&&d<a.length;d++)c=c&&Hb(a[d],b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}function Ib(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=D();return b?b.currentScopeForNode(a):""}
function Jb(a,b){if(a){a.nodeType===Node.ELEMENT_NODE&&b(a);a=a.__shady_childNodes;for(var c=0,d;c<a.length;c++)d=a[c],d.nodeType===Node.ELEMENT_NODE&&Jb(d,b)}};var Kb=window.document,Lb=t.fa,Mb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),Nb=Mb&&Mb.get;function Ob(a){for(var b;b=a.__shady_firstChild;)a.__shady_removeChild(b)}function Pb(a){var b=r(a);if(b&&void 0!==b.K){b=a.__shady_childNodes;for(var c=0,d=b.length,e=void 0;c<d&&(e=b[c]);c++)Pb(e)}if(a=r(a))a.K=void 0}function Qb(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=r(a))&&b.D)&&b.length?b[0]:Qb(a.__shady_nextSibling));return b}
function Rb(a,b,c){if(a=(a=r(a))&&a.I)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),ya(a)}
var Tb=y({get parentNode(){var a=r(this);a=a&&a.parentNode;return void 0!==a?a:this.__shady_native_parentNode},get firstChild(){var a=r(this);a=a&&a.firstChild;return void 0!==a?a:this.__shady_native_firstChild},get lastChild(){var a=r(this);a=a&&a.lastChild;return void 0!==a?a:this.__shady_native_lastChild},get nextSibling(){var a=r(this);a=a&&a.nextSibling;return void 0!==a?a:this.__shady_native_nextSibling},get previousSibling(){var a=r(this);a=a&&a.previousSibling;return void 0!==a?a:this.__shady_native_previousSibling},
get childNodes(){if(u(this)){var a=r(this);if(!a.childNodes){a.childNodes=[];for(var b=this.__shady_firstChild;b;b=b.__shady_nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=this.__shady_native_childNodes;c.item=function(d){return c[d]};return c},get parentElement(){var a=r(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:this.__shady_native_parentElement},get isConnected(){if(Nb&&Nb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;
var a=this.ownerDocument;if(qa){if(a.__shady_native_contains(this))return!0}else if(a.documentElement&&a.documentElement.__shady_native_contains(this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.__shady_parentNode||(v(a)?a.host:void 0);return!!(a&&a instanceof Document)},get textContent(){if(u(this)){for(var a=[],b=0,c=this.__shady_childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&a.push(d.__shady_textContent);return a.join("")}return this.__shady_native_textContent},set textContent(a){if("undefined"===
typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!u(this)&&t.o){var b=this.__shady_firstChild;(b!=this.__shady_lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&Ob(this);this.__shady_native_textContent=a}else Ob(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_insertBefore(document.createTextNode(a));break;default:this.nodeValue=a}},insertBefore:function(a,b){if(this.ownerDocument!==Kb&&a.ownerDocument!==Kb)return this.__shady_native_insertBefore(a,
b),a;if(a===this)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(b){var c=r(b);c=c&&c.parentNode;if(void 0!==c&&c!==this||void 0===c&&b.__shady_native_parentNode!==this)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(b===a)return a;var d=[],e=(c=E(this))?c.host.localName:Ib(this),f=a.__shady_parentNode;if(f){var g=Ib(a);f.__shady_removeChild(a,!!c||
!E(a))}f=!0;var h=(!Lb||void 0===a.__noInsertionPoint)&&!Hb(a,e),k=c&&!a.__noInsertionPoint&&(!Lb||a.nodeType===Node.DOCUMENT_FRAGMENT_NODE);if(k||h)h&&(g=g||Ib(a)),Jb(a,function(l){k&&"slot"===l.localName&&d.push(l);if(h){var m=g;D()&&(m&&Gb(l,m),(m=D())&&m.scopeNode(l,e))}});if("slot"===this.localName||d.length)d.length&&(c.i=c.i||[],c.g=c.g||[],c.h=c.h||{},c.i.push.apply(c.i,d instanceof Array?d:ca(ba(d)))),c&&F(c);u(this)&&(Cb(a,this,b),c=r(this),ia(this)?(F(c.root),f=!1):c.root&&(f=!1));f?(c=
v(this)?this.host:this,b?(b=Qb(b),c.__shady_native_insertBefore(a,b)):c.__shady_native_appendChild(a)):a.ownerDocument!==this.ownerDocument&&this.ownerDocument.adoptNode(a);Rb(this,a);return a},appendChild:function(a){return this.__shady_insertBefore(a)},removeChild:function(a,b){b=void 0===b?!1:b;if(this.ownerDocument!==Kb)return this.__shady_native_removeChild(a);if(a.__shady_parentNode!==this)throw Error("The node to be removed is not a child of this node: "+a);var c=E(a),d=c&&Sb(c,a),e=r(this);
if(u(this)&&(Db(a,this),ia(this))){F(e.root);var f=!0}if(D()&&!b&&c){var g=Ib(a);Jb(a,function(h){Gb(h,g)})}Pb(a);c&&((b=this&&"slot"===this.localName)&&(f=!0),(d||b)&&F(c));f||(f=v(this)?this.host:this,(!e.root&&"slot"!==a.localName||f===a.__shady_native_parentNode)&&f.__shady_native_removeChild(a));Rb(this,null,a);return a},replaceChild:function(a,b){this.__shady_insertBefore(a,b);this.__shady_removeChild(b);return a},cloneNode:function(a){if("template"==this.localName)return this.__shady_native_cloneNode(a);
var b=this.__shady_native_cloneNode(!1);if(a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.__shady_childNodes;for(var c=0,d;c<a.length;c++)d=a[c].__shady_cloneNode(!0),b.__shady_appendChild(d)}return b},getRootNode:function(a){if(this&&this.nodeType){var b=q(this),c=b.K;void 0===c&&(v(this)?(c=this,b.K=c):(c=(c=this.__shady_parentNode)?c.__shady_getRootNode(a):this,document.documentElement.__shady_native_contains(this)&&(b.K=c)));return c}},contains:function(a){return ra(this,a)}});function Ub(a,b,c){var d=[];Vb(a.__shady_childNodes,b,c,d);return d}function Vb(a,b,c,d){for(var e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var k=b,l=c,m=d,p=k(h);p&&m.push(h);l&&l(p)?h=p:(Vb(h.__shady_childNodes,k,l,m),h=void 0)}if(h)break}}
var G=y({get firstElementChild(){var a=r(this);if(a&&void 0!==a.firstChild){for(a=this.__shady_firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_firstElementChild},get lastElementChild(){var a=r(this);if(a&&void 0!==a.lastChild){for(a=this.__shady_lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_lastElementChild},get children(){return u(this)?sa(Array.prototype.filter.call(this.__shady_childNodes,
function(a){return a.nodeType===Node.ELEMENT_NODE})):this.__shady_native_children},get childElementCount(){var a=this.__shady_children;return a?a.length:0}}),Wb=y({querySelector:function(a){return Ub(this,function(b){return la.call(b,a)},function(b){return!!b})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(this.__shady_native_querySelectorAll(a));var c=this.__shady_getRootNode();return b.filter(function(d){return d.__shady_getRootNode()==c})}return Ub(this,function(d){return la.call(d,
a)})}}),Xb=t.fa?Object.assign({},G):G;Object.assign(G,Wb);var Yb=y({getElementById:function(a){return""===a?null:Ub(this,function(b){return b.id==a},function(b){return!!b})[0]||null}});var Zb=y({get activeElement(){var a=t.o?document.__shady_native_activeElement:document.activeElement;if(!a||!a.nodeType)return null;var b=!!v(this);if(!(this===document||b&&this.host!==a&&this.host.__shady_native_contains(a)))return null;for(b=E(a);b&&b!==this;)a=b.host,b=E(a);return this===document?b?null:a:b===this?a:null}});var $b=document.implementation.createHTMLDocument("inert"),ac=y({get innerHTML(){return u(this)?Ia("template"===this.localName?this.content:this,function(a){return a.__shady_childNodes}):this.__shady_native_innerHTML},set innerHTML(a){if("template"===this.localName)this.__shady_native_innerHTML=a;else{Ob(this);var b=this.localName||"div";b=this.namespaceURI&&this.namespaceURI!==$b.namespaceURI?$b.createElementNS(this.namespaceURI,b):$b.createElement(b);for(t.o?b.__shady_native_innerHTML=a:b.innerHTML=
a;a=b.__shady_firstChild;)this.__shady_insertBefore(a)}}});var bc=y({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.X=this;this.host.__shady_addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.X=this;this.host.__shady_removeEventListener(a,b,c)}});function cc(a,b){x(a,bc,b);x(a,Zb,b);x(a,ac,b);x(a,G,b);t.J&&!b?(x(a,Tb,b),x(a,Yb,b)):t.o||(x(a,Va),x(a,Ua))};var dc={},H=t.deferConnectionCallbacks&&"loading"===document.readyState,ec;function fc(a){var b=[];do b.unshift(a);while(a=a.__shady_parentNode);return b}
function gc(a,b,c){if(a!==dc)throw new TypeError("Illegal constructor");this.oa="ShadyRoot";this.host=b;this.mode=c&&c.mode;Eb(b);a=q(b);a.root=this;a.ga="closed"!==this.mode?this:null;a=q(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;a.childNodes=[];this.Y=this.C=!1;this.i=this.h=this.g=null;if(t.preferPerformance)for(;a=b.__shady_native_firstChild;)b.__shady_native_removeChild(a);else F(this)}function F(a){a.C||(a.C=!0,va(function(){return hc(a)}))}
function hc(a){var b;if(b=a.C){for(var c;a;)a:{a.C&&(c=a),b=a;a=b.host.__shady_getRootNode();if(v(a)&&(b=r(b.host))&&0<b.O)break a;a=void 0}b=c}(c=b)&&c._renderSelf()}
gc.prototype._renderSelf=function(){var a=H;H=!0;this.C=!1;if(this.g){ic(this);for(var b=0,c;b<this.g.length;b++){c=this.g[b];var d=r(c),e=d.assignedNodes;d.assignedNodes=[];d.D=[];if(d.Z=e)for(d=0;d<e.length;d++){var f=r(e[d]);f.R=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(b=this.host.__shady_firstChild;b;b=b.__shady_nextSibling)jc(this,b);for(b=0;b<this.g.length;b++){c=this.g[b];e=r(c);if(!e.assignedNodes.length)for(d=c.__shady_firstChild;d;d=d.__shady_nextSibling)jc(this,d,c);
(d=(d=r(c.__shady_parentNode))&&d.root)&&(ja(d)||d.C)&&d._renderSelf();kc(this,e.D,e.assignedNodes);if(d=e.Z){for(f=0;f<d.length;f++)r(d[f]).R=null;e.Z=null;d.length>e.assignedNodes.length&&(e.U=!0)}e.U&&(e.U=!1,lc(this,c))}c=this.g;b=[];for(e=0;e<c.length;e++)d=c[e].__shady_parentNode,(f=r(d))&&f.root||!(0>b.indexOf(d))||b.push(d);for(c=0;c<b.length;c++){f=b[c];e=f===this?this.host:f;d=[];f=f.__shady_childNodes;for(var g=0;g<f.length;g++){var h=f[g];if("slot"==h.localName){h=r(h).D;for(var k=0;k<
h.length;k++)d.push(h[k])}else d.push(h)}f=Array.prototype.slice.call(e.__shady_native_childNodes);g=zb(d,d.length,f,f.length);k=h=0;for(var l=void 0;h<g.length&&(l=g[h]);h++){for(var m=0,p=void 0;m<l.L.length&&(p=l.L[m]);m++)p.__shady_native_parentNode===e&&e.__shady_native_removeChild(p),f.splice(l.index+k,1);k-=l.S}k=0;for(l=void 0;k<g.length&&(l=g[k]);k++)for(h=f[l.index],m=l.index;m<l.index+l.S;m++)p=d[m],e.__shady_native_insertBefore(p,h),f.splice(m,0,p)}}if(!t.preferPerformance&&!this.Y)for(b=
this.host.__shady_childNodes,c=0,e=b.length;c<e;c++)d=b[c],f=r(d),d.__shady_native_parentNode!==this.host||"slot"!==d.localName&&f.assignedSlot||this.host.__shady_native_removeChild(d);this.Y=!0;H=a;ec&&ec()};function jc(a,b,c){var d=q(b),e=d.R;d.R=null;c||(c=(a=a.h[b.__shady_slot||"__catchall"])&&a[0]);c?(q(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(q(d.assignedSlot).U=!0)}
function kc(a,b,c){for(var d=0,e=void 0;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=r(e).assignedNodes;f&&f.length&&kc(a,b,f)}else b.push(c[d])}function lc(a,b){b.__shady_native_dispatchEvent(new Event("slotchange"));b=r(b);b.assignedSlot&&lc(a,b.assignedSlot)}
function ic(a){if(a.i&&a.i.length){for(var b=a.i,c,d=0;d<b.length;d++){var e=b[d];Eb(e);var f=e.__shady_parentNode;Eb(f);f=r(f);f.O=(f.O||0)+1;f=mc(e);a.h[f]?(c=c||{},c[f]=!0,a.h[f].push(e)):a.h[f]=[e];a.g.push(e)}if(c)for(var g in c)a.h[g]=nc(a.h[g]);a.i=[]}}function mc(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.ma=b}
function nc(a){return a.sort(function(b,c){b=fc(b);for(var d=fc(c),e=0;e<b.length;e++){c=b[e];var f=d[e];if(c!==f)return b=Array.from(c.__shady_parentNode.__shady_childNodes),b.indexOf(c)-b.indexOf(f)}})}
function Sb(a,b){if(a.g){ic(a);var c=a.h,d;for(d in c)for(var e=c[d],f=0;f<e.length;f++){var g=e[f];if(ra(b,g)){e.splice(f,1);var h=a.g.indexOf(g);0<=h&&(a.g.splice(h,1),(h=r(g.__shady_parentNode))&&h.O&&h.O--);f--;g=r(g);if(h=g.D)for(var k=0;k<h.length;k++){var l=h[k],m=l.__shady_native_parentNode;m&&m.__shady_native_removeChild(l)}g.D=[];g.assignedNodes=[];h=!0}}return h}}function ja(a){ic(a);return!(!a.g||!a.g.length)}
(function(a){a.__proto__=DocumentFragment.prototype;cc(a,"__shady_");cc(a);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})})(gc.prototype);
if(window.customElements&&t.$&&!t.preferPerformance){var oc=new Map;ec=function(){var a=[];oc.forEach(function(d,e){a.push([e,d])});oc.clear();for(var b=0;b<a.length;b++){var c=a[b][0];a[b][1]?c.ka():c.la()}};H&&document.addEventListener("readystatechange",function(){H=!1;ec()},{once:!0});var pc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.ka=function(){H?oc.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.la=
function(){H?this.isConnected||oc.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},qc=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;qc.call(window.customElements,a,pc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})}function E(a){a=a.__shady_getRootNode();if(v(a))return a};function I(a){this.node=a}n=I.prototype;n.addEventListener=function(a,b,c){return this.node.__shady_addEventListener(a,b,c)};n.removeEventListener=function(a,b,c){return this.node.__shady_removeEventListener(a,b,c)};n.appendChild=function(a){return this.node.__shady_appendChild(a)};n.insertBefore=function(a,b){return this.node.__shady_insertBefore(a,b)};n.removeChild=function(a){return this.node.__shady_removeChild(a)};n.replaceChild=function(a,b){return this.node.__shady_replaceChild(a,b)};
n.cloneNode=function(a){return this.node.__shady_cloneNode(a)};n.getRootNode=function(a){return this.node.__shady_getRootNode(a)};n.contains=function(a){return this.node.__shady_contains(a)};n.dispatchEvent=function(a){return this.node.__shady_dispatchEvent(a)};n.setAttribute=function(a,b){this.node.__shady_setAttribute(a,b)};n.getAttribute=function(a){return this.node.__shady_native_getAttribute(a)};n.removeAttribute=function(a){this.node.__shady_removeAttribute(a)};n.attachShadow=function(a){return this.node.__shady_attachShadow(a)};
n.focus=function(){this.node.__shady_native_focus()};n.blur=function(){this.node.__shady_blur()};n.importNode=function(a,b){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_importNode(a,b)};n.getElementById=function(a){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_getElementById(a)};n.querySelector=function(a){return this.node.__shady_querySelector(a)};n.querySelectorAll=function(a,b){return this.node.__shady_querySelectorAll(a,b)};
n.assignedNodes=function(a){if("slot"===this.node.localName)return this.node.__shady_assignedNodes(a)};
ea.Object.defineProperties(I.prototype,{activeElement:{configurable:!0,enumerable:!0,get:function(){if(v(this.node)||this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_activeElement}},_activeElement:{configurable:!0,enumerable:!0,get:function(){return this.activeElement}},host:{configurable:!0,enumerable:!0,get:function(){if(v(this.node))return this.node.host}},parentNode:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_parentNode}},firstChild:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_firstChild}},lastChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastChild}},nextSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextSibling}},previousSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousSibling}},childNodes:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childNodes}},parentElement:{configurable:!0,enumerable:!0,
get:function(){return this.node.__shady_parentElement}},firstElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_firstElementChild}},lastElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastElementChild}},nextElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextElementSibling}},previousElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousElementSibling}},
children:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_children}},childElementCount:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childElementCount}},shadowRoot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_shadowRoot}},assignedSlot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_assignedSlot}},isConnected:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_isConnected}},innerHTML:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_innerHTML},set:function(a){this.node.__shady_innerHTML=a}},textContent:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_textContent},set:function(a){this.node.__shady_textContent=a}},slot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_slot},set:function(a){this.node.__shady_slot=a}}});
xb.forEach(function(a){Object.defineProperty(I.prototype,a,{get:function(){return this.node["__shady_"+a]},set:function(b){this.node["__shady_"+a]=b},configurable:!0})});var rc=new WeakMap;function sc(a){if(v(a)||a instanceof I)return a;var b=rc.get(a);b||(b=new I(a),rc.set(a,b));return b};var tc=y({dispatchEvent:function(a){wa();return this.__shady_native_dispatchEvent(a)},addEventListener:ob,removeEventListener:qb});var uc=y({get assignedSlot(){var a=this.__shady_parentNode;(a=a&&a.__shady_shadowRoot)&&hc(a);return(a=r(this))&&a.assignedSlot||null}});var vc=window.document;function wc(a,b){if("slot"===b)a=a.__shady_parentNode,ia(a)&&F(r(a).root);else if("slot"===a.localName&&"name"===b&&(b=E(a))){if(b.g){ic(b);var c=a.ma,d=mc(a);if(d!==c){c=b.h[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.h[d]||(b.h[d]=[]);c.push(a);1<c.length&&(b.h[d]=nc(c))}}F(b)}}
var xc=y({get previousElementSibling(){var a=r(this);if(a&&void 0!==a.previousSibling){for(a=this.__shady_previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_previousElementSibling},get nextElementSibling(){var a=r(this);if(a&&void 0!==a.nextSibling){for(a=this.__shady_nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_nextElementSibling},get slot(){return this.getAttribute("slot")},
set slot(a){this.__shady_setAttribute("slot",a)},get shadowRoot(){var a=r(this);return a&&a.ga||null},get className(){return this.getAttribute("class")||""},set className(a){this.__shady_setAttribute("class",a)},setAttribute:function(a,b){if(this.ownerDocument!==vc)this.__shady_native_setAttribute(a,b);else{var c;(c=D())&&"class"===a?(c.setElementClass(this,b),c=!0):c=!1;c||(this.__shady_native_setAttribute(a,b),wc(this,a))}},removeAttribute:function(a){this.__shady_native_removeAttribute(a);wc(this,
a)},attachShadow:function(a){if(!this)throw Error("Must provide a host.");if(!a)throw Error("Not enough arguments.");return new gc(dc,this,a)}});var yc=y({blur:function(){var a=r(this);(a=(a=a&&a.root)&&a.activeElement)?a.__shady_blur():this.__shady_native_blur()}});xb.forEach(function(a){yc[a]={set:function(b){var c=q(this),d=a.substring(2);c.P[a]&&this.removeEventListener(d,c.P[a]);this.__shady_addEventListener(d,b);c.P[a]=b},get:function(){var b=r(this);return b&&b.P[a]},configurable:!0}});var zc=y({assignedNodes:function(a){if("slot"===this.localName){var b=this.__shady_getRootNode();b&&v(b)&&hc(b);return(b=r(this))?(a&&a.flatten?b.D:b.assignedNodes)||[]:[]}}});var Ac=window.document,Bc=y({importNode:function(a,b){if(a.ownerDocument!==Ac||"template"===a.localName)return this.__shady_native_importNode(a,b);var c=this.__shady_native_importNode(a,!1);if(b){a=a.__shady_childNodes;b=0;for(var d;b<a.length;b++)d=this.__shady_importNode(a[b],!0),c.__shady_appendChild(d)}return c}});var Cc=y({addEventListener:ob.bind(window),removeEventListener:qb.bind(window)});var J={};Object.getOwnPropertyDescriptor(HTMLElement.prototype,"parentElement")&&(J.parentElement=Tb.parentElement);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"contains")&&(J.contains=Tb.contains);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"children")&&(J.children=G.children);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&(J.innerHTML=ac.innerHTML);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"className")&&(J.className=xc.className);
var Dc={EventTarget:[tc],Node:[Tb,window.EventTarget?null:tc],Text:[uc],Element:[xc,G,uc,!t.o||"innerHTML"in Element.prototype?ac:null,window.HTMLSlotElement?null:zc],HTMLElement:[yc,J],HTMLSlotElement:[zc],DocumentFragment:[Xb,Yb],Document:[Bc,Xb,Yb,Zb],Window:[Cc]},Ec=t.o?null:["innerHTML","textContent"];function Fc(a){var b=a?null:Ec,c={},d;for(d in Dc)c.N=window[d]&&window[d].prototype,Dc[d].forEach(function(e){return function(f){return e.N&&f&&x(e.N,f,a,b)}}(c)),c={N:c.N}};if(t.$){var ShadyDOM={inUse:t.$,patch:function(a){$a(a);Za(a);return a},isShadyRoot:v,enqueue:va,flush:wa,flushInitial:function(a){!a.Y&&a.C&&hc(a)},settings:t,filterMutations:Ba,observeChildren:za,unobserveChildren:Aa,deferConnectionCallbacks:t.deferConnectionCallbacks,preferPerformance:t.preferPerformance,handlesDynamicScoping:!0,wrap:t.J?sc:function(a){return a},Wrapper:I,composedPath:gb,noPatch:t.J,nativeMethods:Ka,nativeTree:La};window.ShadyDOM=ShadyDOM;Ta();Fc("__shady_");Object.defineProperty(document,
"_activeElement",Zb.activeElement);x(Window.prototype,Cc,"__shady_");t.J||(Fc(),wb());rb();window.Event=tb;window.CustomEvent=ub;window.MouseEvent=vb;window.ShadowRoot=gc};var Gc=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function Hc(a){var b=Gc.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function K(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}
function Ic(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}
function L(a,b,c){c=void 0===c?new Set:c;for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)L(d,b,c);d=Ic(a,e);continue}else if("template"===f){d=Ic(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)L(e,b,c)}d=d.firstChild?d.firstChild:Ic(a,d)}}function M(a,b,c){a[b]=c};function Jc(){this.g=new Map;this.j=new Map;this.i=[];this.h=!1}function Kc(a,b,c){a.g.set(b,c);a.j.set(c.constructorFunction,c)}function Lc(a,b){a.h=!0;a.i.push(b)}function Mc(a,b){a.h&&L(b,function(c){return Nc(a,c)})}function Nc(a,b){if(a.h&&!b.__CE_patched){b.__CE_patched=!0;for(var c=0;c<a.i.length;c++)a.i[c](b)}}function N(a,b){var c=[];L(b,function(e){return c.push(e)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state?a.connectedCallback(d):Oc(a,d)}}
function O(a,b){var c=[];L(b,function(e){return c.push(e)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state&&a.disconnectedCallback(d)}}
function P(a,b,c){c=void 0===c?{}:c;var d=c.Ga||new Set,e=c.upgrade||function(g){return Oc(a,g)},f=[];L(b,function(g){if("link"===g.localName&&"import"===g.getAttribute("rel")){var h=g.import;h instanceof Node&&(h.__CE_isImportDocument=!0,h.__CE_hasRegistry=!0);h&&"complete"===h.readyState?h.__CE_documentLoadHandled=!0:g.addEventListener("load",function(){var k=g.import;if(!k.__CE_documentLoadHandled){k.__CE_documentLoadHandled=!0;var l=new Set(d);l.delete(k);P(a,k,{Ga:l,upgrade:e})}})}else f.push(g)},
d);if(a.h)for(b=0;b<f.length;b++)Nc(a,f[b]);for(b=0;b<f.length;b++)e(f[b])}
function Oc(a,b){if(void 0===b.__CE_state){var c=b.ownerDocument;if(c.defaultView||c.__CE_isImportDocument&&c.__CE_hasRegistry)if(c=a.g.get(b.localName)){c.constructionStack.push(b);var d=c.constructorFunction;try{try{if(new d!==b)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(g){throw b.__CE_state=2,g;}b.__CE_state=1;b.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,d=0;d<c.length;d++){var e=
c[d],f=b.getAttribute(e);null!==f&&a.attributeChangedCallback(b,e,null,f,null)}K(b)&&a.connectedCallback(b)}}}Jc.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};Jc.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};
Jc.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&f.attributeChangedCallback.call(a,b,c,d,e)};function Pc(a){var b=document;this.h=a;this.g=b;this.G=void 0;P(this.h,this.g);"loading"===this.g.readyState&&(this.G=new MutationObserver(this.i.bind(this)),this.G.observe(this.g,{childList:!0,subtree:!0}))}function Qc(a){a.G&&a.G.disconnect()}Pc.prototype.i=function(a){var b=this.g.readyState;"interactive"!==b&&"complete"!==b||Qc(this);for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)P(this.h,c[d])};function Rc(){var a=this;this.h=this.g=void 0;this.i=new Promise(function(b){a.h=b;a.g&&b(a.g)})}function Sc(a){if(a.g)throw Error("Already resolved.");a.g=void 0;a.h&&a.h(void 0)};function Q(a){this.i=!1;this.g=a;this.H=new Map;this.j=function(b){return b()};this.h=!1;this.F=[];this.xa=new Pc(a)}n=Q.prototype;
n.ia=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!Hc(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.g.g.get(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this.i)throw Error("A custom element is already being defined.");this.i=!0;try{var d=function(m){var p=e[m];if(void 0!==p&&!(p instanceof Function))throw Error("The '"+m+"' callback must be a function.");
return p},e=b.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=d("connectedCallback");var g=d("disconnectedCallback");var h=d("adoptedCallback");var k=d("attributeChangedCallback");var l=b.observedAttributes||[]}catch(m){return}finally{this.i=!1}b={localName:a,constructorFunction:b,connectedCallback:f,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]};Kc(this.g,
a,b);this.F.push(b);this.h||(this.h=!0,this.j(function(){return Tc(c)}))};n.upgrade=function(a){P(this.g,a)};
function Tc(a){if(!1!==a.h){a.h=!1;for(var b=a.F,c=[],d=new Map,e=0;e<b.length;e++)d.set(b[e].localName,[]);P(a.g,document,{upgrade:function(h){if(void 0===h.__CE_state){var k=h.localName,l=d.get(k);l?l.push(h):a.g.g.get(k)&&c.push(h)}}});for(e=0;e<c.length;e++)Oc(a.g,c[e]);for(;0<b.length;){var f=b.shift();e=f.localName;f=d.get(f.localName);for(var g=0;g<f.length;g++)Oc(a.g,f[g]);(e=a.H.get(e))&&Sc(e)}}}n.get=function(a){if(a=this.g.g.get(a))return a.constructorFunction};
n.ja=function(a){if(!Hc(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.H.get(a);if(b)return b.i;b=new Rc;this.H.set(a,b);this.g.g.get(a)&&!this.F.some(function(c){return c.localName===a})&&Sc(b);return b.i};n.ya=function(a){Qc(this.xa);var b=this.j;this.j=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=Q;Q.prototype.define=Q.prototype.ia;Q.prototype.upgrade=Q.prototype.upgrade;Q.prototype.get=Q.prototype.get;
Q.prototype.whenDefined=Q.prototype.ja;Q.prototype.polyfillWrapFlushCallback=Q.prototype.ya;var Uc=window.Document.prototype.createElement,Vc=window.Document.prototype.createElementNS,Wc=window.Document.prototype.importNode,Xc=window.Document.prototype.prepend,Yc=window.Document.prototype.append,Zc=window.DocumentFragment.prototype.prepend,$c=window.DocumentFragment.prototype.append,ad=window.Node.prototype.cloneNode,bd=window.Node.prototype.appendChild,cd=window.Node.prototype.insertBefore,dd=window.Node.prototype.removeChild,ed=window.Node.prototype.replaceChild,fd=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),gd=window.Element.prototype.attachShadow,hd=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),id=window.Element.prototype.getAttribute,jd=window.Element.prototype.setAttribute,kd=window.Element.prototype.removeAttribute,ld=window.Element.prototype.getAttributeNS,md=window.Element.prototype.setAttributeNS,nd=window.Element.prototype.removeAttributeNS,od=window.Element.prototype.insertAdjacentElement,pd=window.Element.prototype.insertAdjacentHTML,qd=window.Element.prototype.prepend,
rd=window.Element.prototype.append,sd=window.Element.prototype.before,td=window.Element.prototype.after,ud=window.Element.prototype.replaceWith,vd=window.Element.prototype.remove,wd=window.HTMLElement,xd=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),yd=window.HTMLElement.prototype.insertAdjacentElement,zd=window.HTMLElement.prototype.insertAdjacentHTML;var Ad=new function(){};function Bd(){var a=Cd;window.HTMLElement=function(){function b(){var c=this.constructor,d=a.j.get(c);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");var e=d.constructionStack;if(0===e.length)return e=Uc.call(document,d.localName),Object.setPrototypeOf(e,c.prototype),e.__CE_state=1,e.__CE_definition=d,Nc(a,e),e;d=e.length-1;var f=e[d];if(f===Ad)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
e[d]=Ad;Object.setPrototypeOf(f,c.prototype);Nc(a,f);return f}b.prototype=wd.prototype;Object.defineProperty(b.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:b});return b}()};function Dd(a,b,c){function d(e){return function(f){for(var g=[],h=0;h<arguments.length;++h)g[h]=arguments[h];h=[];for(var k=[],l=0;l<g.length;l++){var m=g[l];m instanceof Element&&K(m)&&k.push(m);if(m instanceof DocumentFragment)for(m=m.firstChild;m;m=m.nextSibling)h.push(m);else h.push(m)}e.apply(this,g);for(g=0;g<k.length;g++)O(a,k[g]);if(K(this))for(g=0;g<h.length;g++)k=h[g],k instanceof Element&&N(a,k)}}void 0!==c.prepend&&M(b,"prepend",d(c.prepend));void 0!==c.append&&M(b,"append",d(c.append))}
;function Ed(){var a=Cd;M(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=a.g.get(b);if(c)return new c.constructorFunction}b=Uc.call(this,b);Nc(a,b);return b});M(Document.prototype,"importNode",function(b,c){b=Wc.call(this,b,!!c);this.__CE_hasRegistry?P(a,b):Mc(a,b);return b});M(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.g.get(c);if(d)return new d.constructorFunction}b=Vc.call(this,
b,c);Nc(a,b);return b});Dd(a,Document.prototype,{prepend:Xc,append:Yc})};function Fd(){function a(c,d){Object.defineProperty(c,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(e){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,e);else{var f=void 0;if(this.firstChild){var g=this.childNodes,h=g.length;if(0<h&&K(this)){f=Array(h);for(var k=0;k<h;k++)f[k]=g[k]}}d.set.call(this,e);if(f)for(e=0;e<f.length;e++)O(b,f[e])}}})}var b=Cd;M(Node.prototype,"insertBefore",function(c,d){if(c instanceof DocumentFragment){var e=Array.prototype.slice.apply(c.childNodes);
c=cd.call(this,c,d);if(K(this))for(d=0;d<e.length;d++)N(b,e[d]);return c}e=K(c);d=cd.call(this,c,d);e&&O(b,c);K(this)&&N(b,c);return d});M(Node.prototype,"appendChild",function(c){if(c instanceof DocumentFragment){var d=Array.prototype.slice.apply(c.childNodes);c=bd.call(this,c);if(K(this))for(var e=0;e<d.length;e++)N(b,d[e]);return c}d=K(c);e=bd.call(this,c);d&&O(b,c);K(this)&&N(b,c);return e});M(Node.prototype,"cloneNode",function(c){c=ad.call(this,!!c);this.ownerDocument.__CE_hasRegistry?P(b,c):
Mc(b,c);return c});M(Node.prototype,"removeChild",function(c){var d=K(c),e=dd.call(this,c);d&&O(b,c);return e});M(Node.prototype,"replaceChild",function(c,d){if(c instanceof DocumentFragment){var e=Array.prototype.slice.apply(c.childNodes);c=ed.call(this,c,d);if(K(this))for(O(b,d),d=0;d<e.length;d++)N(b,e[d]);return c}e=K(c);var f=ed.call(this,c,d),g=K(this);g&&O(b,d);e&&O(b,c);g&&N(b,c);return f});fd&&fd.get?a(Node.prototype,fd):Lc(b,function(c){a(c,{enumerable:!0,configurable:!0,get:function(){for(var d=
[],e=0;e<this.childNodes.length;e++)d.push(this.childNodes[e].textContent);return d.join("")},set:function(d){for(;this.firstChild;)dd.call(this,this.firstChild);bd.call(this,document.createTextNode(d))}})})};function Gd(a){function b(d){return function(e){for(var f=[],g=0;g<arguments.length;++g)f[g]=arguments[g];g=[];for(var h=[],k=0;k<f.length;k++){var l=f[k];l instanceof Element&&K(l)&&h.push(l);if(l instanceof DocumentFragment)for(l=l.firstChild;l;l=l.nextSibling)g.push(l);else g.push(l)}d.apply(this,f);for(f=0;f<h.length;f++)O(a,h[f]);if(K(this))for(f=0;f<g.length;f++)h=g[f],h instanceof Element&&N(a,h)}}var c=Element.prototype;void 0!==sd&&M(c,"before",b(sd));void 0!==sd&&M(c,"after",b(td));void 0!==
ud&&M(c,"replaceWith",function(d){for(var e=[],f=0;f<arguments.length;++f)e[f]=arguments[f];f=[];for(var g=[],h=0;h<e.length;h++){var k=e[h];k instanceof Element&&K(k)&&g.push(k);if(k instanceof DocumentFragment)for(k=k.firstChild;k;k=k.nextSibling)f.push(k);else f.push(k)}h=K(this);ud.apply(this,e);for(e=0;e<g.length;e++)O(a,g[e]);if(h)for(O(a,this),e=0;e<f.length;e++)g=f[e],g instanceof Element&&N(a,g)});void 0!==vd&&M(c,"remove",function(){var d=K(this);vd.call(this);d&&O(a,this)})};function Hd(){function a(e,f){Object.defineProperty(e,"innerHTML",{enumerable:f.enumerable,configurable:!0,get:f.get,set:function(g){var h=this,k=void 0;K(this)&&(k=[],L(this,function(p){p!==h&&k.push(p)}));f.set.call(this,g);if(k)for(var l=0;l<k.length;l++){var m=k[l];1===m.__CE_state&&d.disconnectedCallback(m)}this.ownerDocument.__CE_hasRegistry?P(d,this):Mc(d,this);return g}})}function b(e,f){M(e,"insertAdjacentElement",function(g,h){var k=K(h);g=f.call(this,g,h);k&&O(d,h);K(g)&&N(d,h);return g})}
function c(e,f){function g(h,k){for(var l=[];h!==k;h=h.nextSibling)l.push(h);for(k=0;k<l.length;k++)P(d,l[k])}M(e,"insertAdjacentHTML",function(h,k){h=h.toLowerCase();if("beforebegin"===h){var l=this.previousSibling;f.call(this,h,k);g(l||this.parentNode.firstChild,this)}else if("afterbegin"===h)l=this.firstChild,f.call(this,h,k),g(this.firstChild,l);else if("beforeend"===h)l=this.lastChild,f.call(this,h,k),g(l||this.firstChild,null);else if("afterend"===h)l=this.nextSibling,f.call(this,h,k),g(this.nextSibling,
l);else throw new SyntaxError("The value provided ("+String(h)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");})}var d=Cd;gd&&M(Element.prototype,"attachShadow",function(e){return this.__CE_shadowRoot=e=gd.call(this,e)});hd&&hd.get?a(Element.prototype,hd):xd&&xd.get?a(HTMLElement.prototype,xd):Lc(d,function(e){a(e,{enumerable:!0,configurable:!0,get:function(){return ad.call(this,!0).innerHTML},set:function(f){var g="template"===this.localName,h=g?this.content:this,k=Vc.call(document,
this.namespaceURI,this.localName);for(k.innerHTML=f;0<h.childNodes.length;)dd.call(h,h.childNodes[0]);for(f=g?k.content:k;0<f.childNodes.length;)bd.call(h,f.childNodes[0])}})});M(Element.prototype,"setAttribute",function(e,f){if(1!==this.__CE_state)return jd.call(this,e,f);var g=id.call(this,e);jd.call(this,e,f);f=id.call(this,e);d.attributeChangedCallback(this,e,g,f,null)});M(Element.prototype,"setAttributeNS",function(e,f,g){if(1!==this.__CE_state)return md.call(this,e,f,g);var h=ld.call(this,e,
f);md.call(this,e,f,g);g=ld.call(this,e,f);d.attributeChangedCallback(this,f,h,g,e)});M(Element.prototype,"removeAttribute",function(e){if(1!==this.__CE_state)return kd.call(this,e);var f=id.call(this,e);kd.call(this,e);null!==f&&d.attributeChangedCallback(this,e,f,null,null)});M(Element.prototype,"removeAttributeNS",function(e,f){if(1!==this.__CE_state)return nd.call(this,e,f);var g=ld.call(this,e,f);nd.call(this,e,f);var h=ld.call(this,e,f);g!==h&&d.attributeChangedCallback(this,f,g,h,e)});yd?b(HTMLElement.prototype,
yd):od?b(Element.prototype,od):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");zd?c(HTMLElement.prototype,zd):pd?c(Element.prototype,pd):console.warn("Custom Elements: `Element#insertAdjacentHTML` was not patched.");Dd(d,Element.prototype,{prepend:qd,append:rd});Gd(d)};/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var Id=window.customElements;if(!Id||Id.forcePolyfill||"function"!=typeof Id.define||"function"!=typeof Id.get){var Cd=new Jc;Bd();Ed();Dd(Cd,DocumentFragment.prototype,{prepend:Zc,append:$c});Fd();Hd();document.__CE_hasRegistry=!0;var customElements=new Q(Cd);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Jd(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Kd(a){var b=a=a.replace(Ld,"").replace(Md,""),c=new Jd;c.start=0;c.end=b.length;for(var d=c,e=0,f=b.length;e<f;e++)if("{"===b[e]){d.rules||(d.rules=[]);var g=d,h=g.rules[g.rules.length-1]||null;d=new Jd;d.start=e+1;d.parent=g;d.previous=h;g.rules.push(d)}else"}"===b[e]&&(d.end=e+1,d=d.parent||c);return Nd(c,a)}
function Nd(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=Od(c),c=c.replace(Pd," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=Qd:c.match(Rd)&&(a.type=Sd,a.keyframesName=a.selector.split(Pd).pop()):a.type=0===c.indexOf("--")?Td:Ud);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)Nd(f,
b);return a}function Od(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(b,c){b=c;for(c=6-b.length;c--;)b="0"+b;return"\\"+b})}
function Vd(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h=void 0;f<g&&(h=e[f]);f++)d=Vd(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(Wd,"").replace(Xd,""),b=b.replace(Yd,"").replace(Zd,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var Ud=1,Sd=7,Qd=4,Td=1E3,Ld=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,Md=/@import[^;]*;/gim,Wd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Xd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,Yd=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Zd=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Rd=/^@[^\s]*keyframes/,Pd=/\s+/g;var R=!(window.ShadyDOM&&window.ShadyDOM.inUse),$d;function ae(a){$d=a&&a.shimcssproperties?!1:R||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var be;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&(be=window.ShadyCSS.cssBuild);var ce=!(!window.ShadyCSS||!window.ShadyCSS.disableRuntime);
window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?$d=window.ShadyCSS.nativeCss:window.ShadyCSS?(ae(window.ShadyCSS),window.ShadyCSS=void 0):ae(window.WebComponents&&window.WebComponents.flags);var S=$d;var de=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,ee=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,fe=/(--[\w-]+)\s*([:,;)]|$)/gi,ge=/(animation\s*:)|(animation-name\s*:)/,he=/@media\s(.*)/,ie=/\{[^}]*\}/g;var je=new Set;function ke(a,b){if(!a)return"";"string"===typeof a&&(a=Kd(a));b&&le(a,b);return Vd(a,S)}function me(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Kd(a.textContent));return a.__cssRules||null}function ne(a){return!!a.parent&&a.parent.type===Sd}function le(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===Qd){var g=a.selector.match(he);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===Ud?b(a):c&&f===Sd?c(a):f===Td&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++)le(g,b,c,d)}}
function oe(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;pe(e,c,d);return e}var T=null;function qe(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(T?T.nextSibling:null)||b.firstChild);return T=a}function pe(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);T?a.compareDocumentPosition(T)===Node.DOCUMENT_POSITION_PRECEDING&&(T=a):T=a}
function re(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function se(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=re(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=se(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function te(a,b){R?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
var ue=window.ShadyDOM&&window.ShadyDOM.wrap||function(a){return a};function U(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,M:c}}function ve(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=re(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function we(a){if(void 0!==be)return be;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function xe(a){a=void 0===a?"":a;return""!==a&&S?R?"shadow"===a:"shady"===a:!1};function ye(){}function ze(a,b){Ae(V,a,function(c){W(c,b||"")})}function Ae(a,b,c){b.nodeType===Node.ELEMENT_NODE&&c(b);if(b="template"===b.localName?(b.content||b._content||b).childNodes:b.children||b.childNodes)for(var d=0;d<b.length;d++)Ae(a,b[d],c)}
function W(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),te(a,b)):te(a,(d?d+" ":"")+"style-scope "+b)}}function Be(a,b,c){Ae(V,a,function(d){W(d,b,!0);W(d,c)})}function Ce(a,b){Ae(V,a,function(c){W(c,b||"",!0)})}
function De(a,b,c,d,e){var f=V;e=void 0===e?"":e;""===e&&(R||"shady"===(void 0===d?"":d)?e=ke(b,c):(a=U(a),e=Ee(f,b,a.is,a.M,c)+"\n\n"));return e.trim()}function Ee(a,b,c,d,e){var f=Fe(c,d);c=c?"."+c:"";return ke(b,function(g){g.i||(g.selector=g.m=Ge(a,g,a.h,c,f),g.i=!0);e&&e(g,c,f)})}function Fe(a,b){return b?"[is="+a+"]":a}
function Ge(a,b,c,d,e){var f=ve(b.selector);if(!ne(b)){b=0;for(var g=f.length,h=void 0;b<g&&(h=f[b]);b++)f[b]=c.call(a,h,d,e)}return f.filter(function(k){return!!k}).join(",")}function He(a){return a.replace(Ie,function(b,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
function Je(a){for(var b=[],c;c=a.match(Ke);){var d=c.index,e=re(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{ba:a,matches:b}}function Le(a,b){var c=a.split("\ue000");return b.reduce(function(d,e,f){return d+e+c[f+1]},c[0])}
ye.prototype.h=function(a,b,c){var d=!1;a=a.trim();var e=Ie.test(a);e&&(a=a.replace(Ie,function(h,k,l){return":"+k+"("+l.replace(/\s/g,"")+")"}),a=He(a));var f=Ke.test(a);if(f){var g=Je(a);a=g.ba;g=g.matches}a=a.replace(Me,":host $1");a=a.replace(Ne,function(h,k,l){d||(h=Oe(l,k,b,c),d=d||h.stop,k=h.ra,l=h.value);return k+l});f&&(a=Le(a,g));e&&(a=He(a));return a};
function Oe(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=Pe(a,d):0!==e&&(a=c?Qe(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(Re,function(g,h){return" > "+h}))}a=a.replace(Se,function(g,h,k){return'[dir="'+k+'"] '+h+", "+h+'[dir="'+k+'"]'});return{value:a,ra:b,stop:f}}
function Qe(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")}function Pe(a,b){var c=a.match(Te);return(c=c&&c[2].trim()||"")?c[0].match(Ue)?a.replace(Te,function(d,e,f){return b+f}):c.split(Ue)[0]===b?c:"should_not_match":a.replace(":host",b)}function Ve(a){":root"===a.selector&&(a.selector="html")}
ye.prototype.i=function(a){return a.match(":host")?"":a.match("::slotted")?this.h(a,":not(.style-scope)"):Qe(a.trim(),":not(.style-scope)")};ea.Object.defineProperties(ye.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Ie=/:(nth[-\w]+)\(([^)]+)\)/,Ne=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,Ue=/[[.:#*]/,Me=/^(::slotted)/,Te=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Re=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Se=/(.*):dir\((?:(ltr|rtl))\)/,Ke=/:(?:matches|any|-(?:webkit|moz)-any)/,V=new ye;function We(a,b,c,d,e){this.B=a||null;this.h=b||null;this.aa=c||[];this.s=null;this.cssBuild=e||"";this.M=d||"";this.g=this.u=this.A=null}function X(a){return a?a.__styleInfo:null}function Xe(a,b){return a.__styleInfo=b}We.prototype.i=function(){return this.B};We.prototype._getStyleRules=We.prototype.i;function Ye(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var Ze=navigator.userAgent.match("Trident");function $e(){}function af(a){var b={},c=[],d=0;le(a,function(f){bf(f);f.index=d++;f=f.l.cssText;for(var g;g=fe.exec(f);){var h=g[1];":"!==g[2]&&(b[h]=!0)}},function(f){c.push(f)});a.h=c;a=[];for(var e in b)a.push(e);return a}
function bf(a){if(!a.l){var b={},c={};cf(a,c)&&(b.v=c,a.rules=null);b.cssText=a.parsedCssText.replace(ie,"").replace(de,"");a.l=b}}function cf(a,b){var c=a.l;if(c){if(c.v)return Object.assign(b,c.v),!0}else{c=a.parsedCssText;for(var d;a=de.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function df(a,b,c){b&&(b=0<=b.indexOf(";")?ef(a,b,c):se(b,function(d,e,f,g){if(!e)return d+g;(e=df(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=df(a,c[f]||f,c)||f;return d+(e||"")+g}));return b&&b.trim()||""}
function ef(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){ee.lastIndex=0;if(f=ee.exec(e))e=df(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=df(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function ff(a,b){var c={},d=[];le(a,function(e){e.l||bf(e);var f=e.m||e.parsedSelector;b&&e.l.v&&f&&Ye.call(b,f)&&(cf(e,c),e=e.index,f=parseInt(e/32,10),d[f]=(d[f]||0)|1<<e%32)},null,!0);return{v:c,key:d}}
function gf(a,b,c,d){b.l||bf(b);if(b.l.v){var e=U(a);a=e.is;e=e.M;e=a?Fe(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));if(g||h)c=e,h&&(b.m||(b.m=Ge(V,b,V.h,a?"."+a:"",e)),c=b.m||e),d({ba:c,wa:h,Ia:g})}}function hf(a,b,c){var d={},e={};le(b,function(f){gf(a,f,c,function(g){Ye.call(a._element||a,g.ba)&&(g.wa?cf(f,d):cf(f,e))})},null,!0);return{Aa:e,va:d}}
function jf(a,b,c,d){var e=U(b),f=Fe(e.is,e.M),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),h=X(b);e=h.B;h=h.cssBuild;var k=kf(e,d);return De(b,e,function(l){var m="";l.l||bf(l);l.l.cssText&&(m=ef(a,l.l.cssText,c));l.cssText=m;if(!R&&!ne(l)&&l.cssText){var p=m=l.cssText;null==l.ea&&(l.ea=ge.test(m));if(l.ea)if(null==l.V){l.V=[];for(var A in k)p=k[A],p=p(m),m!==p&&(m=p,l.V.push(A))}else{for(A=0;A<l.V.length;++A)p=k[l.V[A]],m=p(m);p=m}l.cssText=p;l.m=l.m||l.selector;
m="."+d;A=ve(l.m);p=0;for(var ka=A.length,Sa=void 0;p<ka&&(Sa=A[p]);p++)A[p]=Sa.match(g)?Sa.replace(f,m):m+" "+Sa;l.selector=A.join(",")}},h)}function kf(a,b){a=a.h;var c={};if(!R&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,g=b;f.j=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.g=f.keyframesName+"-"+g;f.m=f.m||f.selector;f.selector=f.m.replace(f.keyframesName,f.g);c[e.keyframesName]=lf(e)}return c}function lf(a){return function(b){return b.replace(a.j,a.g)}}
function mf(a,b){var c=nf,d=me(a);a.textContent=ke(d,function(e){var f=e.cssText=e.parsedCssText;e.l&&e.l.cssText&&(f=f.replace(Wd,"").replace(Xd,""),e.cssText=ef(c,f,b))})}ea.Object.defineProperties($e.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var nf=new $e;var of={},pf=window.customElements;if(pf&&!R&&!ce){var qf=pf.define;pf.define=function(a,b,c){of[a]||(of[a]=qe(a));qf.call(pf,a,b,c)}};function rf(){this.cache={}}rf.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({v:b,styleElement:c,u:d});100<e.length&&e.shift();this.cache[a]=e};function sf(){}var tf=new RegExp(V.g+"\\s*([^\\s]*)");function uf(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(tf))?a[1]:""}function vf(a){var b=ue(a).getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?U(a).is:""}
function wf(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g=uf(e);if(g&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===we(e)))Ce(e,g);else if(f instanceof ShadowRoot)for(f=vf(e),f!==g&&Be(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+V.g+")"),g=0;g<e.length;g++){f=e[g];
var h=vf(f);h&&W(f,h)}}}}}
if(!(R||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var xf=new MutationObserver(wf),yf=function(a){xf.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)yf(document);else{var zf=function(){yf(document.body)};window.HTMLImports?window.HTMLImports.whenReady(zf):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){zf();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else zf()})}sf=function(){wf(xf.takeRecords())}};var Af={};var Bf=Promise.resolve();function Cf(a){if(a=Af[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Df(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Ef(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,Bf.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var Ff={},Gf=new rf;function Y(){this.H={};this.i=document.documentElement;var a=new Jd;a.rules=[];this.j=Xe(this.i,new We(a));this.F=!1;this.h=this.g=null}n=Y.prototype;n.flush=function(){sf()};n.ta=function(a){return me(a)};n.Ea=function(a){return ke(a)};n.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
n.prepareTemplateStyles=function(a,b,c){if(!a._prepared&&!ce){R||of[b]||(of[b]=qe(b));a._prepared=!0;a.name=b;a.extends=c;Af[b]=a;var d=we(a),e=xe(d);c={is:b,extends:c};for(var f=[],g=a.content.querySelectorAll("style"),h=0;h<g.length;h++){var k=g[h];if(k.hasAttribute("shady-unscoped")){if(!R){var l=k.textContent;je.has(l)||(je.add(l),l=k.cloneNode(!0),document.head.appendChild(l));k.parentNode.removeChild(k)}}else f.push(k.textContent),k.parentNode.removeChild(k)}f=f.join("").trim()+(Ff[b]||"");
Hf(this);if(!e){if(g=!d)g=ee.test(f)||de.test(f),ee.lastIndex=0,de.lastIndex=0;h=Kd(f);g&&S&&this.g&&this.g.transformRules(h,b);a._styleAst=h}g=[];S||(g=af(a._styleAst));if(!g.length||S)h=R?a.content:null,b=of[b]||null,d=De(c,a._styleAst,null,d,e?f:""),d=d.length?oe(d,c.is,h,b):null,a._style=d;a.g=g}};n.za=function(a,b){Ff[b]=a.join(" ")};n.prepareTemplateDom=function(a,b){if(!ce){var c=we(a);R||"shady"===c||a._domPrepared||(a._domPrepared=!0,ze(a.content,b))}};
function If(a){var b=U(a),c=b.is;b=b.M;var d=of[c]||null,e=Af[c];if(e){c=e._styleAst;var f=e.g;e=we(e);b=new We(c,d,f,b,e);Xe(a,b);return b}}function Jf(a){!a.h&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.h=window.ShadyCSS.CustomStyleInterface,a.h.transformCallback=function(b){a.ha(b)},a.h.validateCallback=function(){requestAnimationFrame(function(){(a.h.enqueued||a.F)&&a.flushCustomStyles()})})}
function Hf(a){!a.g&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.g=window.ShadyCSS.ApplyShim,a.g.invalidCallback=Cf);Jf(a)}
n.flushCustomStyles=function(){if(!ce&&(Hf(this),this.h)){var a=this.h.processStyles();if(this.h.enqueued&&!xe(this.j.cssBuild)){if(S){if(!this.j.cssBuild)for(var b=0;b<a.length;b++){var c=this.h.getStyleForCustomStyle(a[b]);if(c&&S&&this.g){var d=me(c);Hf(this);this.g.transformRules(d);c.textContent=ke(d)}}}else{Kf(this,this.i,this.j);for(b=0;b<a.length;b++)(c=this.h.getStyleForCustomStyle(a[b]))&&mf(c,this.j.A);this.F&&this.styleDocument()}this.h.enqueued=!1}}};
n.styleElement=function(a,b){if(ce){if(b){X(a)||Xe(a,new We(null));var c=X(a);c.s=c.s||{};Object.assign(c.s,b);Lf(this,a,c)}}else if(c=X(a)||If(a))if(a!==this.i&&(this.F=!0),b&&(c.s=c.s||{},Object.assign(c.s,b)),S)Lf(this,a,c);else if(this.flush(),Kf(this,a,c),c.aa&&c.aa.length){b=U(a).is;var d;a:{if(d=Gf.cache[b])for(var e=d.length-1;0<=e;e--){var f=d[e];b:{var g=c.aa;for(var h=0;h<g.length;h++){var k=g[h];if(f.v[k]!==c.A[k]){g=!1;break b}}g=!0}if(g){d=f;break a}}d=void 0}g=d?d.styleElement:null;
e=c.u;(f=d&&d.u)||(f=this.H[b]=(this.H[b]||0)+1,f=b+"-"+f);c.u=f;f=c.u;h=nf;h=g?g.textContent||"":jf(h,a,c.A,f);k=X(a);var l=k.g;l&&!R&&l!==g&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));R?k.g?(k.g.textContent=h,g=k.g):h&&(g=oe(h,f,a.shadowRoot,k.h)):g?g.parentNode||(Ze&&-1<h.indexOf("@media")&&(g.textContent=h),pe(g,null,k.h)):h&&(g=oe(h,f,null,k.h));g&&(g._useCount=g._useCount||0,k.g!=g&&g._useCount++,k.g=g);f=g;R||(g=c.u,k=h=a.getAttribute("class")||"",e&&(k=h.replace(new RegExp("\\s*x-scope\\s*"+
e+"\\s*","g")," ")),k+=(k?" ":"")+"x-scope "+g,h!==k&&te(a,k));d||Gf.store(b,c.A,f,c.u)}};
function Lf(a,b,c){var d=U(b).is;if(c.s){var e=c.s,f;for(f in e)null===f?b.style.removeProperty(f):b.style.setProperty(f,e[f])}e=Af[d];if(!(!e&&b!==a.i||e&&""!==we(e))&&e&&e._style&&!Df(e)){if(Df(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)Hf(a),a.g&&a.g.transformRules(e._styleAst,d),e._style.textContent=De(b,c.B),Ef(e);R&&(a=b.shadowRoot)&&(a=a.querySelector("style"))&&(a.textContent=De(b,c.B));c.B=e._styleAst}}
function Mf(a,b){return(b=ue(b).getRootNode().host)?X(b)||If(b)?b:Mf(a,b):a.i}function Kf(a,b,c){var d=Mf(a,b),e=X(d),f=e.A;d===a.i||f||(Kf(a,d,e),f=e.A);a=Object.create(f||null);d=hf(b,c.B,c.cssBuild);b=ff(e.B,b).v;Object.assign(a,d.va,b,d.Aa);b=c.s;for(var g in b)if((e=b[g])||0===e)a[g]=e;g=nf;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=df(g,a[d],a);c.A=a}n.styleDocument=function(a){this.styleSubtree(this.i,a)};
n.styleSubtree=function(a,b){var c=ue(a),d=c.shadowRoot;(d||a===this.i)&&this.styleElement(a,b);if(a=d&&(d.children||d.childNodes))for(c=0;c<a.length;c++)this.styleSubtree(a[c]);else if(c=c.children||c.childNodes)for(a=0;a<c.length;a++)this.styleSubtree(c[a])};
n.ha=function(a){var b=this,c=we(a);c!==this.j.cssBuild&&(this.j.cssBuild=c);if(!xe(c)){var d=me(a);le(d,function(e){if(R)Ve(e);else{var f=V;e.selector=e.parsedSelector;Ve(e);e.selector=e.m=Ge(f,e,f.i,void 0,void 0)}S&&""===c&&(Hf(b),b.g&&b.g.transformRule(e))});S?a.textContent=ke(d):this.j.B.rules.push(d)}};n.getComputedStyleValue=function(a,b){var c;S||(c=(X(a)||X(Mf(this,a))).A[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};
n.Da=function(a,b){var c=ue(a).getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===V.g){c=d[e+1];break}}}c&&b.push(V.g,c);S||(c=X(a))&&c.u&&b.push(nf.g,c.u);te(a,b.join(" "))};n.qa=function(a){return X(a)};n.Ca=function(a,b){W(a,b)};n.Fa=function(a,b){W(a,b,!0)};n.Ba=function(a){return vf(a)};n.sa=function(a){return uf(a)};Y.prototype.flush=Y.prototype.flush;Y.prototype.prepareTemplate=Y.prototype.prepareTemplate;
Y.prototype.styleElement=Y.prototype.styleElement;Y.prototype.styleDocument=Y.prototype.styleDocument;Y.prototype.styleSubtree=Y.prototype.styleSubtree;Y.prototype.getComputedStyleValue=Y.prototype.getComputedStyleValue;Y.prototype.setElementClass=Y.prototype.Da;Y.prototype._styleInfoForNode=Y.prototype.qa;Y.prototype.transformCustomStyleForDocument=Y.prototype.ha;Y.prototype.getStyleAst=Y.prototype.ta;Y.prototype.styleAstToString=Y.prototype.Ea;Y.prototype.flushCustomStyles=Y.prototype.flushCustomStyles;
Y.prototype.scopeNode=Y.prototype.Ca;Y.prototype.unscopeNode=Y.prototype.Fa;Y.prototype.scopeForNode=Y.prototype.Ba;Y.prototype.currentScopeForNode=Y.prototype.sa;Y.prototype.prepareAdoptedCssText=Y.prototype.za;Object.defineProperties(Y.prototype,{nativeShadow:{get:function(){return R}},nativeCss:{get:function(){return S}}});var Z=new Y,Nf,Of;window.ShadyCSS&&(Nf=window.ShadyCSS.ApplyShim,Of=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Z,prepareTemplate:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Z.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Z.flushCustomStyles();Z.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Z.flushCustomStyles();Z.styleSubtree(a,b)},styleElement:function(a){Z.flushCustomStyles();Z.styleElement(a)},styleDocument:function(a){Z.flushCustomStyles();Z.styleDocument(a)},flushCustomStyles:function(){Z.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Z.getComputedStyleValue(a,b)},nativeCss:S,nativeShadow:R,cssBuild:be,disableRuntime:ce};Nf&&(window.ShadyCSS.ApplyShim=Nf);Of&&(window.ShadyCSS.CustomStyleInterface=Of);var Pf=window.document;window.WebComponents=window.WebComponents||{};function Qf(){requestAnimationFrame(function(){window.WebComponents.ready=!0;window.document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})}function Rf(){Qf();Pf.removeEventListener("readystatechange",Rf)}"loading"!==Pf.readyState?Qf():Pf.addEventListener("readystatechange",Rf);}).call(this);

//# sourceMappingURL=webcomponents-sd-ce.js.map
