/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){'use strict';var aa=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function m(b){var a=aa.has(b);b=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(b);return!a&&b}function n(b){var a=b.isConnected;if(void 0!==a)return a;for(;b&&!(b.__CE_isImportDocument||b instanceof Document);)b=b.parentNode||(window.ShadowRoot&&b instanceof ShadowRoot?b.host:void 0);return!(!b||!(b.__CE_isImportDocument||b instanceof Document))}
function q(b,a){for(;a&&a!==b&&!a.nextSibling;)a=a.parentNode;return a&&a!==b?a.nextSibling:null}
function r(b,a,c){c=void 0===c?new Set:c;for(var e=b;e;){if(e.nodeType===Node.ELEMENT_NODE){var d=e;a(d);var f=d.localName;if("link"===f&&"import"===d.getAttribute("rel")){e=d.import;if(e instanceof Node&&!c.has(e))for(c.add(e),e=e.firstChild;e;e=e.nextSibling)r(e,a,c);e=q(b,d);continue}else if("template"===f){e=q(b,d);continue}if(d=d.__CE_shadowRoot)for(d=d.firstChild;d;d=d.nextSibling)r(d,a,c)}e=e.firstChild?e.firstChild:q(b,e)}}function t(b,a,c){b[a]=c};function u(){this.g=new Map;this.j=new Map;this.i=[];this.h=!1}function ba(b,a,c){b.g.set(a,c);b.j.set(c.constructorFunction,c)}function v(b,a){b.h=!0;b.i.push(a)}function w(b,a){b.h&&r(a,function(c){return y(b,c)})}function y(b,a){if(b.h&&!a.__CE_patched){a.__CE_patched=!0;for(var c=0;c<b.i.length;c++)b.i[c](a)}}function z(b,a){var c=[];r(a,function(d){return c.push(d)});for(a=0;a<c.length;a++){var e=c[a];1===e.__CE_state?b.connectedCallback(e):A(b,e)}}
function B(b,a){var c=[];r(a,function(d){return c.push(d)});for(a=0;a<c.length;a++){var e=c[a];1===e.__CE_state&&b.disconnectedCallback(e)}}
function C(b,a,c){c=void 0===c?{}:c;var e=c.A||new Set,d=c.upgrade||function(g){return A(b,g)},f=[];r(a,function(g){if("link"===g.localName&&"import"===g.getAttribute("rel")){var h=g.import;h instanceof Node&&(h.__CE_isImportDocument=!0,h.__CE_hasRegistry=!0);h&&"complete"===h.readyState?h.__CE_documentLoadHandled=!0:g.addEventListener("load",function(){var k=g.import;if(!k.__CE_documentLoadHandled){k.__CE_documentLoadHandled=!0;var l=new Set(e);l.delete(k);C(b,k,{A:l,upgrade:d})}})}else f.push(g)},
e);if(b.h)for(a=0;a<f.length;a++)y(b,f[a]);for(a=0;a<f.length;a++)d(f[a])}
function A(b,a){if(void 0===a.__CE_state){var c=a.ownerDocument;if(c.defaultView||c.__CE_isImportDocument&&c.__CE_hasRegistry)if(c=b.g.get(a.localName)){c.constructionStack.push(a);var e=c.constructorFunction;try{try{if(new e!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(g){throw a.__CE_state=2,g;}a.__CE_state=1;a.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,e=0;e<c.length;e++){var d=
c[e],f=a.getAttribute(d);null!==f&&b.attributeChangedCallback(a,d,null,f,null)}n(a)&&b.connectedCallback(a)}}}u.prototype.connectedCallback=function(b){var a=b.__CE_definition;a.connectedCallback&&a.connectedCallback.call(b)};u.prototype.disconnectedCallback=function(b){var a=b.__CE_definition;a.disconnectedCallback&&a.disconnectedCallback.call(b)};
u.prototype.attributeChangedCallback=function(b,a,c,e,d){var f=b.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(a)&&f.attributeChangedCallback.call(b,a,c,e,d)};function D(b){var a=document;this.i=b;this.g=a;this.h=void 0;C(this.i,this.g);"loading"===this.g.readyState&&(this.h=new MutationObserver(this.j.bind(this)),this.h.observe(this.g,{childList:!0,subtree:!0}))}function E(b){b.h&&b.h.disconnect()}D.prototype.j=function(b){var a=this.g.readyState;"interactive"!==a&&"complete"!==a||E(this);for(a=0;a<b.length;a++)for(var c=b[a].addedNodes,e=0;e<c.length;e++)C(this.i,c[e])};function ca(){var b=this;this.h=this.g=void 0;this.i=new Promise(function(a){b.h=a;b.g&&a(b.g)})}function F(b){if(b.g)throw Error("Already resolved.");b.g=void 0;b.h&&b.h(void 0)};function G(b){this.i=!1;this.g=b;this.m=new Map;this.j=function(a){return a()};this.h=!1;this.l=[];this.u=new D(b)}
G.prototype.o=function(b,a){var c=this;if(!(a instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!m(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(this.g.g.get(b))throw Error("A custom element with name '"+b+"' has already been defined.");if(this.i)throw Error("A custom element is already being defined.");this.i=!0;try{var e=function(p){var x=d[p];if(void 0!==x&&!(x instanceof Function))throw Error("The '"+p+"' callback must be a function.");
return x},d=a.prototype;if(!(d instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=e("connectedCallback");var g=e("disconnectedCallback");var h=e("adoptedCallback");var k=e("attributeChangedCallback");var l=a.observedAttributes||[]}catch(p){return}finally{this.i=!1}a={localName:b,constructorFunction:a,connectedCallback:f,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]};ba(this.g,
b,a);this.l.push(a);this.h||(this.h=!0,this.j(function(){return da(c)}))};G.prototype.upgrade=function(b){C(this.g,b)};
function da(b){if(!1!==b.h){b.h=!1;for(var a=b.l,c=[],e=new Map,d=0;d<a.length;d++)e.set(a[d].localName,[]);C(b.g,document,{upgrade:function(h){if(void 0===h.__CE_state){var k=h.localName,l=e.get(k);l?l.push(h):b.g.g.get(k)&&c.push(h)}}});for(d=0;d<c.length;d++)A(b.g,c[d]);for(;0<a.length;){var f=a.shift();d=f.localName;f=e.get(f.localName);for(var g=0;g<f.length;g++)A(b.g,f[g]);(d=b.m.get(d))&&F(d)}}}G.prototype.get=function(b){if(b=this.g.g.get(b))return b.constructorFunction};
G.prototype.s=function(b){if(!m(b))return Promise.reject(new SyntaxError("'"+b+"' is not a valid custom element name."));var a=this.m.get(b);if(a)return a.i;a=new ca;this.m.set(b,a);this.g.g.get(b)&&!this.l.some(function(c){return c.localName===b})&&F(a);return a.i};G.prototype.v=function(b){E(this.u);var a=this.j;this.j=function(c){return b(function(){return a(c)})}};window.CustomElementRegistry=G;G.prototype.define=G.prototype.o;G.prototype.upgrade=G.prototype.upgrade;G.prototype.get=G.prototype.get;
G.prototype.whenDefined=G.prototype.s;G.prototype.polyfillWrapFlushCallback=G.prototype.v;var H=window.Document.prototype.createElement,I=window.Document.prototype.createElementNS,ea=window.Document.prototype.importNode,fa=window.Document.prototype.prepend,ha=window.Document.prototype.append,ia=window.DocumentFragment.prototype.prepend,ja=window.DocumentFragment.prototype.append,J=window.Node.prototype.cloneNode,K=window.Node.prototype.appendChild,L=window.Node.prototype.insertBefore,M=window.Node.prototype.removeChild,N=window.Node.prototype.replaceChild,O=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),P=window.Element.prototype.attachShadow,Q=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),R=window.Element.prototype.getAttribute,S=window.Element.prototype.setAttribute,ka=window.Element.prototype.removeAttribute,T=window.Element.prototype.getAttributeNS,la=window.Element.prototype.setAttributeNS,ma=window.Element.prototype.removeAttributeNS,na=window.Element.prototype.insertAdjacentElement,oa=window.Element.prototype.insertAdjacentHTML,pa=window.Element.prototype.prepend,
qa=window.Element.prototype.append,U=window.Element.prototype.before,ra=window.Element.prototype.after,sa=window.Element.prototype.replaceWith,ta=window.Element.prototype.remove,ua=window.HTMLElement,V=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),va=window.HTMLElement.prototype.insertAdjacentElement,wa=window.HTMLElement.prototype.insertAdjacentHTML;var xa=new function(){};function ya(){var b=W;window.HTMLElement=function(){function a(){var c=this.constructor,e=b.j.get(c);if(!e)throw Error("The custom element being constructed was not registered with `customElements`.");var d=e.constructionStack;if(0===d.length)return d=H.call(document,e.localName),Object.setPrototypeOf(d,c.prototype),d.__CE_state=1,d.__CE_definition=e,y(b,d),d;e=d.length-1;var f=d[e];if(f===xa)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
d[e]=xa;Object.setPrototypeOf(f,c.prototype);y(b,f);return f}a.prototype=ua.prototype;Object.defineProperty(a.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:a});return a}()};function X(b,a,c){function e(d){return function(f){for(var g=[],h=0;h<arguments.length;++h)g[h]=arguments[h];h=[];for(var k=[],l=0;l<g.length;l++){var p=g[l];p instanceof Element&&n(p)&&k.push(p);if(p instanceof DocumentFragment)for(p=p.firstChild;p;p=p.nextSibling)h.push(p);else h.push(p)}d.apply(this,g);for(g=0;g<k.length;g++)B(b,k[g]);if(n(this))for(g=0;g<h.length;g++)k=h[g],k instanceof Element&&z(b,k)}}void 0!==c.prepend&&t(a,"prepend",e(c.prepend));void 0!==c.append&&t(a,"append",e(c.append))}
;function za(){var b=W;t(Document.prototype,"createElement",function(a){if(this.__CE_hasRegistry){var c=b.g.get(a);if(c)return new c.constructorFunction}a=H.call(this,a);y(b,a);return a});t(Document.prototype,"importNode",function(a,c){a=ea.call(this,a,!!c);this.__CE_hasRegistry?C(b,a):w(b,a);return a});t(Document.prototype,"createElementNS",function(a,c){if(this.__CE_hasRegistry&&(null===a||"http://www.w3.org/1999/xhtml"===a)){var e=b.g.get(c);if(e)return new e.constructorFunction}a=I.call(this,a,
c);y(b,a);return a});X(b,Document.prototype,{prepend:fa,append:ha})};function Aa(){function b(c,e){Object.defineProperty(c,"textContent",{enumerable:e.enumerable,configurable:!0,get:e.get,set:function(d){if(this.nodeType===Node.TEXT_NODE)e.set.call(this,d);else{var f=void 0;if(this.firstChild){var g=this.childNodes,h=g.length;if(0<h&&n(this)){f=Array(h);for(var k=0;k<h;k++)f[k]=g[k]}}e.set.call(this,d);if(f)for(d=0;d<f.length;d++)B(a,f[d])}}})}var a=W;t(Node.prototype,"insertBefore",function(c,e){if(c instanceof DocumentFragment){var d=Array.prototype.slice.apply(c.childNodes);
c=L.call(this,c,e);if(n(this))for(e=0;e<d.length;e++)z(a,d[e]);return c}d=n(c);e=L.call(this,c,e);d&&B(a,c);n(this)&&z(a,c);return e});t(Node.prototype,"appendChild",function(c){if(c instanceof DocumentFragment){var e=Array.prototype.slice.apply(c.childNodes);c=K.call(this,c);if(n(this))for(var d=0;d<e.length;d++)z(a,e[d]);return c}e=n(c);d=K.call(this,c);e&&B(a,c);n(this)&&z(a,c);return d});t(Node.prototype,"cloneNode",function(c){c=J.call(this,!!c);this.ownerDocument.__CE_hasRegistry?C(a,c):w(a,
c);return c});t(Node.prototype,"removeChild",function(c){var e=n(c),d=M.call(this,c);e&&B(a,c);return d});t(Node.prototype,"replaceChild",function(c,e){if(c instanceof DocumentFragment){var d=Array.prototype.slice.apply(c.childNodes);c=N.call(this,c,e);if(n(this))for(B(a,e),e=0;e<d.length;e++)z(a,d[e]);return c}d=n(c);var f=N.call(this,c,e),g=n(this);g&&B(a,e);d&&B(a,c);g&&z(a,c);return f});O&&O.get?b(Node.prototype,O):v(a,function(c){b(c,{enumerable:!0,configurable:!0,get:function(){for(var e=[],
d=0;d<this.childNodes.length;d++)e.push(this.childNodes[d].textContent);return e.join("")},set:function(e){for(;this.firstChild;)M.call(this,this.firstChild);K.call(this,document.createTextNode(e))}})})};function Ba(b){function a(e){return function(d){for(var f=[],g=0;g<arguments.length;++g)f[g]=arguments[g];g=[];for(var h=[],k=0;k<f.length;k++){var l=f[k];l instanceof Element&&n(l)&&h.push(l);if(l instanceof DocumentFragment)for(l=l.firstChild;l;l=l.nextSibling)g.push(l);else g.push(l)}e.apply(this,f);for(f=0;f<h.length;f++)B(b,h[f]);if(n(this))for(f=0;f<g.length;f++)h=g[f],h instanceof Element&&z(b,h)}}var c=Element.prototype;void 0!==U&&t(c,"before",a(U));void 0!==U&&t(c,"after",a(ra));void 0!==
sa&&t(c,"replaceWith",function(e){for(var d=[],f=0;f<arguments.length;++f)d[f]=arguments[f];f=[];for(var g=[],h=0;h<d.length;h++){var k=d[h];k instanceof Element&&n(k)&&g.push(k);if(k instanceof DocumentFragment)for(k=k.firstChild;k;k=k.nextSibling)f.push(k);else f.push(k)}h=n(this);sa.apply(this,d);for(d=0;d<g.length;d++)B(b,g[d]);if(h)for(B(b,this),d=0;d<f.length;d++)g=f[d],g instanceof Element&&z(b,g)});void 0!==ta&&t(c,"remove",function(){var e=n(this);ta.call(this);e&&B(b,this)})};function Ca(){function b(d,f){Object.defineProperty(d,"innerHTML",{enumerable:f.enumerable,configurable:!0,get:f.get,set:function(g){var h=this,k=void 0;n(this)&&(k=[],r(this,function(x){x!==h&&k.push(x)}));f.set.call(this,g);if(k)for(var l=0;l<k.length;l++){var p=k[l];1===p.__CE_state&&e.disconnectedCallback(p)}this.ownerDocument.__CE_hasRegistry?C(e,this):w(e,this);return g}})}function a(d,f){t(d,"insertAdjacentElement",function(g,h){var k=n(h);g=f.call(this,g,h);k&&B(e,h);n(g)&&z(e,h);return g})}
function c(d,f){function g(h,k){for(var l=[];h!==k;h=h.nextSibling)l.push(h);for(k=0;k<l.length;k++)C(e,l[k])}t(d,"insertAdjacentHTML",function(h,k){h=h.toLowerCase();if("beforebegin"===h){var l=this.previousSibling;f.call(this,h,k);g(l||this.parentNode.firstChild,this)}else if("afterbegin"===h)l=this.firstChild,f.call(this,h,k),g(this.firstChild,l);else if("beforeend"===h)l=this.lastChild,f.call(this,h,k),g(l||this.firstChild,null);else if("afterend"===h)l=this.nextSibling,f.call(this,h,k),g(this.nextSibling,
l);else throw new SyntaxError("The value provided ("+String(h)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");})}var e=W;P&&t(Element.prototype,"attachShadow",function(d){return this.__CE_shadowRoot=d=P.call(this,d)});Q&&Q.get?b(Element.prototype,Q):V&&V.get?b(HTMLElement.prototype,V):v(e,function(d){b(d,{enumerable:!0,configurable:!0,get:function(){return J.call(this,!0).innerHTML},set:function(f){var g="template"===this.localName,h=g?this.content:this,k=I.call(document,
this.namespaceURI,this.localName);for(k.innerHTML=f;0<h.childNodes.length;)M.call(h,h.childNodes[0]);for(f=g?k.content:k;0<f.childNodes.length;)K.call(h,f.childNodes[0])}})});t(Element.prototype,"setAttribute",function(d,f){if(1!==this.__CE_state)return S.call(this,d,f);var g=R.call(this,d);S.call(this,d,f);f=R.call(this,d);e.attributeChangedCallback(this,d,g,f,null)});t(Element.prototype,"setAttributeNS",function(d,f,g){if(1!==this.__CE_state)return la.call(this,d,f,g);var h=T.call(this,d,f);la.call(this,
d,f,g);g=T.call(this,d,f);e.attributeChangedCallback(this,f,h,g,d)});t(Element.prototype,"removeAttribute",function(d){if(1!==this.__CE_state)return ka.call(this,d);var f=R.call(this,d);ka.call(this,d);null!==f&&e.attributeChangedCallback(this,d,f,null,null)});t(Element.prototype,"removeAttributeNS",function(d,f){if(1!==this.__CE_state)return ma.call(this,d,f);var g=T.call(this,d,f);ma.call(this,d,f);var h=T.call(this,d,f);g!==h&&e.attributeChangedCallback(this,f,g,h,d)});va?a(HTMLElement.prototype,
va):na?a(Element.prototype,na):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");wa?c(HTMLElement.prototype,wa):oa?c(Element.prototype,oa):console.warn("Custom Elements: `Element#insertAdjacentHTML` was not patched.");X(e,Element.prototype,{prepend:pa,append:qa});Ba(e)};/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var Y=window.customElements;if(!Y||Y.forcePolyfill||"function"!=typeof Y.define||"function"!=typeof Y.get){var W=new u;ya();za();X(W,DocumentFragment.prototype,{prepend:ia,append:ja});Aa();Ca();document.__CE_hasRegistry=!0;var customElements=new G(W);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var Z=window.document;window.WebComponents=window.WebComponents||{};function Da(){window.WebComponents.ready=!0;window.document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))}function Ea(){Da();Z.removeEventListener("readystatechange",Ea)}"loading"!==Z.readyState?Da():Z.addEventListener("readystatechange",Ea);}).call(this);

//# sourceMappingURL=webcomponents-ce.js.map
