/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';(function(b){function a(e,h){if("function"===typeof window.CustomEvent)return new CustomEvent(e,h);var k=document.createEvent("CustomEvent");k.initCustomEvent(e,!!h.bubbles,!!h.cancelable,h.detail);return k}function c(e){if(V)return e.ownerDocument!==document?e.ownerDocument:null;var h=e.__importDoc;if(!h&&e.parentNode){h=e.parentNode;if("function"===typeof h.closest)h=h.closest("link[rel=import]");else for(;!m(h)&&(h=h.parentNode););e.__importDoc=h}return h}function f(e){var h=t(document,
"link[rel=import]:not([import-dependency])"),k=h.length;k?x(h,function(p){return l(p,function(){0===--k&&e()})}):e()}function d(e){function h(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",h),e())}document.addEventListener("readystatechange",h);h()}function g(e){d(function(){return f(function(){return e&&e()})})}function l(e,h){if(e.__loaded)h&&h();else if("script"===e.localName&&!e.src||"style"===e.localName&&!e.firstChild||"style"===e.localName&&
"http://www.w3.org/2000/svg"===e.namespaceURI)e.__loaded=!0,h&&h();else{var k=function(p){e.removeEventListener(p.type,k);e.__loaded=!0;h&&h()};e.addEventListener("load",k);"style"===e.localName&&(W||N)||e.addEventListener("error",k)}}function m(e){return e.nodeType===Node.ELEMENT_NODE&&"link"===e.localName&&"import"===e.rel}function n(){var e=this;this.g={};this.h=0;this.i=new MutationObserver(function(h){return e.B(h)});this.i.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}
function r(e){x(t(e,"template"),function(h){h instanceof HTMLTemplateElement&&(x(t(h.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]'),function(k){var p=document.createElement("script");x(k.attributes,function(u){return p.setAttribute(u.name,u.value)});p.textContent=k.textContent;k.parentNode.replaceChild(p,k)}),r(h.content))})}function t(e,h){return e.childNodes.length?e.querySelectorAll(h):La}function x(e,h,k){var p=e?e.length:
0,u=k?-1:1;for(k=k?p-1:0;k<p&&0<=k;k+=u)h(e[k],k)}var G=document.createElement("link"),V="import"in G,La=G.querySelectorAll("*"),X=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return X||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var Ma=/(url\()([^)]*)(\))/g,Na=/(@import[\s]+(?!url\())([^;]*)(;)/g,Oa=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,A={L:function(e,h){e.href&&e.setAttribute("href",
A.s(e.getAttribute("href"),h));e.src&&e.setAttribute("src",A.s(e.getAttribute("src"),h));if("style"===e.localName){var k=A.F(e.textContent,h,Ma);e.textContent=A.F(k,h,Na)}},F:function(e,h,k){return e.replace(k,function(p,u,q,v){p=q.replace(/["']/g,"");h&&(p=A.s(p,h));return u+"'"+p+"'"+v})},s:function(e,h){if(void 0===A.u){A.u=!1;try{var k=new URL("b","http://a");k.pathname="c%20d";A.u="http://a/c%20d"===k.href}catch(p){}}if(A.u)return(new URL(e,h)).href;k=A.J;k||(k=document.implementation.createHTMLDocument("temp"),
A.J=k,k.D=k.createElement("base"),k.head.appendChild(k.D),k.C=k.createElement("a"));k.D.href=h;k.C.href=e;return k.C.href||e}},Pa={async:!0,load:function(e,h,k){if(e)if(e.match(/^data:/)){var p=e.split(","),u=p[1];u=-1<p[0].indexOf(";base64")?atob(u):decodeURIComponent(u);h(u)}else{var q=function(C){C=void 0===C?0:C;return I(0===C).then(function(E){h(E.M,E.P)},function(E){console.error(E);if(2<=C)k();else return v(100*Math.random()*Math.pow(2,C)).then(function(){return q(C+1)})})},v=function(C){return new Promise(function(E){return setTimeout(E,
C)})},I=function(C){var E=null;return fetch(e,{cache:C?"default":"reload"}).then(function(J){if(!J.ok)throw Error("HTTP "+J.status);E=J.url;return J.text()}).then(function(J){return{M:J,O:E}})};q()}else k()}},W=/Trident/.test(navigator.userAgent),N=/Edge\/\d./i.test(navigator.userAgent);n.prototype.loadImports=function(e){var h=this;e=t(e,"link[rel=import]");x(e,function(k){return h.l(k)})};n.prototype.l=function(e){var h=this,k=e.href;if(void 0!==this.g[k]){var p=this.g[k];p&&p.__loaded&&(e.__import=
p,this.j(e))}else this.h++,this.g[k]="pending",Pa.load(k,function(u,q){u=h.G(u,q||k);h.g[k]=u;h.h--;h.loadImports(u);h.m()},function(){h.g[k]=null;h.h--;h.m()})};n.prototype.G=function(e,h){var k=this;if(!e)return document.createDocumentFragment();if(W||N)e=e.replace(Oa,function(q,v,I){return-1===q.indexOf("type=")?v+" type=import-disable "+I:q});var p=document.createElement("template");p.innerHTML=e;if(p.content)e=p.content,r(e);else for(e=document.createDocumentFragment();p.firstChild;)e.appendChild(p.firstChild);
if(p=e.querySelector("base"))h=A.s(p.getAttribute("href"),h),p.removeAttribute("href");p=t(e,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]');var u=0;x(p,function(q){l(q);A.L(q,h);if("style"===q.localName&&k.o(q)){var v=k.v(q);l(v);q.parentNode.replaceChild(v,q);q=v}q.setAttribute("import-dependency","");if("script"===
q.localName&&!q.src&&q.textContent){if("module"===q.type)throw Error("Inline module scripts are not supported in HTML Imports.");q.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(q.textContent+("\n//# sourceURL="+h+(u?"-"+u:"")+".js\n")));q.textContent="";u++}});return e};n.prototype.o=function(e){return N&&-1<e.textContent.indexOf("@import")};n.prototype.v=function(e){var h=e.ownerDocument.createElement("style");h.textContent=e.textContent;x(e.attributes,function(k){return h.setAttribute(k.name,
k.value)});return h};n.prototype.m=function(){var e=this;if(!this.h){this.i.disconnect();this.flatten(document);var h=!1,k=!1,p=function(){k&&h&&(e.loadImports(document),e.h||(e.i.observe(document.head,{childList:!0,subtree:!0}),e.A()))};this.I(function(){k=!0;p()});this.H(function(){h=!0;p()})}};n.prototype.flatten=function(e){var h=this;e=t(e,"link[rel=import]");x(e,function(k){var p=h.g[k.href];(k.__import=p)&&p.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(h.g[k.href]=k,k.readyState="loading",k.__import=
k,h.flatten(p),k.appendChild(p))})};n.prototype.H=function(e){function h(u){if(u<p){var q=k[u],v=document.createElement("script");q.removeAttribute("import-dependency");x(q.attributes,function(I){return v.setAttribute(I.name,I.value)});X=v;q.parentNode.replaceChild(v,q);l(v,function(){X=null;h(u+1)})}else e()}var k=t(document,"script[import-dependency]"),p=k.length;h(0)};n.prototype.I=function(e){var h=this,k=t(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),p=k.length;
if(p){var u=(W||N)&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");x(k,function(q){u&&h.o(q)&&q.ownerDocument.defaultView!==window.top&&(q.__loaded=!0);l(q,function(){q.removeAttribute("import-dependency");0===--p&&e()});if(u&&q.parentNode!==document.head){var v=document.createElement(q.localName);v.__appliedElement=q;v.setAttribute("type","import-placeholder");q.parentNode.insertBefore(v,q.nextSibling);for(v=c(q);v&&c(v);)v=c(v);v.parentNode!==document.head&&(v=null);
document.head.insertBefore(q,v);q.removeAttribute("type")}})}else e()};n.prototype.A=function(){var e=this,h=t(document,"link[rel=import]");x(h,function(k){return e.j(k)},!0)};n.prototype.j=function(e){e.__loaded||(e.__loaded=!0,e.import&&(e.import.readyState="complete"),e.dispatchEvent(a(e.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};n.prototype.B=function(e){var h=this;x(e,function(k){return x(k.addedNodes,function(p){p&&p.nodeType===Node.ELEMENT_NODE&&(m(p)?h.l(p):h.loadImports(p))})})};
var Y=null;if(V)G=t(document,"link[rel=import]"),x(G,function(e){e.import&&"loading"===e.import.readyState||(e.__loaded=!0)}),G=function(e){e=e.target;m(e)&&(e.__loaded=!0)},document.addEventListener("load",G,!0),document.addEventListener("error",G,!0);else{var M=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!M||M.configurable?Node:Element).prototype,"baseURI",{get:function(){var e=m(this)?this:c(this);return e?e.href:M&&M.get?M.get.call(this):(document.querySelector("base")||
window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});d(function(){Y=new n})}g(function(){return document.dispatchEvent(a("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});b.useNative=V;b.whenReady=g;b.importForElement=c;b.loadImports=function(e){Y&&Y.loadImports(e)}})(window.HTMLImports=window.HTMLImports||{});var aa=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function ba(b){var a=aa.has(b);b=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(b);return!a&&b}function w(b){var a=b.isConnected;if(void 0!==a)return a;for(;b&&!(b.__CE_isImportDocument||b instanceof Document);)b=b.parentNode||(window.ShadowRoot&&b instanceof ShadowRoot?b.host:void 0);return!(!b||!(b.__CE_isImportDocument||b instanceof Document))}
function y(b,a){for(;a&&a!==b&&!a.nextSibling;)a=a.parentNode;return a&&a!==b?a.nextSibling:null}
function z(b,a,c){c=void 0===c?new Set:c;for(var f=b;f;){if(f.nodeType===Node.ELEMENT_NODE){var d=f;a(d);var g=d.localName;if("link"===g&&"import"===d.getAttribute("rel")){f=d.import;if(f instanceof Node&&!c.has(f))for(c.add(f),f=f.firstChild;f;f=f.nextSibling)z(f,a,c);f=y(b,d);continue}else if("template"===g){f=y(b,d);continue}if(d=d.__CE_shadowRoot)for(d=d.firstChild;d;d=d.nextSibling)z(d,a,c)}f=f.firstChild?f.firstChild:y(b,f)}}function B(b,a,c){b[a]=c};function D(){this.g=new Map;this.j=new Map;this.i=[];this.h=!1}function ca(b,a,c){b.g.set(a,c);b.j.set(c.constructorFunction,c)}function da(b,a){b.h=!0;b.i.push(a)}function ea(b,a){b.h&&z(a,function(c){return F(b,c)})}function F(b,a){if(b.h&&!a.__CE_patched){a.__CE_patched=!0;for(var c=0;c<b.i.length;c++)b.i[c](a)}}function H(b,a){var c=[];z(a,function(d){return c.push(d)});for(a=0;a<c.length;a++){var f=c[a];1===f.__CE_state?b.connectedCallback(f):K(b,f)}}
function L(b,a){var c=[];z(a,function(d){return c.push(d)});for(a=0;a<c.length;a++){var f=c[a];1===f.__CE_state&&b.disconnectedCallback(f)}}
function O(b,a,c){c=void 0===c?{}:c;var f=c.N||new Set,d=c.upgrade||function(l){return K(b,l)},g=[];z(a,function(l){if("link"===l.localName&&"import"===l.getAttribute("rel")){var m=l.import;m instanceof Node&&(m.__CE_isImportDocument=!0,m.__CE_hasRegistry=!0);m&&"complete"===m.readyState?m.__CE_documentLoadHandled=!0:l.addEventListener("load",function(){var n=l.import;if(!n.__CE_documentLoadHandled){n.__CE_documentLoadHandled=!0;var r=new Set(f);r.delete(n);O(b,n,{N:r,upgrade:d})}})}else g.push(l)},
f);if(b.h)for(a=0;a<g.length;a++)F(b,g[a]);for(a=0;a<g.length;a++)d(g[a])}
function K(b,a){if(void 0===a.__CE_state){var c=a.ownerDocument;if(c.defaultView||c.__CE_isImportDocument&&c.__CE_hasRegistry)if(c=b.g.get(a.localName)){c.constructionStack.push(a);var f=c.constructorFunction;try{try{if(new f!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(l){throw a.__CE_state=2,l;}a.__CE_state=1;a.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,f=0;f<c.length;f++){var d=
c[f],g=a.getAttribute(d);null!==g&&b.attributeChangedCallback(a,d,null,g,null)}w(a)&&b.connectedCallback(a)}}}D.prototype.connectedCallback=function(b){var a=b.__CE_definition;a.connectedCallback&&a.connectedCallback.call(b)};D.prototype.disconnectedCallback=function(b){var a=b.__CE_definition;a.disconnectedCallback&&a.disconnectedCallback.call(b)};
D.prototype.attributeChangedCallback=function(b,a,c,f,d){var g=b.__CE_definition;g.attributeChangedCallback&&-1<g.observedAttributes.indexOf(a)&&g.attributeChangedCallback.call(b,a,c,f,d)};function fa(b){var a=document;this.i=b;this.g=a;this.h=void 0;O(this.i,this.g);"loading"===this.g.readyState&&(this.h=new MutationObserver(this.j.bind(this)),this.h.observe(this.g,{childList:!0,subtree:!0}))}function ha(b){b.h&&b.h.disconnect()}fa.prototype.j=function(b){var a=this.g.readyState;"interactive"!==a&&"complete"!==a||ha(this);for(a=0;a<b.length;a++)for(var c=b[a].addedNodes,f=0;f<c.length;f++)O(this.i,c[f])};function ia(){var b=this;this.h=this.g=void 0;this.i=new Promise(function(a){b.h=a;b.g&&a(b.g)})}function ja(b){if(b.g)throw Error("Already resolved.");b.g=void 0;b.h&&b.h(void 0)};function P(b){this.i=!1;this.g=b;this.m=new Map;this.j=function(a){return a()};this.h=!1;this.l=[];this.A=new fa(b)}
P.prototype.o=function(b,a){var c=this;if(!(a instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!ba(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(this.g.g.get(b))throw Error("A custom element with name '"+b+"' has already been defined.");if(this.i)throw Error("A custom element is already being defined.");this.i=!0;try{var f=function(t){var x=d[t];if(void 0!==x&&!(x instanceof Function))throw Error("The '"+t+"' callback must be a function.");
return x},d=a.prototype;if(!(d instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var g=f("connectedCallback");var l=f("disconnectedCallback");var m=f("adoptedCallback");var n=f("attributeChangedCallback");var r=a.observedAttributes||[]}catch(t){return}finally{this.i=!1}a={localName:b,constructorFunction:a,connectedCallback:g,disconnectedCallback:l,adoptedCallback:m,attributeChangedCallback:n,observedAttributes:r,constructionStack:[]};ca(this.g,
b,a);this.l.push(a);this.h||(this.h=!0,this.j(function(){return ka(c)}))};P.prototype.upgrade=function(b){O(this.g,b)};
function ka(b){if(!1!==b.h){b.h=!1;for(var a=b.l,c=[],f=new Map,d=0;d<a.length;d++)f.set(a[d].localName,[]);O(b.g,document,{upgrade:function(m){if(void 0===m.__CE_state){var n=m.localName,r=f.get(n);r?r.push(m):b.g.g.get(n)&&c.push(m)}}});for(d=0;d<c.length;d++)K(b.g,c[d]);for(;0<a.length;){var g=a.shift();d=g.localName;g=f.get(g.localName);for(var l=0;l<g.length;l++)K(b.g,g[l]);(d=b.m.get(d))&&ja(d)}}}P.prototype.get=function(b){if(b=this.g.g.get(b))return b.constructorFunction};
P.prototype.v=function(b){if(!ba(b))return Promise.reject(new SyntaxError("'"+b+"' is not a valid custom element name."));var a=this.m.get(b);if(a)return a.i;a=new ia;this.m.set(b,a);this.g.g.get(b)&&!this.l.some(function(c){return c.localName===b})&&ja(a);return a.i};P.prototype.B=function(b){ha(this.A);var a=this.j;this.j=function(c){return b(function(){return a(c)})}};window.CustomElementRegistry=P;P.prototype.define=P.prototype.o;P.prototype.upgrade=P.prototype.upgrade;P.prototype.get=P.prototype.get;
P.prototype.whenDefined=P.prototype.v;P.prototype.polyfillWrapFlushCallback=P.prototype.B;var la=window.Document.prototype.createElement,ma=window.Document.prototype.createElementNS,na=window.Document.prototype.importNode,oa=window.Document.prototype.prepend,pa=window.Document.prototype.append,qa=window.DocumentFragment.prototype.prepend,ra=window.DocumentFragment.prototype.append,sa=window.Node.prototype.cloneNode,Q=window.Node.prototype.appendChild,ta=window.Node.prototype.insertBefore,ua=window.Node.prototype.removeChild,va=window.Node.prototype.replaceChild,wa=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),xa=window.Element.prototype.attachShadow,ya=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),za=window.Element.prototype.getAttribute,Aa=window.Element.prototype.setAttribute,Ba=window.Element.prototype.removeAttribute,R=window.Element.prototype.getAttributeNS,Ca=window.Element.prototype.setAttributeNS,Da=window.Element.prototype.removeAttributeNS,Ea=window.Element.prototype.insertAdjacentElement,Fa=window.Element.prototype.insertAdjacentHTML,Ga=window.Element.prototype.prepend,
Ha=window.Element.prototype.append,Ia=window.Element.prototype.before,Ja=window.Element.prototype.after,Ka=window.Element.prototype.replaceWith,Qa=window.Element.prototype.remove,Ra=window.HTMLElement,Sa=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),Ta=window.HTMLElement.prototype.insertAdjacentElement,Ua=window.HTMLElement.prototype.insertAdjacentHTML;var Va=new function(){};function Wa(){var b=S;window.HTMLElement=function(){function a(){var c=this.constructor,f=b.j.get(c);if(!f)throw Error("The custom element being constructed was not registered with `customElements`.");var d=f.constructionStack;if(0===d.length)return d=la.call(document,f.localName),Object.setPrototypeOf(d,c.prototype),d.__CE_state=1,d.__CE_definition=f,F(b,d),d;f=d.length-1;var g=d[f];if(g===Va)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
d[f]=Va;Object.setPrototypeOf(g,c.prototype);F(b,g);return g}a.prototype=Ra.prototype;Object.defineProperty(a.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:a});return a}()};function Xa(b,a,c){function f(d){return function(g){for(var l=[],m=0;m<arguments.length;++m)l[m]=arguments[m];m=[];for(var n=[],r=0;r<l.length;r++){var t=l[r];t instanceof Element&&w(t)&&n.push(t);if(t instanceof DocumentFragment)for(t=t.firstChild;t;t=t.nextSibling)m.push(t);else m.push(t)}d.apply(this,l);for(l=0;l<n.length;l++)L(b,n[l]);if(w(this))for(l=0;l<m.length;l++)n=m[l],n instanceof Element&&H(b,n)}}void 0!==c.prepend&&B(a,"prepend",f(c.prepend));void 0!==c.append&&B(a,"append",f(c.append))}
;function Ya(){var b=S;B(Document.prototype,"createElement",function(a){if(this.__CE_hasRegistry){var c=b.g.get(a);if(c)return new c.constructorFunction}a=la.call(this,a);F(b,a);return a});B(Document.prototype,"importNode",function(a,c){a=na.call(this,a,!!c);this.__CE_hasRegistry?O(b,a):ea(b,a);return a});B(Document.prototype,"createElementNS",function(a,c){if(this.__CE_hasRegistry&&(null===a||"http://www.w3.org/1999/xhtml"===a)){var f=b.g.get(c);if(f)return new f.constructorFunction}a=ma.call(this,
a,c);F(b,a);return a});Xa(b,Document.prototype,{prepend:oa,append:pa})};function Za(){function b(c,f){Object.defineProperty(c,"textContent",{enumerable:f.enumerable,configurable:!0,get:f.get,set:function(d){if(this.nodeType===Node.TEXT_NODE)f.set.call(this,d);else{var g=void 0;if(this.firstChild){var l=this.childNodes,m=l.length;if(0<m&&w(this)){g=Array(m);for(var n=0;n<m;n++)g[n]=l[n]}}f.set.call(this,d);if(g)for(d=0;d<g.length;d++)L(a,g[d])}}})}var a=S;B(Node.prototype,"insertBefore",function(c,f){if(c instanceof DocumentFragment){var d=Array.prototype.slice.apply(c.childNodes);
c=ta.call(this,c,f);if(w(this))for(f=0;f<d.length;f++)H(a,d[f]);return c}d=w(c);f=ta.call(this,c,f);d&&L(a,c);w(this)&&H(a,c);return f});B(Node.prototype,"appendChild",function(c){if(c instanceof DocumentFragment){var f=Array.prototype.slice.apply(c.childNodes);c=Q.call(this,c);if(w(this))for(var d=0;d<f.length;d++)H(a,f[d]);return c}f=w(c);d=Q.call(this,c);f&&L(a,c);w(this)&&H(a,c);return d});B(Node.prototype,"cloneNode",function(c){c=sa.call(this,!!c);this.ownerDocument.__CE_hasRegistry?O(a,c):
ea(a,c);return c});B(Node.prototype,"removeChild",function(c){var f=w(c),d=ua.call(this,c);f&&L(a,c);return d});B(Node.prototype,"replaceChild",function(c,f){if(c instanceof DocumentFragment){var d=Array.prototype.slice.apply(c.childNodes);c=va.call(this,c,f);if(w(this))for(L(a,f),f=0;f<d.length;f++)H(a,d[f]);return c}d=w(c);var g=va.call(this,c,f),l=w(this);l&&L(a,f);d&&L(a,c);l&&H(a,c);return g});wa&&wa.get?b(Node.prototype,wa):da(a,function(c){b(c,{enumerable:!0,configurable:!0,get:function(){for(var f=
[],d=0;d<this.childNodes.length;d++)f.push(this.childNodes[d].textContent);return f.join("")},set:function(f){for(;this.firstChild;)ua.call(this,this.firstChild);Q.call(this,document.createTextNode(f))}})})};function $a(b){function a(f){return function(d){for(var g=[],l=0;l<arguments.length;++l)g[l]=arguments[l];l=[];for(var m=[],n=0;n<g.length;n++){var r=g[n];r instanceof Element&&w(r)&&m.push(r);if(r instanceof DocumentFragment)for(r=r.firstChild;r;r=r.nextSibling)l.push(r);else l.push(r)}f.apply(this,g);for(g=0;g<m.length;g++)L(b,m[g]);if(w(this))for(g=0;g<l.length;g++)m=l[g],m instanceof Element&&H(b,m)}}var c=Element.prototype;void 0!==Ia&&B(c,"before",a(Ia));void 0!==Ia&&B(c,"after",a(Ja));void 0!==
Ka&&B(c,"replaceWith",function(f){for(var d=[],g=0;g<arguments.length;++g)d[g]=arguments[g];g=[];for(var l=[],m=0;m<d.length;m++){var n=d[m];n instanceof Element&&w(n)&&l.push(n);if(n instanceof DocumentFragment)for(n=n.firstChild;n;n=n.nextSibling)g.push(n);else g.push(n)}m=w(this);Ka.apply(this,d);for(d=0;d<l.length;d++)L(b,l[d]);if(m)for(L(b,this),d=0;d<g.length;d++)l=g[d],l instanceof Element&&H(b,l)});void 0!==Qa&&B(c,"remove",function(){var f=w(this);Qa.call(this);f&&L(b,this)})};function ab(){function b(d,g){Object.defineProperty(d,"innerHTML",{enumerable:g.enumerable,configurable:!0,get:g.get,set:function(l){var m=this,n=void 0;w(this)&&(n=[],z(this,function(x){x!==m&&n.push(x)}));g.set.call(this,l);if(n)for(var r=0;r<n.length;r++){var t=n[r];1===t.__CE_state&&f.disconnectedCallback(t)}this.ownerDocument.__CE_hasRegistry?O(f,this):ea(f,this);return l}})}function a(d,g){B(d,"insertAdjacentElement",function(l,m){var n=w(m);l=g.call(this,l,m);n&&L(f,m);w(l)&&H(f,m);return l})}
function c(d,g){function l(m,n){for(var r=[];m!==n;m=m.nextSibling)r.push(m);for(n=0;n<r.length;n++)O(f,r[n])}B(d,"insertAdjacentHTML",function(m,n){m=m.toLowerCase();if("beforebegin"===m){var r=this.previousSibling;g.call(this,m,n);l(r||this.parentNode.firstChild,this)}else if("afterbegin"===m)r=this.firstChild,g.call(this,m,n),l(this.firstChild,r);else if("beforeend"===m)r=this.lastChild,g.call(this,m,n),l(r||this.firstChild,null);else if("afterend"===m)r=this.nextSibling,g.call(this,m,n),l(this.nextSibling,
r);else throw new SyntaxError("The value provided ("+String(m)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");})}var f=S;xa&&B(Element.prototype,"attachShadow",function(d){return this.__CE_shadowRoot=d=xa.call(this,d)});ya&&ya.get?b(Element.prototype,ya):Sa&&Sa.get?b(HTMLElement.prototype,Sa):da(f,function(d){b(d,{enumerable:!0,configurable:!0,get:function(){return sa.call(this,!0).innerHTML},set:function(g){var l="template"===this.localName,m=l?this.content:this,n=ma.call(document,
this.namespaceURI,this.localName);for(n.innerHTML=g;0<m.childNodes.length;)ua.call(m,m.childNodes[0]);for(g=l?n.content:n;0<g.childNodes.length;)Q.call(m,g.childNodes[0])}})});B(Element.prototype,"setAttribute",function(d,g){if(1!==this.__CE_state)return Aa.call(this,d,g);var l=za.call(this,d);Aa.call(this,d,g);g=za.call(this,d);f.attributeChangedCallback(this,d,l,g,null)});B(Element.prototype,"setAttributeNS",function(d,g,l){if(1!==this.__CE_state)return Ca.call(this,d,g,l);var m=R.call(this,d,g);
Ca.call(this,d,g,l);l=R.call(this,d,g);f.attributeChangedCallback(this,g,m,l,d)});B(Element.prototype,"removeAttribute",function(d){if(1!==this.__CE_state)return Ba.call(this,d);var g=za.call(this,d);Ba.call(this,d);null!==g&&f.attributeChangedCallback(this,d,g,null,null)});B(Element.prototype,"removeAttributeNS",function(d,g){if(1!==this.__CE_state)return Da.call(this,d,g);var l=R.call(this,d,g);Da.call(this,d,g);var m=R.call(this,d,g);l!==m&&f.attributeChangedCallback(this,g,l,m,d)});Ta?a(HTMLElement.prototype,
Ta):Ea?a(Element.prototype,Ea):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");Ua?c(HTMLElement.prototype,Ua):Fa?c(Element.prototype,Fa):console.warn("Custom Elements: `Element#insertAdjacentHTML` was not patched.");Xa(f,Element.prototype,{prepend:Ga,append:Ha});$a(f)};var T=window.customElements;if(!T||T.forcePolyfill||"function"!=typeof T.define||"function"!=typeof T.get){var S=new D;Wa();Ya();Xa(S,DocumentFragment.prototype,{prepend:qa,append:ra});Za();ab();document.__CE_hasRegistry=!0;var customElements=new P(S);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var bb=window.customElements,U=window.HTMLImports,cb=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(bb&&bb.polyfillWrapFlushCallback){var Z,db=function(){if(Z){cb.K&&cb.K(window.document);var b=Z;Z=null;b();return!0}},eb=U.whenReady;bb.polyfillWrapFlushCallback(function(b){Z=b;eb(db)});U.whenReady=function(b){eb(function(){db()?U.whenReady(b):b()})}}
U.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var fb=document.createElement("style");fb.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var gb=document.querySelector("head");gb.insertBefore(fb,gb.firstChild);/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
}).call(this);

//# sourceMappingURL=webcomponents-hi-ce.js.map
