/**
@license @nocompile
Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';var v;function ca(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function da(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:ca(a)}}function ea(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}
function fa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ha=fa(this);
(function(a){function b(k,n){if("function"===typeof window.CustomEvent)return new CustomEvent(k,n);var p=document.createEvent("CustomEvent");p.initCustomEvent(k,!!n.bubbles,!!n.cancelable,n.detail);return p}function c(k){if(Q)return k.ownerDocument!==document?k.ownerDocument:null;var n=k.__importDoc;if(!n&&k.parentNode){n=k.parentNode;if("function"===typeof n.closest)n=n.closest("link[rel=import]");else for(;!h(n)&&(n=n.parentNode););k.__importDoc=n}return n}function d(k){var n=q(document,"link[rel=import]:not([import-dependency])"),
p=n.length;p?t(n,function(r){return g(r,function(){0===--p&&k()})}):k()}function e(k){function n(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",n),k())}document.addEventListener("readystatechange",n);n()}function f(k){e(function(){return d(function(){return k&&k()})})}function g(k,n){if(k.__loaded)n&&n();else if("script"===k.localName&&!k.src||"style"===k.localName&&!k.firstChild||"style"===k.localName&&"http://www.w3.org/2000/svg"===k.namespaceURI)k.__loaded=
!0,n&&n();else{var p=function(r){k.removeEventListener(r.type,p);k.__loaded=!0;n&&n()};k.addEventListener("load",p);"style"===k.localName&&(Za||wa)||k.addEventListener("error",p)}}function h(k){return k.nodeType===Node.ELEMENT_NODE&&"link"===k.localName&&"import"===k.rel}function m(){var k=this;this.g={};this.h=0;this.i=new MutationObserver(function(n){return k.Ra(n)});this.i.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}function l(k){t(q(k,"template"),function(n){n instanceof
HTMLTemplateElement&&(t(q(n.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]'),function(p){var r=document.createElement("script");t(p.attributes,function(z){return r.setAttribute(z.name,z.value)});r.textContent=p.textContent;p.parentNode.replaceChild(r,p)}),l(n.content))})}function q(k,n){return k.childNodes.length?k.querySelectorAll(n):Z}function t(k,n,p){var r=k?k.length:0,z=p?-1:1;for(p=p?r-1:0;p<r&&0<=p;p+=z)n(k[p],p)}var B=
document.createElement("link"),Q="import"in B,Z=B.querySelectorAll("*"),$a=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",{get:function(){return $a||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var Md=/(url\()([^)]*)(\))/g,Nd=/(@import[\s]+(?!url\())([^;]*)(;)/g,Od=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,K={Ca:function(k,n){k.href&&k.setAttribute("href",K.V(k.getAttribute("href"),n));k.src&&k.setAttribute("src",
K.V(k.getAttribute("src"),n));if("style"===k.localName){var p=K.la(k.textContent,n,Md);k.textContent=K.la(p,n,Nd)}},la:function(k,n,p){return k.replace(p,function(r,z,u,A){r=u.replace(/["']/g,"");n&&(r=K.V(r,n));return z+"'"+r+"'"+A})},V:function(k,n){if(void 0===K.Y){K.Y=!1;try{var p=new URL("b","http://a");p.pathname="c%20d";K.Y="http://a/c%20d"===p.href}catch(r){}}if(K.Y)return(new URL(k,n)).href;p=K.ta;p||(p=document.implementation.createHTMLDocument("temp"),K.ta=p,p.ea=p.createElement("base"),
p.head.appendChild(p.ea),p.da=p.createElement("a"));p.ea.href=n;p.da.href=k;return p.da.href||k}},Pd={async:!0,load:function(k,n,p){if(k)if(k.match(/^data:/)){var r=k.split(","),z=r[1];z=-1<r[0].indexOf(";base64")?atob(z):decodeURIComponent(z);n(z)}else{var u=function(N){N=void 0===N?0:N;return aa(0===N).then(function(R){n(R.Ia,R.Va)},function(R){console.error(R);if(2<=N)p();else return A(100*Math.random()*Math.pow(2,N)).then(function(){return u(N+1)})})},A=function(N){return new Promise(function(R){return setTimeout(R,
N)})},aa=function(N){var R=null;return fetch(k,{cache:N?"default":"reload"}).then(function(ba){if(!ba.ok)throw Error("HTTP "+ba.status);R=ba.url;return ba.text()}).then(function(ba){return{Ia:ba,Ua:R}})};u()}else p()}},Za=/Trident/.test(navigator.userAgent),wa=/Edge\/\d./i.test(navigator.userAgent);m.prototype.loadImports=function(k){var n=this;k=q(k,"link[rel=import]");t(k,function(p){return n.F(p)})};m.prototype.F=function(k){var n=this,p=k.href;if(void 0!==this.g[p]){var r=this.g[p];r&&r.__loaded&&
(k.__import=r,this.j(k))}else this.h++,this.g[p]="pending",Pd.load(p,function(z,u){z=n.na(z,u||p);n.g[p]=z;n.h--;n.loadImports(z);n.H()},function(){n.g[p]=null;n.h--;n.H()})};m.prototype.na=function(k,n){var p=this;if(!k)return document.createDocumentFragment();if(Za||wa)k=k.replace(Od,function(u,A,aa){return-1===u.indexOf("type=")?A+" type=import-disable "+aa:u});var r=document.createElement("template");r.innerHTML=k;if(r.content)k=r.content,l(k);else for(k=document.createDocumentFragment();r.firstChild;)k.appendChild(r.firstChild);
if(r=k.querySelector("base"))n=K.V(r.getAttribute("href"),n),r.removeAttribute("href");r=q(k,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]');var z=0;t(r,function(u){g(u);K.Ca(u,n);if("style"===u.localName&&p.ia(u)){var A=p.Ka(u);g(A);u.parentNode.replaceChild(A,u);u=A}u.setAttribute("import-dependency","");if("script"===
u.localName&&!u.src&&u.textContent){if("module"===u.type)throw Error("Inline module scripts are not supported in HTML Imports.");u.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(u.textContent+("\n//# sourceURL="+n+(z?"-"+z:"")+".js\n")));u.textContent="";z++}});return k};m.prototype.ia=function(k){return wa&&-1<k.textContent.indexOf("@import")};m.prototype.Ka=function(k){var n=k.ownerDocument.createElement("style");n.textContent=k.textContent;t(k.attributes,function(p){return n.setAttribute(p.name,
p.value)});return n};m.prototype.H=function(){var k=this;if(!this.h){this.i.disconnect();this.flatten(document);var n=!1,p=!1,r=function(){p&&n&&(k.loadImports(document),k.h||(k.i.observe(document.head,{childList:!0,subtree:!0}),k.Pa()))};this.pa(function(){p=!0;r()});this.oa(function(){n=!0;r()})}};m.prototype.flatten=function(k){var n=this;k=q(k,"link[rel=import]");t(k,function(p){var r=n.g[p.href];(p.__import=r)&&r.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(n.g[p.href]=p,p.readyState="loading",p.__import=
p,n.flatten(r),p.appendChild(r))})};m.prototype.oa=function(k){function n(z){if(z<r){var u=p[z],A=document.createElement("script");u.removeAttribute("import-dependency");t(u.attributes,function(aa){return A.setAttribute(aa.name,aa.value)});$a=A;u.parentNode.replaceChild(A,u);g(A,function(){$a=null;n(z+1)})}else k()}var p=q(document,"script[import-dependency]"),r=p.length;n(0)};m.prototype.pa=function(k){var n=this,p=q(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),r=
p.length;if(r){var z=(Za||wa)&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");t(p,function(u){z&&n.ia(u)&&u.ownerDocument.defaultView!==window.top&&(u.__loaded=!0);g(u,function(){u.removeAttribute("import-dependency");0===--r&&k()});if(z&&u.parentNode!==document.head){var A=document.createElement(u.localName);A.__appliedElement=u;A.setAttribute("type","import-placeholder");u.parentNode.insertBefore(A,u.nextSibling);for(A=c(u);A&&c(A);)A=c(A);A.parentNode!==document.head&&
(A=null);document.head.insertBefore(u,A);u.removeAttribute("type")}})}else k()};m.prototype.Pa=function(){var k=this,n=q(document,"link[rel=import]");t(n,function(p){return k.j(p)},!0)};m.prototype.j=function(k){k.__loaded||(k.__loaded=!0,k.import&&(k.import.readyState="complete"),k.dispatchEvent(b(k.import?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};m.prototype.Ra=function(k){var n=this;t(k,function(p){return t(p.addedNodes,function(r){r&&r.nodeType===Node.ELEMENT_NODE&&(h(r)?n.F(r):
n.loadImports(r))})})};var ab=null;if(Q)B=q(document,"link[rel=import]"),t(B,function(k){k.import&&"loading"===k.import.readyState||(k.__loaded=!0)}),B=function(k){k=k.target;h(k)&&(k.__loaded=!0)},document.addEventListener("load",B,!0),document.addEventListener("error",B,!0);else{var oa=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!oa||oa.configurable?Node:Element).prototype,"baseURI",{get:function(){var k=h(this)?this:c(this);return k?k.href:oa&&oa.get?oa.get.call(this):
(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});e(function(){ab=new m})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});a.useNative=Q;a.whenReady=f;a.importForElement=c;a.loadImports=function(k){ab&&ab.loadImports(k)}})(window.HTMLImports=window.HTMLImports||{});/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function ia(){this.ka=this.root=null;this.T=!1;this.D=this.P=this.$=this.assignedSlot=this.assignedNodes=this.G=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.J=void 0;this.fa=this.ga=!1;this.O={}}ia.prototype.toJSON=function(){return{}};function w(a){a.__shady||(a.__shady=new ia);return a.__shady}function x(a){return a&&a.__shady};var y=window.ShadyDOM||{};y.Ea=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ja=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");y.o=!!(ja&&ja.configurable&&ja.get);y.aa=y.force||!y.Ea;y.I=y.noPatch||!1;y.ja=y.preferPerformance;function C(a){return(a=x(a))&&void 0!==a.firstChild}function D(a){return"ShadyRoot"===a.va}function ka(a){return(a=(a=x(a))&&a.root)&&la(a)}
var ma=Element.prototype,na=ma.matches||ma.matchesSelector||ma.mozMatchesSelector||ma.msMatchesSelector||ma.oMatchesSelector||ma.webkitMatchesSelector,pa=document.createTextNode(""),qa=0,ra=[];(new MutationObserver(function(){for(;ra.length;)try{ra.shift()()}catch(a){throw pa.textContent=qa++,a;}})).observe(pa,{characterData:!0});function sa(a){ra.push(a);pa.textContent=qa++}var ta=!!document.contains;function ua(a,b){for(;b;){if(b==a)return!0;b=b.__shady_parentNode}return!1}
function va(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(e){return a[e]};a.namedItem=function(e){if("length"!==e&&isNaN(e)&&a[e])return a[e];for(var f=da(a),g=f.next();!g.done;g=f.next())if(g=g.value,(g.getAttribute("id")||g.getAttribute("name"))==e)return g;return null};return a}
function E(a,b,c,d){c=void 0===c?"":c;for(var e in b){var f=b[e];if(!(d&&0<=d.indexOf(e))){f.configurable=!0;var g=c+e;if(f.value)a[g]=f.value;else try{Object.defineProperty(a,g,f)}catch(h){}}}}function F(a){var b={};Object.getOwnPropertyNames(a).forEach(function(c){b[c]=Object.getOwnPropertyDescriptor(a,c)});return b};var xa=[],ya;function za(a){ya||(ya=!0,sa(Aa));xa.push(a)}function Aa(){ya=!1;for(var a=!!xa.length;xa.length;)xa.shift()();return a}Aa.list=xa;function Ba(){this.g=!1;this.addedNodes=[];this.removedNodes=[];this.S=new Set}function Ca(a){a.g||(a.g=!0,sa(function(){a.flush()}))}Ba.prototype.flush=function(){if(this.g){this.g=!1;var a=this.takeRecords();a.length&&this.S.forEach(function(b){b(a)})}};Ba.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function Da(a,b){var c=w(a);c.G||(c.G=new Ba);c.G.S.add(b);var d=c.G;return{ua:b,xa:d,wa:a,takeRecords:function(){return d.takeRecords()}}}function Ea(a){var b=a&&a.xa;b&&(b.S.delete(a.ua),b.S.size||(w(a.wa).G=null))}
function Fa(a,b){var c=b.getRootNode();return a.map(function(d){var e=c===d.target.getRootNode();if(e&&d.addedNodes){if(e=Array.from(d.addedNodes).filter(function(f){return c===f.getRootNode()}),e.length)return d=Object.create(d),Object.defineProperty(d,"addedNodes",{value:e,configurable:!0}),d}else if(e)return d}).filter(function(d){return d})};var Ga=/[&\u00A0"]/g,Ha=/[&\u00A0<>]/g;function Ia(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Ja(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Ka=Ja("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),La=Ja("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function Ma(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g=void 0;e<f&&(g=d[e]);e++){a:{var h=g;var m=a,l=b;switch(h.nodeType){case Node.ELEMENT_NODE:m=h.localName;for(var q="<"+m,t=h.attributes,B=0,Q;Q=t[B];B++)q+=" "+Q.name+'="'+Q.value.replace(Ga,Ia)+'"';q+=">";h=Ka[m]?q:q+Ma(h,l)+"</"+m+">";break a;case Node.TEXT_NODE:h=h.data;h=m&&La[m.localName]?h:h.replace(Ha,Ia);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var Na=y.o,Oa={querySelector:function(a){return this.__shady_native_querySelector(a)},querySelectorAll:function(a){return this.__shady_native_querySelectorAll(a)}},Pa={};function Qa(a){Pa[a]=function(b){return b["__shady_native_"+a]}}function Ra(a,b){E(a,b,"__shady_native_");for(var c in b)Qa(c)}function G(a,b){b=void 0===b?[]:b;for(var c=0;c<b.length;c++){var d=b[c],e=Object.getOwnPropertyDescriptor(a,d);e&&(Object.defineProperty(a,"__shady_native_"+d,e),e.value?Oa[d]||(Oa[d]=e.value):Qa(d))}}
var H=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),I=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1),Sa=document.implementation.createHTMLDocument("inert");function Ta(a){for(var b;b=a.__shady_native_firstChild;)a.__shady_native_removeChild(b)}var Ua=["firstElementChild","lastElementChild","children","childElementCount"],Va=["querySelector","querySelectorAll"];
function Wa(){var a=["dispatchEvent","addEventListener","removeEventListener"];window.EventTarget?G(window.EventTarget.prototype,a):(G(Node.prototype,a),G(Window.prototype,a));Na?G(Node.prototype,"parentNode firstChild lastChild previousSibling nextSibling childNodes parentElement textContent".split(" ")):Ra(Node.prototype,{parentNode:{get:function(){H.currentNode=this;return H.parentNode()}},firstChild:{get:function(){H.currentNode=this;return H.firstChild()}},lastChild:{get:function(){H.currentNode=
this;return H.lastChild()}},previousSibling:{get:function(){H.currentNode=this;return H.previousSibling()}},nextSibling:{get:function(){H.currentNode=this;return H.nextSibling()}},childNodes:{get:function(){var b=[];H.currentNode=this;for(var c=H.firstChild();c;)b.push(c),c=H.nextSibling();return b}},parentElement:{get:function(){I.currentNode=this;return I.parentNode()}},textContent:{get:function(){switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:for(var b=document.createTreeWalker(this,
NodeFilter.SHOW_TEXT,null,!1),c="",d;d=b.nextNode();)c+=d.nodeValue;return c;default:return this.nodeValue}},set:function(b){if("undefined"===typeof b||null===b)b="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:Ta(this);(0<b.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_native_insertBefore(document.createTextNode(b),void 0);break;default:this.nodeValue=b}}}});G(Node.prototype,"appendChild insertBefore removeChild replaceChild cloneNode contains".split(" "));
a={firstElementChild:{get:function(){I.currentNode=this;return I.firstChild()}},lastElementChild:{get:function(){I.currentNode=this;return I.lastChild()}},children:{get:function(){var b=[];I.currentNode=this;for(var c=I.firstChild();c;)b.push(c),c=I.nextSibling();return va(b)}},childElementCount:{get:function(){return this.children?this.children.length:0}}};Na?(G(Element.prototype,Ua),G(Element.prototype,["previousElementSibling","nextElementSibling","innerHTML"]),Object.getOwnPropertyDescriptor(HTMLElement.prototype,
"children")&&G(HTMLElement.prototype,["children"]),Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&G(HTMLElement.prototype,["innerHTML"])):(Ra(Element.prototype,a),Ra(Element.prototype,{previousElementSibling:{get:function(){I.currentNode=this;return I.previousSibling()}},nextElementSibling:{get:function(){I.currentNode=this;return I.nextSibling()}},innerHTML:{get:function(){return Ma(this,function(b){return b.__shady_native_childNodes})},set:function(b){var c="template"===this.localName?
this.content:this;Ta(c);var d=this.localName||"div";d=this.namespaceURI&&this.namespaceURI!==Sa.namespaceURI?Sa.createElementNS(this.namespaceURI,d):Sa.createElement(d);d.innerHTML=b;for(b="template"===this.localName?d.content:d;d=b.__shady_native_firstChild;)c.__shady_native_insertBefore(d,void 0)}}}));G(Element.prototype,"setAttribute getAttribute hasAttribute removeAttribute focus blur".split(" "));G(Element.prototype,Va);G(HTMLElement.prototype,["focus","blur","contains"]);Na&&G(HTMLElement.prototype,
["parentElement","children","innerHTML"]);window.HTMLTemplateElement&&G(window.HTMLTemplateElement.prototype,["innerHTML"]);Na?G(DocumentFragment.prototype,Ua):Ra(DocumentFragment.prototype,a);G(DocumentFragment.prototype,Va);Na?(G(Document.prototype,Ua),G(Document.prototype,["activeElement"])):Ra(Document.prototype,a);G(Document.prototype,["importNode","getElementById"]);G(Document.prototype,Va)};var Xa=F({get childNodes(){return this.__shady_childNodes},get firstChild(){return this.__shady_firstChild},get lastChild(){return this.__shady_lastChild},get textContent(){return this.__shady_textContent},set textContent(a){this.__shady_textContent=a},get childElementCount(){return this.__shady_childElementCount},get children(){return this.__shady_children},get firstElementChild(){return this.__shady_firstElementChild},get lastElementChild(){return this.__shady_lastElementChild},get innerHTML(){return this.__shady_innerHTML},
set innerHTML(a){return this.__shady_innerHTML=a},get shadowRoot(){return this.__shady_shadowRoot}}),Ya=F({get parentElement(){return this.__shady_parentElement},get parentNode(){return this.__shady_parentNode},get nextSibling(){return this.__shady_nextSibling},get previousSibling(){return this.__shady_previousSibling},get nextElementSibling(){return this.__shady_nextElementSibling},get previousElementSibling(){return this.__shady_previousElementSibling},get className(){return this.__shady_className},
set className(a){return this.__shady_className=a}}),bb;for(bb in Xa)Xa[bb].enumerable=!1;for(var cb in Ya)Ya[cb].enumerable=!1;var db=y.o||y.I,eb=db?function(){}:function(a){var b=w(a);b.ga||(b.ga=!0,E(a,Ya))},fb=db?function(){}:function(a){var b=w(a);b.fa||(b.fa=!0,E(a,Xa))};var gb="__eventWrappers"+Date.now(),hb=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),ib={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},jb={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function kb(a){return a instanceof Node?a.__shady_getRootNode():a}function lb(a,b){var c=[],d=a;for(a=kb(a);d;)c.push(d),d=d.__shady_assignedSlot?d.__shady_assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.__shady_parentNode;c[c.length-1]===document&&c.push(window);return c}function mb(a){a.__composedPath||(a.__composedPath=lb(a.target,!0));return a.__composedPath}
function nb(a,b){if(!D)return a;a=lb(a,!0);for(var c=0,d,e=void 0,f,g=void 0;c<b.length;c++)if(d=b[c],f=kb(d),f!==e&&(g=a.indexOf(f),e=f),!D(f)||-1<g)return d}function ob(a){function b(c,d){c=new a(c,d);c.__composed=d&&!!d.composed;return c}b.__proto__=a;b.prototype=a.prototype;return b}var pb={focus:!0,blur:!0};function qb(a){return a.__target!==a.target||a.__relatedTarget!==a.relatedTarget}
function rb(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!qb(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.__immediatePropagationStopped);d++);}
function sb(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];rb(a,d,"capture");if(a.W)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=x(d);f=f&&f.root;if(0===c||f&&f===e)if(rb(a,d,"bubble"),d!==window&&(e=d.__shady_getRootNode()),a.W)break}}
function tb(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],m=h.type,l=h.capture,q=h.once,t=h.passive;if(b===h.node&&c===m&&d===l&&e===q&&f===t)return g}return-1}
function ub(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){if(jb[a])return this.__shady_native_addEventListener(a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.X||this,m=b[gb];if(m){if(-1<tb(m,h,a,e,f,g))return}else b[gb]=[];m=function(l){f&&this.__shady_removeEventListener(a,b,c);l.__target||vb(l);if(h!==this){var q=Object.getOwnPropertyDescriptor(l,"currentTarget");
Object.defineProperty(l,"currentTarget",{get:function(){return h},configurable:!0})}l.__previousCurrentTarget=l.currentTarget;if(!D(h)||-1!=l.composedPath().indexOf(h))if(l.composed||-1<l.composedPath().indexOf(h))if(qb(l)&&l.target===l.relatedTarget)l.eventPhase===Event.BUBBLING_PHASE&&l.stopImmediatePropagation();else if(l.eventPhase===Event.CAPTURING_PHASE||l.bubbles||l.target===h||h instanceof Window){var t="function"===d?b.call(h,l):b.handleEvent&&b.handleEvent(l);h!==this&&(q?(Object.defineProperty(l,
"currentTarget",q),q=null):delete l.currentTarget);return t}};b[gb].push({node:h,type:a,capture:e,once:f,passive:g,Sa:m});pb[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][e?"capture":"bubble"].push(m)):this.__shady_native_addEventListener(a,m,c)}}}
function wb(a,b,c){if(b){if(jb[a])return this.__shady_native_removeEventListener(a,b,c);if(c&&"object"===typeof c){var d=!!c.capture;var e=!!c.once;var f=!!c.passive}else d=!!c,f=e=!1;var g=c&&c.X||this,h=void 0;var m=null;try{m=b[gb]}catch(l){}m&&(e=tb(m,g,a,d,e,f),-1<e&&(h=m.splice(e,1)[0].Sa,m.length||(b[gb]=void 0)));this.__shady_native_removeEventListener(a,h||b,c);h&&pb[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][d?"capture":"bubble"],h=a.indexOf(h),-1<h&&a.splice(h,1))}}
function xb(){for(var a in pb)window.__shady_native_addEventListener(a,function(b){b.__target||(vb(b),sb(b))},!0)}
var yb=F({get composed(){void 0===this.__composed&&(hb?this.__composed="focusin"===this.type||"focusout"===this.type||hb(this):!1!==this.isTrusted&&(this.__composed=ib[this.type]));return this.__composed||!1},composedPath:function(){this.__composedPath||(this.__composedPath=lb(this.__target,this.composed));return this.__composedPath},get target(){return nb(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.__relatedTarget)return null;this.__relatedTargetComposedPath||
(this.__relatedTargetComposedPath=lb(this.__relatedTarget,!0));return nb(this.currentTarget||this.__previousCurrentTarget,this.__relatedTargetComposedPath)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.W=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.W=this.__immediatePropagationStopped=!0}});
function vb(a){a.__target=a.target;a.__relatedTarget=a.relatedTarget;if(y.o){var b=Object.getPrototypeOf(a);if(!Object.hasOwnProperty(b,"__shady_patchedProto")){var c=Object.create(b);c.__shady_sourceProto=b;E(c,yb);b.__shady_patchedProto=c}a.__proto__=b.__shady_patchedProto}else E(a,yb)}var zb=ob(Event),Ab=ob(CustomEvent),Bb=ob(MouseEvent);
function Cb(){if(!hb&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var b=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.__shady_dispatchEvent(b)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}}var Db=Object.getOwnPropertyNames(Document.prototype).filter(function(a){return"on"===a.substring(0,2)});function Eb(a,b){return{index:a,K:[],R:b}}
function Fb(a,b,c,d){var e=0,f=0,g=0,h=0,m=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<m;g++)if(a[g]!==c[g])break a;g=m}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,q=0;q<m-g&&Gb(a[--h],c[--l]);)q++;h=q}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=Eb(e,0);f<d;)b.K.push(c[f++]);return[b]}if(f==d)return[Eb(e,b-e)];m=e;g=f;d=d-g+1;h=b-m+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(q=1;q<h;q++)if(a[m+q-1]===c[g+l-1])b[l][q]=
b[l-1][q-1];else{var t=b[l-1][q]+1,B=b[l][q-1]+1;b[l][q]=t<B?t:B}m=b.length-1;g=b[0].length-1;d=b[m][g];for(a=[];0<m||0<g;)0==m?(a.push(2),g--):0==g?(a.push(3),m--):(h=b[m-1][g-1],l=b[m-1][g],q=b[m][g-1],t=l<q?l<h?l:h:q<h?q:h,t==h?(h==d?a.push(0):(a.push(1),d=h),m--,g--):t==l?(a.push(3),m--,d=l):(a.push(2),g--,d=q));a.reverse();b=void 0;m=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(m.push(b),b=void 0);e++;f++;break;case 1:b||(b=Eb(e,0));b.R++;e++;b.K.push(c[f]);f++;break;case 2:b||(b=Eb(e,0));
b.R++;e++;break;case 3:b||(b=Eb(e,0)),b.K.push(c[f]),f++}b&&m.push(b);return m}function Gb(a,b){return a===b};function Hb(a,b,c){eb(a);c=c||null;var d=w(a),e=w(b),f=c?w(c):null;d.previousSibling=c?f.previousSibling:b.__shady_lastChild;if(f=x(d.previousSibling))f.nextSibling=a;if(f=x(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function Ib(a,b,c){fb(b);var d=w(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){d=a.__shady_childNodes;for(var e=0;e<d.length;e++)Hb(d[e],b,c);a=w(a);b=void 0!==a.firstChild?null:void 0;a.firstChild=a.lastChild=b;a.childNodes=b}else Hb(a,b,c)}
function Jb(a,b){var c=w(a);b=w(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(w(a).nextSibling=d);d&&(w(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function Kb(a){var b=w(a);if(void 0===b.firstChild){b.childNodes=null;var c=b.firstChild=a.__shady_native_firstChild||null;b.lastChild=a.__shady_native_lastChild||null;fb(a);b=c;for(c=void 0;b;b=b.__shady_native_nextSibling){var d=w(b);d.parentNode=a;d.nextSibling=b.__shady_native_nextSibling||null;d.previousSibling=c||null;c=b;eb(b)}}};var Lb=null;function J(){Lb||(Lb=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return Lb||null}function Mb(a,b){var c=J();c&&c.unscopeNode(a,b)}function Nb(a,b){var c=J();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;a=a.__shady_childNodes;for(var d=0;c&&d<a.length;d++)c=c&&Nb(a[d],b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}function Ob(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=J();return b?b.currentScopeForNode(a):""}
function Pb(a,b){if(a){a.nodeType===Node.ELEMENT_NODE&&b(a);a=a.__shady_childNodes;for(var c=0,d;c<a.length;c++)d=a[c],d.nodeType===Node.ELEMENT_NODE&&Pb(d,b)}};var Qb=window.document,Rb=y.ja,Sb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),Tb=Sb&&Sb.get;function Ub(a){for(var b;b=a.__shady_firstChild;)a.__shady_removeChild(b)}function Vb(a){var b=x(a);if(b&&void 0!==b.J){b=a.__shady_childNodes;for(var c=0,d=b.length,e=void 0;c<d&&(e=b[c]);c++)Vb(e)}if(a=x(a))a.J=void 0}function Wb(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=x(a))&&b.D)&&b.length?b[0]:Wb(a.__shady_nextSibling));return b}
function Xb(a,b,c){if(a=(a=x(a))&&a.G)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Ca(a)}
var $b=F({get parentNode(){var a=x(this);a=a&&a.parentNode;return void 0!==a?a:this.__shady_native_parentNode},get firstChild(){var a=x(this);a=a&&a.firstChild;return void 0!==a?a:this.__shady_native_firstChild},get lastChild(){var a=x(this);a=a&&a.lastChild;return void 0!==a?a:this.__shady_native_lastChild},get nextSibling(){var a=x(this);a=a&&a.nextSibling;return void 0!==a?a:this.__shady_native_nextSibling},get previousSibling(){var a=x(this);a=a&&a.previousSibling;return void 0!==a?a:this.__shady_native_previousSibling},
get childNodes(){if(C(this)){var a=x(this);if(!a.childNodes){a.childNodes=[];for(var b=this.__shady_firstChild;b;b=b.__shady_nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=this.__shady_native_childNodes;c.item=function(d){return c[d]};return c},get parentElement(){var a=x(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:this.__shady_native_parentElement},get isConnected(){if(Tb&&Tb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;
var a=this.ownerDocument;if(ta){if(a.__shady_native_contains(this))return!0}else if(a.documentElement&&a.documentElement.__shady_native_contains(this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.__shady_parentNode||(D(a)?a.host:void 0);return!!(a&&a instanceof Document)},get textContent(){if(C(this)){for(var a=[],b=0,c=this.__shady_childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&a.push(d.__shady_textContent);return a.join("")}return this.__shady_native_textContent},set textContent(a){if("undefined"===
typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!C(this)&&y.o){var b=this.__shady_firstChild;(b!=this.__shady_lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&Ub(this);this.__shady_native_textContent=a}else Ub(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.__shady_insertBefore(document.createTextNode(a));break;default:this.nodeValue=a}},insertBefore:function(a,b){if(this.ownerDocument!==Qb&&a.ownerDocument!==Qb)return this.__shady_native_insertBefore(a,
b),a;if(a===this)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(b){var c=x(b);c=c&&c.parentNode;if(void 0!==c&&c!==this||void 0===c&&b.__shady_native_parentNode!==this)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(b===a)return a;var d=[],e=(c=Yb(this))?c.host.localName:Ob(this),f=a.__shady_parentNode;if(f){var g=Ob(a);f.__shady_removeChild(a,!!c||
!Yb(a))}f=!0;var h=(!Rb||void 0===a.__noInsertionPoint)&&!Nb(a,e),m=c&&!a.__noInsertionPoint&&(!Rb||a.nodeType===Node.DOCUMENT_FRAGMENT_NODE);if(m||h)h&&(g=g||Ob(a)),Pb(a,function(l){m&&"slot"===l.localName&&d.push(l);if(h){var q=g;J()&&(q&&Mb(l,q),(q=J())&&q.scopeNode(l,e))}});if("slot"===this.localName||d.length)d.length&&(c.i=c.i||[],c.g=c.g||[],c.h=c.h||{},c.i.push.apply(c.i,d instanceof Array?d:ea(da(d)))),c&&L(c);C(this)&&(Ib(a,this,b),c=x(this),ka(this)?(L(c.root),f=!1):c.root&&(f=!1));f?(c=
D(this)?this.host:this,b?(b=Wb(b),c.__shady_native_insertBefore(a,b)):c.__shady_native_appendChild(a)):a.ownerDocument!==this.ownerDocument&&this.ownerDocument.adoptNode(a);Xb(this,a);return a},appendChild:function(a){return this.__shady_insertBefore(a)},removeChild:function(a,b){b=void 0===b?!1:b;if(this.ownerDocument!==Qb)return this.__shady_native_removeChild(a);if(a.__shady_parentNode!==this)throw Error("The node to be removed is not a child of this node: "+a);var c=Yb(a),d=c&&Zb(c,a),e=x(this);
if(C(this)&&(Jb(a,this),ka(this))){L(e.root);var f=!0}if(J()&&!b&&c){var g=Ob(a);Pb(a,function(h){Mb(h,g)})}Vb(a);c&&((b=this&&"slot"===this.localName)&&(f=!0),(d||b)&&L(c));f||(f=D(this)?this.host:this,(!e.root&&"slot"!==a.localName||f===a.__shady_native_parentNode)&&f.__shady_native_removeChild(a));Xb(this,null,a);return a},replaceChild:function(a,b){this.__shady_insertBefore(a,b);this.__shady_removeChild(b);return a},cloneNode:function(a){if("template"==this.localName)return this.__shady_native_cloneNode(a);
var b=this.__shady_native_cloneNode(!1);if(a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.__shady_childNodes;for(var c=0,d;c<a.length;c++)d=a[c].__shady_cloneNode(!0),b.__shady_appendChild(d)}return b},getRootNode:function(a){if(this&&this.nodeType){var b=w(this),c=b.J;void 0===c&&(D(this)?(c=this,b.J=c):(c=(c=this.__shady_parentNode)?c.__shady_getRootNode(a):this,document.documentElement.__shady_native_contains(this)&&(b.J=c)));return c}},contains:function(a){return ua(this,a)}});function ac(a,b,c){var d=[];bc(a.__shady_childNodes,b,c,d);return d}function bc(a,b,c,d){for(var e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var m=b,l=c,q=d,t=m(h);t&&q.push(h);l&&l(t)?h=t:(bc(h.__shady_childNodes,m,l,q),h=void 0)}if(h)break}}
var cc=F({get firstElementChild(){var a=x(this);if(a&&void 0!==a.firstChild){for(a=this.__shady_firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_firstElementChild},get lastElementChild(){var a=x(this);if(a&&void 0!==a.lastChild){for(a=this.__shady_lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_lastElementChild},get children(){return C(this)?va(Array.prototype.filter.call(this.__shady_childNodes,
function(a){return a.nodeType===Node.ELEMENT_NODE})):this.__shady_native_children},get childElementCount(){var a=this.__shady_children;return a?a.length:0}}),dc=F({querySelector:function(a){return ac(this,function(b){return na.call(b,a)},function(b){return!!b})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(this.__shady_native_querySelectorAll(a));var c=this.__shady_getRootNode();return b.filter(function(d){return d.__shady_getRootNode()==c})}return ac(this,function(d){return na.call(d,
a)})}}),ec=y.ja?Object.assign({},cc):cc;Object.assign(cc,dc);var fc=F({getElementById:function(a){return""===a?null:ac(this,function(b){return b.id==a},function(b){return!!b})[0]||null}});var gc=F({get activeElement(){var a=y.o?document.__shady_native_activeElement:document.activeElement;if(!a||!a.nodeType)return null;var b=!!D(this);if(!(this===document||b&&this.host!==a&&this.host.__shady_native_contains(a)))return null;for(b=Yb(a);b&&b!==this;)a=b.host,b=Yb(a);return this===document?b?null:a:b===this?a:null}});var hc=document.implementation.createHTMLDocument("inert"),ic=F({get innerHTML(){return C(this)?Ma("template"===this.localName?this.content:this,function(a){return a.__shady_childNodes}):this.__shady_native_innerHTML},set innerHTML(a){if("template"===this.localName)this.__shady_native_innerHTML=a;else{Ub(this);var b=this.localName||"div";b=this.namespaceURI&&this.namespaceURI!==hc.namespaceURI?hc.createElementNS(this.namespaceURI,b):hc.createElement(b);for(y.o?b.__shady_native_innerHTML=a:b.innerHTML=
a;a=b.__shady_firstChild;)this.__shady_insertBefore(a)}}});var jc=F({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.X=this;this.host.__shady_addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.X=this;this.host.__shady_removeEventListener(a,b,c)}});function kc(a,b){E(a,jc,b);E(a,gc,b);E(a,ic,b);E(a,cc,b);y.I&&!b?(E(a,$b,b),E(a,fc,b)):y.o||(E(a,Ya),E(a,Xa))};var lc={},M=y.deferConnectionCallbacks&&"loading"===document.readyState,mc;function nc(a){var b=[];do b.unshift(a);while(a=a.__shady_parentNode);return b}
function oc(a,b,c){if(a!==lc)throw new TypeError("Illegal constructor");this.va="ShadyRoot";this.host=b;this.mode=c&&c.mode;Kb(b);a=w(b);a.root=this;a.ka="closed"!==this.mode?this:null;a=w(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;a.childNodes=[];this.Z=this.C=!1;this.i=this.h=this.g=null;if(y.preferPerformance)for(;a=b.__shady_native_firstChild;)b.__shady_native_removeChild(a);else L(this)}function L(a){a.C||(a.C=!0,za(function(){return pc(a)}))}
function pc(a){var b;if(b=a.C){for(var c;a;)a:{a.C&&(c=a),b=a;a=b.host.__shady_getRootNode();if(D(a)&&(b=x(b.host))&&0<b.N)break a;a=void 0}b=c}(c=b)&&c._renderSelf()}
oc.prototype._renderSelf=function(){var a=M;M=!0;this.C=!1;if(this.g){qc(this);for(var b=0,c;b<this.g.length;b++){c=this.g[b];var d=x(c),e=d.assignedNodes;d.assignedNodes=[];d.D=[];if(d.$=e)for(d=0;d<e.length;d++){var f=x(e[d]);f.P=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(b=this.host.__shady_firstChild;b;b=b.__shady_nextSibling)rc(this,b);for(b=0;b<this.g.length;b++){c=this.g[b];e=x(c);if(!e.assignedNodes.length)for(d=c.__shady_firstChild;d;d=d.__shady_nextSibling)rc(this,d,c);
(d=(d=x(c.__shady_parentNode))&&d.root)&&(la(d)||d.C)&&d._renderSelf();sc(this,e.D,e.assignedNodes);if(d=e.$){for(f=0;f<d.length;f++)x(d[f]).P=null;e.$=null;d.length>e.assignedNodes.length&&(e.T=!0)}e.T&&(e.T=!1,tc(this,c))}c=this.g;b=[];for(e=0;e<c.length;e++)d=c[e].__shady_parentNode,(f=x(d))&&f.root||!(0>b.indexOf(d))||b.push(d);for(c=0;c<b.length;c++){f=b[c];e=f===this?this.host:f;d=[];f=f.__shady_childNodes;for(var g=0;g<f.length;g++){var h=f[g];if("slot"==h.localName){h=x(h).D;for(var m=0;m<
h.length;m++)d.push(h[m])}else d.push(h)}f=Array.prototype.slice.call(e.__shady_native_childNodes);g=Fb(d,d.length,f,f.length);m=h=0;for(var l=void 0;h<g.length&&(l=g[h]);h++){for(var q=0,t=void 0;q<l.K.length&&(t=l.K[q]);q++)t.__shady_native_parentNode===e&&e.__shady_native_removeChild(t),f.splice(l.index+m,1);m-=l.R}m=0;for(l=void 0;m<g.length&&(l=g[m]);m++)for(h=f[l.index],q=l.index;q<l.index+l.R;q++)t=d[q],e.__shady_native_insertBefore(t,h),f.splice(q,0,t)}}if(!y.preferPerformance&&!this.Z)for(b=
this.host.__shady_childNodes,c=0,e=b.length;c<e;c++)d=b[c],f=x(d),d.__shady_native_parentNode!==this.host||"slot"!==d.localName&&f.assignedSlot||this.host.__shady_native_removeChild(d);this.Z=!0;M=a;mc&&mc()};function rc(a,b,c){var d=w(b),e=d.P;d.P=null;c||(c=(a=a.h[b.__shady_slot||"__catchall"])&&a[0]);c?(w(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(w(d.assignedSlot).T=!0)}
function sc(a,b,c){for(var d=0,e=void 0;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=x(e).assignedNodes;f&&f.length&&sc(a,b,f)}else b.push(c[d])}function tc(a,b){b.__shady_native_dispatchEvent(new Event("slotchange"));b=x(b);b.assignedSlot&&tc(a,b.assignedSlot)}
function qc(a){if(a.i&&a.i.length){for(var b=a.i,c,d=0;d<b.length;d++){var e=b[d];Kb(e);var f=e.__shady_parentNode;Kb(f);f=x(f);f.N=(f.N||0)+1;f=uc(e);a.h[f]?(c=c||{},c[f]=!0,a.h[f].push(e)):a.h[f]=[e];a.g.push(e)}if(c)for(var g in c)a.h[g]=vc(a.h[g]);a.i=[]}}function uc(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.sa=b}
function vc(a){return a.sort(function(b,c){b=nc(b);for(var d=nc(c),e=0;e<b.length;e++){c=b[e];var f=d[e];if(c!==f)return b=Array.from(c.__shady_parentNode.__shady_childNodes),b.indexOf(c)-b.indexOf(f)}})}
function Zb(a,b){if(a.g){qc(a);var c=a.h,d;for(d in c)for(var e=c[d],f=0;f<e.length;f++){var g=e[f];if(ua(b,g)){e.splice(f,1);var h=a.g.indexOf(g);0<=h&&(a.g.splice(h,1),(h=x(g.__shady_parentNode))&&h.N&&h.N--);f--;g=x(g);if(h=g.D)for(var m=0;m<h.length;m++){var l=h[m],q=l.__shady_native_parentNode;q&&q.__shady_native_removeChild(l)}g.D=[];g.assignedNodes=[];h=!0}}return h}}function la(a){qc(a);return!(!a.g||!a.g.length)}
(function(a){a.__proto__=DocumentFragment.prototype;kc(a,"__shady_");kc(a);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})})(oc.prototype);
if(window.customElements&&y.aa&&!y.preferPerformance){var wc=new Map;mc=function(){var a=[];wc.forEach(function(d,e){a.push([e,d])});wc.clear();for(var b=0;b<a.length;b++){var c=a[b][0];a[b][1]?c.qa():c.ra()}};M&&document.addEventListener("readystatechange",function(){M=!1;mc()},{once:!0});var xc=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.qa=function(){M?wc.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.ra=
function(){M?this.isConnected||wc.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},yc=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;yc.call(window.customElements,a,xc(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})}function Yb(a){a=a.__shady_getRootNode();if(D(a))return a};function zc(a){this.node=a}v=zc.prototype;v.addEventListener=function(a,b,c){return this.node.__shady_addEventListener(a,b,c)};v.removeEventListener=function(a,b,c){return this.node.__shady_removeEventListener(a,b,c)};v.appendChild=function(a){return this.node.__shady_appendChild(a)};v.insertBefore=function(a,b){return this.node.__shady_insertBefore(a,b)};v.removeChild=function(a){return this.node.__shady_removeChild(a)};v.replaceChild=function(a,b){return this.node.__shady_replaceChild(a,b)};
v.cloneNode=function(a){return this.node.__shady_cloneNode(a)};v.getRootNode=function(a){return this.node.__shady_getRootNode(a)};v.contains=function(a){return this.node.__shady_contains(a)};v.dispatchEvent=function(a){return this.node.__shady_dispatchEvent(a)};v.setAttribute=function(a,b){this.node.__shady_setAttribute(a,b)};v.getAttribute=function(a){return this.node.__shady_native_getAttribute(a)};v.removeAttribute=function(a){this.node.__shady_removeAttribute(a)};v.attachShadow=function(a){return this.node.__shady_attachShadow(a)};
v.focus=function(){this.node.__shady_native_focus()};v.blur=function(){this.node.__shady_blur()};v.importNode=function(a,b){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_importNode(a,b)};v.getElementById=function(a){if(this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_getElementById(a)};v.querySelector=function(a){return this.node.__shady_querySelector(a)};v.querySelectorAll=function(a,b){return this.node.__shady_querySelectorAll(a,b)};
v.assignedNodes=function(a){if("slot"===this.node.localName)return this.node.__shady_assignedNodes(a)};
ha.Object.defineProperties(zc.prototype,{activeElement:{configurable:!0,enumerable:!0,get:function(){if(D(this.node)||this.node.nodeType===Node.DOCUMENT_NODE)return this.node.__shady_activeElement}},_activeElement:{configurable:!0,enumerable:!0,get:function(){return this.activeElement}},host:{configurable:!0,enumerable:!0,get:function(){if(D(this.node))return this.node.host}},parentNode:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_parentNode}},firstChild:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_firstChild}},lastChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastChild}},nextSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextSibling}},previousSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousSibling}},childNodes:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childNodes}},parentElement:{configurable:!0,enumerable:!0,
get:function(){return this.node.__shady_parentElement}},firstElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_firstElementChild}},lastElementChild:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_lastElementChild}},nextElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_nextElementSibling}},previousElementSibling:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_previousElementSibling}},
children:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_children}},childElementCount:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_childElementCount}},shadowRoot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_shadowRoot}},assignedSlot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_assignedSlot}},isConnected:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_isConnected}},innerHTML:{configurable:!0,
enumerable:!0,get:function(){return this.node.__shady_innerHTML},set:function(a){this.node.__shady_innerHTML=a}},textContent:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_textContent},set:function(a){this.node.__shady_textContent=a}},slot:{configurable:!0,enumerable:!0,get:function(){return this.node.__shady_slot},set:function(a){this.node.__shady_slot=a}}});
Db.forEach(function(a){Object.defineProperty(zc.prototype,a,{get:function(){return this.node["__shady_"+a]},set:function(b){this.node["__shady_"+a]=b},configurable:!0})});var Ac=new WeakMap;function Bc(a){if(D(a)||a instanceof zc)return a;var b=Ac.get(a);b||(b=new zc(a),Ac.set(a,b));return b};var Cc=F({dispatchEvent:function(a){Aa();return this.__shady_native_dispatchEvent(a)},addEventListener:ub,removeEventListener:wb});var Dc=F({get assignedSlot(){var a=this.__shady_parentNode;(a=a&&a.__shady_shadowRoot)&&pc(a);return(a=x(this))&&a.assignedSlot||null}});var Ec=window.document;function Fc(a,b){if("slot"===b)a=a.__shady_parentNode,ka(a)&&L(x(a).root);else if("slot"===a.localName&&"name"===b&&(b=Yb(a))){if(b.g){qc(b);var c=a.sa,d=uc(a);if(d!==c){c=b.h[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.h[d]||(b.h[d]=[]);c.push(a);1<c.length&&(b.h[d]=vc(c))}}L(b)}}
var Gc=F({get previousElementSibling(){var a=x(this);if(a&&void 0!==a.previousSibling){for(a=this.__shady_previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_previousSibling;return a}return this.__shady_native_previousElementSibling},get nextElementSibling(){var a=x(this);if(a&&void 0!==a.nextSibling){for(a=this.__shady_nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.__shady_nextSibling;return a}return this.__shady_native_nextElementSibling},get slot(){return this.getAttribute("slot")},
set slot(a){this.__shady_setAttribute("slot",a)},get shadowRoot(){var a=x(this);return a&&a.ka||null},get className(){return this.getAttribute("class")||""},set className(a){this.__shady_setAttribute("class",a)},setAttribute:function(a,b){if(this.ownerDocument!==Ec)this.__shady_native_setAttribute(a,b);else{var c;(c=J())&&"class"===a?(c.setElementClass(this,b),c=!0):c=!1;c||(this.__shady_native_setAttribute(a,b),Fc(this,a))}},removeAttribute:function(a){this.__shady_native_removeAttribute(a);Fc(this,
a)},attachShadow:function(a){if(!this)throw Error("Must provide a host.");if(!a)throw Error("Not enough arguments.");return new oc(lc,this,a)}});var Hc=F({blur:function(){var a=x(this);(a=(a=a&&a.root)&&a.activeElement)?a.__shady_blur():this.__shady_native_blur()}});Db.forEach(function(a){Hc[a]={set:function(b){var c=w(this),d=a.substring(2);c.O[a]&&this.removeEventListener(d,c.O[a]);this.__shady_addEventListener(d,b);c.O[a]=b},get:function(){var b=x(this);return b&&b.O[a]},configurable:!0}});var Ic=F({assignedNodes:function(a){if("slot"===this.localName){var b=this.__shady_getRootNode();b&&D(b)&&pc(b);return(b=x(this))?(a&&a.flatten?b.D:b.assignedNodes)||[]:[]}}});var Jc=window.document,Kc=F({importNode:function(a,b){if(a.ownerDocument!==Jc||"template"===a.localName)return this.__shady_native_importNode(a,b);var c=this.__shady_native_importNode(a,!1);if(b){a=a.__shady_childNodes;b=0;for(var d;b<a.length;b++)d=this.__shady_importNode(a[b],!0),c.__shady_appendChild(d)}return c}});var Lc=F({addEventListener:ub.bind(window),removeEventListener:wb.bind(window)});var Mc={};Object.getOwnPropertyDescriptor(HTMLElement.prototype,"parentElement")&&(Mc.parentElement=$b.parentElement);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"contains")&&(Mc.contains=$b.contains);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"children")&&(Mc.children=cc.children);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"innerHTML")&&(Mc.innerHTML=ic.innerHTML);Object.getOwnPropertyDescriptor(HTMLElement.prototype,"className")&&(Mc.className=Gc.className);
var Nc={EventTarget:[Cc],Node:[$b,window.EventTarget?null:Cc],Text:[Dc],Element:[Gc,cc,Dc,!y.o||"innerHTML"in Element.prototype?ic:null,window.HTMLSlotElement?null:Ic],HTMLElement:[Hc,Mc],HTMLSlotElement:[Ic],DocumentFragment:[ec,fc],Document:[Kc,ec,fc,gc],Window:[Lc]},Oc=y.o?null:["innerHTML","textContent"];function Pc(a){var b=a?null:Oc,c={},d;for(d in Nc)c.M=window[d]&&window[d].prototype,Nc[d].forEach(function(e){return function(f){return e.M&&f&&E(e.M,f,a,b)}}(c)),c={M:c.M}};if(y.aa){var ShadyDOM={inUse:y.aa,patch:function(a){fb(a);eb(a);return a},isShadyRoot:D,enqueue:za,flush:Aa,flushInitial:function(a){!a.Z&&a.C&&pc(a)},settings:y,filterMutations:Fa,observeChildren:Da,unobserveChildren:Ea,deferConnectionCallbacks:y.deferConnectionCallbacks,preferPerformance:y.preferPerformance,handlesDynamicScoping:!0,wrap:y.I?Bc:function(a){return a},Wrapper:zc,composedPath:mb,noPatch:y.I,nativeMethods:Oa,nativeTree:Pa};window.ShadyDOM=ShadyDOM;Wa();Pc("__shady_");Object.defineProperty(document,
"_activeElement",gc.activeElement);E(Window.prototype,Lc,"__shady_");y.I||(Pc(),Cb());xb();window.Event=zb;window.CustomEvent=Ab;window.MouseEvent=Bb;window.ShadowRoot=oc};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Qc(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Rc(a){var b=a=a.replace(Sc,"").replace(Tc,""),c=new Qc;c.start=0;c.end=b.length;for(var d=c,e=0,f=b.length;e<f;e++)if("{"===b[e]){d.rules||(d.rules=[]);var g=d,h=g.rules[g.rules.length-1]||null;d=new Qc;d.start=e+1;d.parent=g;d.previous=h;g.rules.push(d)}else"}"===b[e]&&(d.end=e+1,d=d.parent||c);return Uc(c,a)}
function Uc(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=Vc(c),c=c.replace(Wc," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=Xc:c.match(Yc)&&(a.type=Zc,a.keyframesName=a.selector.split(Wc).pop()):a.type=0===c.indexOf("--")?$c:ad);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)Uc(f,
b);return a}function Vc(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(b,c){b=c;for(c=6-b.length;c--;)b="0"+b;return"\\"+b})}
function bd(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules,f;if(f=e)f=e[0],f=!(f&&f.selector&&0===f.selector.indexOf("--"));if(f){f=0;for(var g=e.length,h=void 0;f<g&&(h=e[f]);f++)d=bd(h,b,d)}else b?b=a.cssText:(b=a.cssText,b=b.replace(cd,"").replace(dd,""),b=b.replace(ed,"").replace(fd,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
var ad=1,Zc=7,Xc=4,$c=1E3,Sc=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,Tc=/@import[^;]*;/gim,cd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,dd=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,ed=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,fd=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Yc=/^@[^\s]*keyframes/,Wc=/\s+/g;var O=!(window.ShadyDOM&&window.ShadyDOM.inUse),gd;function hd(a){gd=a&&a.shimcssproperties?!1:O||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var id;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&(id=window.ShadyCSS.cssBuild);var jd=!(!window.ShadyCSS||!window.ShadyCSS.disableRuntime);
window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?gd=window.ShadyCSS.nativeCss:window.ShadyCSS?(hd(window.ShadyCSS),window.ShadyCSS=void 0):hd(window.WebComponents&&window.WebComponents.flags);var P=gd;var kd=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,ld=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,md=/(--[\w-]+)\s*([:,;)]|$)/gi,nd=/(animation\s*:)|(animation-name\s*:)/,od=/@media\s(.*)/,pd=/\{[^}]*\}/g;var qd=new Set;function rd(a,b){if(!a)return"";"string"===typeof a&&(a=Rc(a));b&&sd(a,b);return bd(a,P)}function td(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Rc(a.textContent));return a.__cssRules||null}function ud(a){return!!a.parent&&a.parent.type===Zc}function sd(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&f===Xc){var g=a.selector.match(od);g&&(window.matchMedia(g[1]).matches||(e=!0))}f===ad?b(a):c&&f===Zc?c(a):f===$c&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++)sd(g,b,c,d)}}
function vd(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;wd(e,c,d);return e}var S=null;function xd(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(S?S.nextSibling:null)||b.firstChild);return S=a}function wd(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);S?a.compareDocumentPosition(S)===Node.DOCUMENT_POSITION_PRECEDING&&(S=a):S=a}
function yd(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function zd(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=yd(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=zd(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function Ad(a,b){O?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
var Bd=window.ShadyDOM&&window.ShadyDOM.wrap||function(a){return a};function T(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a.extends);return{is:b,L:c}}function Cd(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=yd(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function Dd(a){if(void 0!==id)return id;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function Ed(a){a=void 0===a?"":a;return""!==a&&P?O?"shadow"===a:"shady"===a:!1};function Fd(){}function Gd(a,b){Hd(U,a,function(c){V(c,b||"")})}function Hd(a,b,c){b.nodeType===Node.ELEMENT_NODE&&c(b);if(b="template"===b.localName?(b.content||b._content||b).childNodes:b.children||b.childNodes)for(var d=0;d<b.length;d++)Hd(a,b[d],c)}
function V(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),Ad(a,b)):Ad(a,(d?d+" ":"")+"style-scope "+b)}}function Id(a,b,c){Hd(U,a,function(d){V(d,b,!0);V(d,c)})}function Jd(a,b){Hd(U,a,function(c){V(c,b||"",!0)})}
function Kd(a,b,c,d,e){var f=U;e=void 0===e?"":e;""===e&&(O||"shady"===(void 0===d?"":d)?e=rd(b,c):(a=T(a),e=Ld(f,b,a.is,a.L,c)+"\n\n"));return e.trim()}function Ld(a,b,c,d,e){var f=Qd(c,d);c=c?"."+c:"";return rd(b,function(g){g.i||(g.selector=g.m=Rd(a,g,a.h,c,f),g.i=!0);e&&e(g,c,f)})}function Qd(a,b){return b?"[is="+a+"]":a}
function Rd(a,b,c,d,e){var f=Cd(b.selector);if(!ud(b)){b=0;for(var g=f.length,h=void 0;b<g&&(h=f[b]);b++)f[b]=c.call(a,h,d,e)}return f.filter(function(m){return!!m}).join(",")}function Sd(a){return a.replace(Td,function(b,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})}
function Ud(a){for(var b=[],c;c=a.match(Vd);){var d=c.index,e=yd(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{ca:a,matches:b}}function Wd(a,b){var c=a.split("\ue000");return b.reduce(function(d,e,f){return d+e+c[f+1]},c[0])}
Fd.prototype.h=function(a,b,c){var d=!1;a=a.trim();var e=Td.test(a);e&&(a=a.replace(Td,function(h,m,l){return":"+m+"("+l.replace(/\s/g,"")+")"}),a=Sd(a));var f=Vd.test(a);if(f){var g=Ud(a);a=g.ca;g=g.matches}a=a.replace(Xd,":host $1");a=a.replace(Yd,function(h,m,l){d||(h=Zd(l,m,b,c),d=d||h.stop,m=h.Aa,l=h.value);return m+l});f&&(a=Wd(a,g));e&&(a=Sd(a));return a};
function Zd(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=$d(a,d):0!==e&&(a=c?ae(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(be,function(g,h){return" > "+h}))}a=a.replace(ce,function(g,h,m){return'[dir="'+m+'"] '+h+", "+h+'[dir="'+m+'"]'});return{value:a,Aa:b,stop:f}}
function ae(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")}function $d(a,b){var c=a.match(de);return(c=c&&c[2].trim()||"")?c[0].match(ee)?a.replace(de,function(d,e,f){return b+f}):c.split(ee)[0]===b?c:"should_not_match":a.replace(":host",b)}function fe(a){":root"===a.selector&&(a.selector="html")}
Fd.prototype.i=function(a){return a.match(":host")?"":a.match("::slotted")?this.h(a,":not(.style-scope)"):ae(a.trim(),":not(.style-scope)")};ha.Object.defineProperties(Fd.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Td=/:(nth[-\w]+)\(([^)]+)\)/,Yd=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,ee=/[[.:#*]/,Xd=/^(::slotted)/,de=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,be=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,ce=/(.*):dir\((?:(ltr|rtl))\)/,Vd=/:(?:matches|any|-(?:webkit|moz)-any)/,U=new Fd;function ge(a,b,c,d,e){this.B=a||null;this.h=b||null;this.ba=c||[];this.s=null;this.cssBuild=e||"";this.L=d||"";this.g=this.u=this.A=null}function W(a){return a?a.__styleInfo:null}function he(a,b){return a.__styleInfo=b}ge.prototype.i=function(){return this.B};ge.prototype._getStyleRules=ge.prototype.i;function ie(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var je=navigator.userAgent.match("Trident");function ke(){}function le(a){var b={},c=[],d=0;sd(a,function(f){me(f);f.index=d++;f=f.l.cssText;for(var g;g=md.exec(f);){var h=g[1];":"!==g[2]&&(b[h]=!0)}},function(f){c.push(f)});a.h=c;a=[];for(var e in b)a.push(e);return a}
function me(a){if(!a.l){var b={},c={};ne(a,c)&&(b.v=c,a.rules=null);b.cssText=a.parsedCssText.replace(pd,"").replace(kd,"");a.l=b}}function ne(a,b){var c=a.l;if(c){if(c.v)return Object.assign(b,c.v),!0}else{c=a.parsedCssText;for(var d;a=kd.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function oe(a,b,c){b&&(b=0<=b.indexOf(";")?pe(a,b,c):zd(b,function(d,e,f,g){if(!e)return d+g;(e=oe(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=oe(a,c[f]||f,c)||f;return d+(e||"")+g}));return b&&b.trim()||""}
function pe(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){ld.lastIndex=0;if(f=ld.exec(e))e=oe(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=oe(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function qe(a,b){var c={},d=[];sd(a,function(e){e.l||me(e);var f=e.m||e.parsedSelector;b&&e.l.v&&f&&ie.call(b,f)&&(ne(e,c),e=e.index,f=parseInt(e/32,10),d[f]=(d[f]||0)|1<<e%32)},null,!0);return{v:c,key:d}}
function re(a,b,c,d){b.l||me(b);if(b.l.v){var e=T(a);a=e.is;e=e.L;e=a?Qd(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));if(g||h)c=e,h&&(b.m||(b.m=Rd(U,b,U.h,a?"."+a:"",e)),c=b.m||e),d({ca:c,Ga:h,Ta:g})}}function se(a,b,c){var d={},e={};sd(b,function(f){re(a,f,c,function(g){ie.call(a._element||a,g.ca)&&(g.Ga?ne(f,d):ne(f,e))})},null,!0);return{Ja:e,Fa:d}}
function te(a,b,c,d){var e=T(b),f=Qd(e.is,e.L),g=new RegExp("(?:^|[^.#[:])"+(b.extends?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),h=W(b);e=h.B;h=h.cssBuild;var m=ue(e,d);return Kd(b,e,function(l){var q="";l.l||me(l);l.l.cssText&&(q=pe(a,l.l.cssText,c));l.cssText=q;if(!O&&!ud(l)&&l.cssText){var t=q=l.cssText;null==l.ha&&(l.ha=nd.test(q));if(l.ha)if(null==l.U){l.U=[];for(var B in m)t=m[B],t=t(q),q!==t&&(q=t,l.U.push(B))}else{for(B=0;B<l.U.length;++B)t=m[l.U[B]],q=t(q);t=q}l.cssText=t;l.m=l.m||l.selector;
q="."+d;B=Cd(l.m);t=0;for(var Q=B.length,Z=void 0;t<Q&&(Z=B[t]);t++)B[t]=Z.match(g)?Z.replace(f,q):q+" "+Z;l.selector=B.join(",")}},h)}function ue(a,b){a=a.h;var c={};if(!O&&a)for(var d=0,e=a[d];d<a.length;e=a[++d]){var f=e,g=b;f.j=new RegExp("\\b"+f.keyframesName+"(?!\\B|-)","g");f.g=f.keyframesName+"-"+g;f.m=f.m||f.selector;f.selector=f.m.replace(f.keyframesName,f.g);c[e.keyframesName]=ve(e)}return c}function ve(a){return function(b){return b.replace(a.j,a.g)}}
function we(a,b){var c=xe,d=td(a);a.textContent=rd(d,function(e){var f=e.cssText=e.parsedCssText;e.l&&e.l.cssText&&(f=f.replace(cd,"").replace(dd,""),e.cssText=pe(c,f,b))})}ha.Object.defineProperties(ke.prototype,{g:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var xe=new ke;var ye={},ze=window.customElements;if(ze&&!O&&!jd){var Ae=ze.define;ze.define=function(a,b,c){ye[a]||(ye[a]=xd(a));Ae.call(ze,a,b,c)}};function Be(){this.cache={}}Be.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({v:b,styleElement:c,u:d});100<e.length&&e.shift();this.cache[a]=e};function Ce(){}var De=new RegExp(U.g+"\\s*([^\\s]*)");function Ee(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(De))?a[1]:""}function Fe(a){var b=Bd(a).getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?T(a).is:""}
function Ge(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g=Ee(e);if(g&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===Dd(e)))Jd(e,g);else if(f instanceof ShadowRoot)for(f=Fe(e),f!==g&&Id(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+U.g+")"),g=0;g<e.length;g++){f=e[g];
var h=Fe(f);h&&V(f,h)}}}}}
if(!(O||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var He=new MutationObserver(Ge),Ie=function(a){He.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)Ie(document);else{var Je=function(){Ie(document.body)};window.HTMLImports?window.HTMLImports.whenReady(Je):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){Je();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else Je()})}Ce=function(){Ge(He.takeRecords())}};var Ke={};var Le=Promise.resolve();function Me(a){if(a=Ke[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function Ne(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function Oe(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,Le.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var Pe={},Qe=new Be;function X(){this.H={};this.i=document.documentElement;var a=new Qc;a.rules=[];this.j=he(this.i,new ge(a));this.F=!1;this.h=this.g=null}v=X.prototype;v.flush=function(){Ce()};v.Da=function(a){return td(a)};v.Oa=function(a){return rd(a)};v.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
v.prepareTemplateStyles=function(a,b,c){if(!a._prepared&&!jd){O||ye[b]||(ye[b]=xd(b));a._prepared=!0;a.name=b;a.extends=c;Ke[b]=a;var d=Dd(a),e=Ed(d);c={is:b,extends:c};for(var f=[],g=a.content.querySelectorAll("style"),h=0;h<g.length;h++){var m=g[h];if(m.hasAttribute("shady-unscoped")){if(!O){var l=m.textContent;qd.has(l)||(qd.add(l),l=m.cloneNode(!0),document.head.appendChild(l));m.parentNode.removeChild(m)}}else f.push(m.textContent),m.parentNode.removeChild(m)}f=f.join("").trim()+(Pe[b]||"");
Re(this);if(!e){if(g=!d)g=ld.test(f)||kd.test(f),ld.lastIndex=0,kd.lastIndex=0;h=Rc(f);g&&P&&this.g&&this.g.transformRules(h,b);a._styleAst=h}g=[];P||(g=le(a._styleAst));if(!g.length||P)h=O?a.content:null,b=ye[b]||null,d=Kd(c,a._styleAst,null,d,e?f:""),d=d.length?vd(d,c.is,h,b):null,a._style=d;a.g=g}};v.Ha=function(a,b){Pe[b]=a.join(" ")};v.prepareTemplateDom=function(a,b){if(!jd){var c=Dd(a);O||"shady"===c||a._domPrepared||(a._domPrepared=!0,Gd(a.content,b))}};
function Se(a){var b=T(a),c=b.is;b=b.L;var d=ye[c]||null,e=Ke[c];if(e){c=e._styleAst;var f=e.g;e=Dd(e);b=new ge(c,d,f,b,e);he(a,b);return b}}function Te(a){!a.h&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(a.h=window.ShadyCSS.CustomStyleInterface,a.h.transformCallback=function(b){a.ma(b)},a.h.validateCallback=function(){requestAnimationFrame(function(){(a.h.enqueued||a.F)&&a.flushCustomStyles()})})}
function Re(a){!a.g&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(a.g=window.ShadyCSS.ApplyShim,a.g.invalidCallback=Me);Te(a)}
v.flushCustomStyles=function(){if(!jd&&(Re(this),this.h)){var a=this.h.processStyles();if(this.h.enqueued&&!Ed(this.j.cssBuild)){if(P){if(!this.j.cssBuild)for(var b=0;b<a.length;b++){var c=this.h.getStyleForCustomStyle(a[b]);if(c&&P&&this.g){var d=td(c);Re(this);this.g.transformRules(d);c.textContent=rd(d)}}}else{Ue(this,this.i,this.j);for(b=0;b<a.length;b++)(c=this.h.getStyleForCustomStyle(a[b]))&&we(c,this.j.A);this.F&&this.styleDocument()}this.h.enqueued=!1}}};
v.styleElement=function(a,b){if(jd){if(b){W(a)||he(a,new ge(null));var c=W(a);c.s=c.s||{};Object.assign(c.s,b);Ve(this,a,c)}}else if(c=W(a)||Se(a))if(a!==this.i&&(this.F=!0),b&&(c.s=c.s||{},Object.assign(c.s,b)),P)Ve(this,a,c);else if(this.flush(),Ue(this,a,c),c.ba&&c.ba.length){b=T(a).is;var d;a:{if(d=Qe.cache[b])for(var e=d.length-1;0<=e;e--){var f=d[e];b:{var g=c.ba;for(var h=0;h<g.length;h++){var m=g[h];if(f.v[m]!==c.A[m]){g=!1;break b}}g=!0}if(g){d=f;break a}}d=void 0}g=d?d.styleElement:null;
e=c.u;(f=d&&d.u)||(f=this.H[b]=(this.H[b]||0)+1,f=b+"-"+f);c.u=f;f=c.u;h=xe;h=g?g.textContent||"":te(h,a,c.A,f);m=W(a);var l=m.g;l&&!O&&l!==g&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));O?m.g?(m.g.textContent=h,g=m.g):h&&(g=vd(h,f,a.shadowRoot,m.h)):g?g.parentNode||(je&&-1<h.indexOf("@media")&&(g.textContent=h),wd(g,null,m.h)):h&&(g=vd(h,f,null,m.h));g&&(g._useCount=g._useCount||0,m.g!=g&&g._useCount++,m.g=g);f=g;O||(g=c.u,m=h=a.getAttribute("class")||"",e&&(m=h.replace(new RegExp("\\s*x-scope\\s*"+
e+"\\s*","g")," ")),m+=(m?" ":"")+"x-scope "+g,h!==m&&Ad(a,m));d||Qe.store(b,c.A,f,c.u)}};
function Ve(a,b,c){var d=T(b).is;if(c.s){var e=c.s,f;for(f in e)null===f?b.style.removeProperty(f):b.style.setProperty(f,e[f])}e=Ke[d];if(!(!e&&b!==a.i||e&&""!==Dd(e))&&e&&e._style&&!Ne(e)){if(Ne(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)Re(a),a.g&&a.g.transformRules(e._styleAst,d),e._style.textContent=Kd(b,c.B),Oe(e);O&&(a=b.shadowRoot)&&(a=a.querySelector("style"))&&(a.textContent=Kd(b,c.B));c.B=e._styleAst}}
function We(a,b){return(b=Bd(b).getRootNode().host)?W(b)||Se(b)?b:We(a,b):a.i}function Ue(a,b,c){var d=We(a,b),e=W(d),f=e.A;d===a.i||f||(Ue(a,d,e),f=e.A);a=Object.create(f||null);d=se(b,c.B,c.cssBuild);b=qe(e.B,b).v;Object.assign(a,d.Fa,b,d.Ja);b=c.s;for(var g in b)if((e=b[g])||0===e)a[g]=e;g=xe;b=Object.getOwnPropertyNames(a);for(e=0;e<b.length;e++)d=b[e],a[d]=oe(g,a[d],a);c.A=a}v.styleDocument=function(a){this.styleSubtree(this.i,a)};
v.styleSubtree=function(a,b){var c=Bd(a),d=c.shadowRoot;(d||a===this.i)&&this.styleElement(a,b);if(a=d&&(d.children||d.childNodes))for(c=0;c<a.length;c++)this.styleSubtree(a[c]);else if(c=c.children||c.childNodes)for(a=0;a<c.length;a++)this.styleSubtree(c[a])};
v.ma=function(a){var b=this,c=Dd(a);c!==this.j.cssBuild&&(this.j.cssBuild=c);if(!Ed(c)){var d=td(a);sd(d,function(e){if(O)fe(e);else{var f=U;e.selector=e.parsedSelector;fe(e);e.selector=e.m=Rd(f,e,f.i,void 0,void 0)}P&&""===c&&(Re(b),b.g&&b.g.transformRule(e))});P?a.textContent=rd(d):this.j.B.rules.push(d)}};v.getComputedStyleValue=function(a,b){var c;P||(c=(W(a)||W(We(this,a))).A[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};
v.Na=function(a,b){var c=Bd(a).getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===U.g){c=d[e+1];break}}}c&&b.push(U.g,c);P||(c=W(a))&&c.u&&b.push(xe.g,c.u);Ad(a,b.join(" "))};v.ya=function(a){return W(a)};v.Ma=function(a,b){V(a,b)};v.Qa=function(a,b){V(a,b,!0)};v.La=function(a){return Fe(a)};v.Ba=function(a){return Ee(a)};X.prototype.flush=X.prototype.flush;X.prototype.prepareTemplate=X.prototype.prepareTemplate;
X.prototype.styleElement=X.prototype.styleElement;X.prototype.styleDocument=X.prototype.styleDocument;X.prototype.styleSubtree=X.prototype.styleSubtree;X.prototype.getComputedStyleValue=X.prototype.getComputedStyleValue;X.prototype.setElementClass=X.prototype.Na;X.prototype._styleInfoForNode=X.prototype.ya;X.prototype.transformCustomStyleForDocument=X.prototype.ma;X.prototype.getStyleAst=X.prototype.Da;X.prototype.styleAstToString=X.prototype.Oa;X.prototype.flushCustomStyles=X.prototype.flushCustomStyles;
X.prototype.scopeNode=X.prototype.Ma;X.prototype.unscopeNode=X.prototype.Qa;X.prototype.scopeForNode=X.prototype.La;X.prototype.currentScopeForNode=X.prototype.Ba;X.prototype.prepareAdoptedCssText=X.prototype.Ha;Object.defineProperties(X.prototype,{nativeShadow:{get:function(){return O}},nativeCss:{get:function(){return P}}});var Y=new X,Xe,Ye;window.ShadyCSS&&(Xe=window.ShadyCSS.ApplyShim,Ye=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Y,prepareTemplate:function(a,b,c){Y.flushCustomStyles();Y.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Y.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Y.flushCustomStyles();Y.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Y.flushCustomStyles();Y.styleSubtree(a,b)},styleElement:function(a){Y.flushCustomStyles();Y.styleElement(a)},styleDocument:function(a){Y.flushCustomStyles();Y.styleDocument(a)},flushCustomStyles:function(){Y.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Y.getComputedStyleValue(a,b)},nativeCss:P,nativeShadow:O,cssBuild:id,disableRuntime:jd};Xe&&(window.ShadyCSS.ApplyShim=Xe);Ye&&(window.ShadyCSS.CustomStyleInterface=Ye);/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var Ze=window.customElements,$e=window.HTMLImports,af=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(Ze&&Ze.polyfillWrapFlushCallback){var bf,cf=function(){if(bf){af.za&&af.za(window.document);var a=bf;bf=null;a();return!0}},df=$e.whenReady;Ze.polyfillWrapFlushCallback(function(a){bf=a;df(cf)});$e.whenReady=function(a){df(function(){cf()?$e.whenReady(a):a()})}}
$e.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var ef=document.createElement("style");ef.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var ff=document.querySelector("head");ff.insertBefore(ef,ff.firstChild);/*

Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
}).call(this);

//# sourceMappingURL=webcomponents-hi-sd.js.map
